(*
 * WebSharper.BindingAdaptor: projects WebSharper binding packages to OCaml opam packages.
 *
 * Copyright (c) 2026 IntelliFactory.
 * All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *)

module BindingAdaptor.Generator

open System
open System.Text
open WebSharper.Core
open WebSharper.Core.AST
open WebSharper.Core.Metadata

[<Literal>]
let Header = "(* Generated by binding-adaptor. Do not edit. *)"

let private keywords =
    set [ "and"; "as"; "assert"; "begin"; "class"; "constraint"; "do"; "done"; "downto"
          "else"; "end"; "exception"; "external"; "false"; "for"; "fun"; "function"
          "functor"; "if"; "in"; "include"; "inherit"; "initializer"; "lazy"; "let"
          "match"; "method"; "module"; "mutable"; "new"; "object"; "of"; "open"; "or"
          "private"; "rec"; "sig"; "struct"; "then"; "to"; "true"; "try"; "type"
          "val"; "virtual"; "when"; "while"; "with"; "nonrec"; "land"; "lor"; "lxor"
          "lsl"; "lsr"; "asr"; "mod" ]

let lowerFirst (s: string) =
    if String.IsNullOrEmpty s then s
    else string (Char.ToLower s.[0]) + s.Substring(1)

let upperFirst (s: string) =
    if String.IsNullOrEmpty s then s
    else string (Char.ToUpper s.[0]) + s.Substring(1)

let sanitize (s: string) =
    let sb = StringBuilder()
    for c in s do
        if Char.IsLetterOrDigit c || c = '_' || c = '\'' then sb.Append c |> ignore
    let r = sb.ToString()
    let r = if r = "" then "x" else r
    let r = if Char.IsDigit r.[0] then "_" + r else r
    if keywords.Contains r then r + "_" else r

let typeParamName (n: int) =
    let letters = "abcdefghijklmnopqrstuvwxyz"
    let c = letters.[n % 26]
    let suffix = if n < 26 then "" else string (n / 26)
    sprintf "'%c%s" c suffix

let builtinType (fullName: string) =
    match fullName with
    | "System.Void" -> Some "unit"
    | "System.Boolean" -> Some "bool"
    | "System.String" -> Some "string"
    | "System.Char" -> Some "char"
    | "System.SByte" | "System.Byte" | "System.Int16" | "System.UInt16"
    | "System.Int32" | "System.UInt32" -> Some "int"
    | "System.Int64" | "System.UInt64" -> Some "int64"
    | "System.Single" -> Some "float"
    | "System.Double" -> Some "float"
    | "System.Object" -> Some "Js.t"
    | _ -> None

type TypeCtx =
    { Lookup: string -> (string * int) option
      mutable Fresh: int }

type TypeEnv =
    { LocalModules: Set<string>
      LocalArity: string -> int
      LocalByFull: Map<string, string>
      // member module -> representative module of its cyclic type-cluster
      RepOf: string -> string option
      ExternalByFull: Map<string, string * int * string>
      ExternalSimple: Map<string, string * int * string>
      Deps: System.Collections.Generic.HashSet<string> }

let rec mapType (ctx: TypeCtx) (t: Type) : string =
    match t with
    | Type.VoidType -> "unit"
    | Type.ConcreteType c ->
        let td = c.Entity.Value
        match builtinType td.FullName with
        | Some b -> b
        | None ->
            match ctx.Lookup td.FullName with
            | Some (m, arity) ->
                let gs0 = c.Generics |> List.map (mapType ctx)
                let gs =
                    if List.length gs0 >= arity then
                        List.truncate arity gs0
                    else
                        gs0
                        @ [ for _ in List.length gs0 .. arity - 1 ->
                                ctx.Fresh <- ctx.Fresh + 1
                                typeParamName (8 + ctx.Fresh) ]
                let name = if m = "" then "t" else m + ".t"
                match gs with
                | [] -> name
                | _ -> "(" + String.concat ", " gs + ") " + name
            | None -> "Js.t"
    | Type.TypeParameter i -> typeParamName i
    | Type.ArrayType(e, _) -> "(" + mapType ctx e + ") array"
    | Type.TupleType(ts, _) -> String.concat " * " (ts |> List.map (mapType ctx))
    | Type.FSharpFuncType _ -> "Js.t"
    | Type.ByRefType u -> mapType ctx u
    | _ -> "Js.t"

let rec typeDisplay (t: Type) : string =
    match t with
    | Type.VoidType -> "void"
    | Type.ConcreteType c ->
        let generics = c.Generics |> List.map typeDisplay
        match generics with
        | [] -> c.Entity.Value.FullName
        | gs -> c.Entity.Value.FullName + "<" + String.concat "," gs + ">"
    | Type.TypeParameter i -> "'" + string i
    | Type.ArrayType(e, rank) -> typeDisplay e + String.replicate rank "[]"
    | Type.TupleType(ts, _) -> "(" + String.concat "," (ts |> List.map typeDisplay) + ")"
    | Type.FSharpFuncType _ -> "fn"
    | Type.ByRefType u -> typeDisplay u
    | _ -> "?"

let methodKinds (m: CompiledMember) =
    [ if m.IsStatic then "static"
      if m.IsInstance then "instance"
      if m.IsFunc then "func"
      if m.IsGlobalFunc then "globalfunc"
      if m.IsNew then "new"
      if m.IsInline then "inline"
      if m.IsMacro then "macro" ]
    |> String.concat ","

let fieldKinds (f: CompiledField) =
    [ if f.IsStaticField then "static"
      if f.IsInstanceField then "instance"
      if f.IsIndexedField then "indexed"
      if f.IsVarField then "var" ]
    |> String.concat ","

type private MaxHoleProbe() =
    inherit Transformer()

    member val Max = -1 with get, set

    override this.TransformHole(i: int) =
        if i > this.Max then this.Max <- i
        Hole i

let private maxHole (m: CompiledMethodInfo) =
    let probe = MaxHoleProbe()
    probe.TransformExpression m.Expression |> ignore
    probe.Max

let lastSegment (fullName: string) =
    let last = fullName.Substring(fullName.LastIndexOf('.') + 1)
    if last.Contains "`" then last.Substring(0, last.IndexOf '`') else last

let simpleTypeName (fullName: string) =
    let i = max (fullName.LastIndexOf '.') (fullName.LastIndexOf '+')
    let s = if i >= 0 then fullName.Substring(i + 1) else fullName
    if s.Contains "`" then s.Substring(0, s.IndexOf '`') else s

let validModuleName (s: string) =
    s.Length > 0
    && Char.IsLetter s.[0]
    && (s |> Seq.forall (fun c -> Char.IsLetterOrDigit c || c = '_' || c = '\''))

// A JS address path identifies thin/JS classes; handwritten ([<JavaScript>])
// libraries use a placeholder path ("default") and are identified by their .NET
// type name instead.
let classModuleName (td: TypeDefinitionInfo) (address: Address) =
    let jsName =
        match List.ofSeq address.Address with
        | [] | [ "default" ] -> None
        | xs -> Some(List.last xs)
    let raw =
        match jsName with
        | Some n -> if n.Contains "`" then n.Substring(0, n.IndexOf '`') else n
        | None -> simpleTypeName td.FullName
    upperFirst raw

// Dune wraps library `foo_bar` in a module `Foo_bar`; generated packages are
// wrapped so identically-named types across packages do not collide.
let wrapModule (pkgId: string) = upperFirst (pkgId.Replace('-', '_'))

type Member =
    { Name: string
      Signature: string
      Tag: string
      Kinds: string }

type GeneratedClass =
    { Module: string
      Generics: int
      // For members of a collapsed cyclic cluster: the representative module
      // whose abstract type this module aliases (type t = Rep.t).
      Alias: string option
      Address: Address
      Methods: Member list
      Fields: Member list
      Constructors: Member list }

let receiverType (generics: int) =
    if generics = 0 then "t"
    else "(" + String.concat ", " [ for i in 0 .. generics - 1 -> typeParamName i ] + ") t"

let referencedModules (ci: ClassInfo) : string list =
    let acc = System.Collections.Generic.HashSet<string>()
    let rec go (t: Type) =
        match t with
        | Type.ConcreteType c ->
            let td = c.Entity.Value
            if (builtinType td.FullName).IsNone then
                acc.Add td.FullName |> ignore
            c.Generics |> List.iter go
        | Type.ArrayType(e, _) -> go e
        | Type.TupleType(ts, _) -> ts |> List.iter go
        | Type.ByRefType u -> go u
        | _ -> ()
    for kv in ci.Methods do
        kv.Key.Value.Parameters |> List.iter go
        go kv.Key.Value.ReturnType
    for kv in ci.Fields do
        go kv.Value.Type
    for kv in ci.Constructors do
        kv.Key.Value.CtorParameters |> List.iter go
    // Base classes / implemented interfaces keep a type hierarchy in one cluster.
    (match ci.BaseClass with
     | Some bc -> go (Type.ConcreteType bc)
     | None -> ())
    for i in ci.Implements do
        go (Type.ConcreteType i)
    acc |> Seq.toList

let stronglyConnected (nodes: string list) (edges: Map<string, Set<string>>) : Map<string, Set<string>> =
    let index = System.Collections.Generic.Dictionary<string, int>()
    let low = System.Collections.Generic.Dictionary<string, int>()
    let onStack = System.Collections.Generic.HashSet<string>()
    let stack = System.Collections.Generic.Stack<string>()
    let result = System.Collections.Generic.Dictionary<string, Set<string>>()
    let mutable idx = 0
    let succ n =
        match Map.tryFind n edges with
        | Some s -> s
        | None -> Set.empty
    let rec strongconnect (v: string) =
        index.[v] <- idx
        low.[v] <- idx
        idx <- idx + 1
        stack.Push v
        onStack.Add v |> ignore
        for w in succ v do
            if not (index.ContainsKey w) then
                strongconnect w
                low.[v] <- min low.[v] low.[w]
            elif onStack.Contains w then
                low.[v] <- min low.[v] index.[w]
        if low.[v] = index.[v] then
            let comp = System.Collections.Generic.HashSet<string>()
            let mutable go = true
            while go do
                let w = stack.Pop()
                onStack.Remove w |> ignore
                comp.Add w |> ignore
                if w = v then go <- false
            for x in comp do
                result.[x] <- Set.ofSeq comp
    for n in nodes do
        if not (index.ContainsKey n) then strongconnect n
    result |> Seq.map (fun kv -> kv.Key, kv.Value) |> Map.ofSeq

let generateClass
    (env: TypeEnv)
    (opaque: Set<string>)
    (assemblyName: string)
    (isAbstract: bool)
    (address: Address)
    (td: TypeDefinitionInfo)
    (ci: ClassInfo)
    : GeneratedClass =

    let moduleName = classModuleName td address
    let generics = ci.Generics.Length
    let addrString = address.ToString()
    let qual = assemblyName + "!" + addrString
    let recv = receiverType generics
    let alias =
        match env.RepOf moduleName with
        | Some r when r <> moduleName -> Some r
        | _ -> None

    let ctx : TypeCtx =
        { Lookup =
            (fun fullName ->
                let redirect m = match env.RepOf m with Some r -> r | None -> m
                match Map.tryFind fullName env.LocalByFull with
                | Some m ->
                    let m = redirect m
                    if m = moduleName then Some("", generics)
                    elif not (opaque.Contains m) then Some(m, env.LocalArity m)
                    else None
                | None ->
                    match Map.tryFind fullName env.ExternalByFull with
                    | Some(qm, ar, pkg) ->
                        env.Deps.Add pkg |> ignore
                        Some(qm, ar)
                    | None ->
                        let s = redirect (simpleTypeName fullName)
                        if s = moduleName then Some("", generics)
                        elif env.LocalModules.Contains s && not (opaque.Contains s) then Some(s, env.LocalArity s)
                        else
                            match Map.tryFind s env.ExternalSimple with
                            | Some(qm, ar, pkg) ->
                                env.Deps.Add pkg |> ignore
                                Some(qm, ar)
                            | None -> None)
          Fresh = 0 }

    let used = System.Collections.Generic.Dictionary<string, int>()

    let unique (baseName: string) =
        match used.TryGetValue baseName with
        | true, n ->
            used.[baseName] <- n + 1
            sprintf "%s_%d" baseName (n + 1)
        | _ ->
            used.[baseName] <- 1
            baseName

    let methods =
        ci.Methods
        |> Seq.map (fun kv ->
            let mi = kv.Key.Value
            let cmi = kv.Value
            let form = cmi.CompiledForm
            let mh = if form.IsInline then maxHole cmi else -1
            let isInstance =
                (form.IsInstance && not form.IsNew)
                || (form.IsInline && mh >= mi.Parameters.Length)
            let argTypes =
                (if isInstance then [ recv ] else [])
                @ (mi.Parameters |> List.map (mapType ctx))
            let argTypes = if argTypes = [] then [ "unit" ] else argTypes
            let ret = mapType ctx mi.ReturnType
            let name = unique (sanitize (lowerFirst mi.MethodName))
            let tag =
                let ps = mi.Parameters |> List.map typeDisplay
                sprintf "ws:%s#%s|%s" qual mi.MethodName (String.concat "|" ps)
            { Name = name
              Signature = String.concat " -> " (argTypes @ [ ret ])
              Tag = tag
              Kinds = methodKinds form })
        |> Seq.toList

    let fields =
        ci.Fields
        |> Seq.collect (fun kv ->
            let f = kv.Value.CompiledForm
            let ty = mapType ctx kv.Value.Type
            let baseName = sanitize (lowerFirst kv.Key)
            let getter =
                { Name = unique ("get_" + baseName)
                  Signature = sprintf "%s -> %s" recv ty
                  Tag = sprintf "wsget:%s#%s" qual kv.Key
                  Kinds = fieldKinds f }
            if kv.Value.ReadOnly then
                [ getter ]
            else
                let setter =
                    { Name = unique ("set_" + baseName)
                      Signature =
                        if f.IsStaticField then sprintf "%s -> unit" ty
                        else sprintf "%s -> %s -> unit" recv ty
                      Tag = sprintf "wsset:%s#%s" qual kv.Key
                      Kinds = fieldKinds f }
                [ getter; setter ])
        |> Seq.toList

    // Abstract classes have no usable constructor: `new Abstract()` yields an
    // empty object. Their instances come from static factory methods instead.
    let ctors =
        if isAbstract then
            []
        else
            ci.Constructors
            |> Seq.map (fun kv ->
                let cinfo = kv.Key.Value
                let cts = cinfo.CtorParameters |> List.map (mapType ctx)
                let cts = if cts = [] then [ "unit" ] else cts
                { Name = unique "create"
                  Signature = String.concat " -> " (cts @ [ recv ])
                  Tag = sprintf "wsnew:%s" qual
                  Kinds = methodKinds kv.Value.CompiledForm })
            |> Seq.toList

    { Module = moduleName
      Generics = generics
      Alias = alias
      Address = address
      Methods = methods
      Fields = fields
      Constructors = ctors }

let renderMember (m: Member) =
    sprintf "(* %s *)\nexternal %s : %s = \"%s\" \"%s\"\n" m.Kinds m.Name m.Signature m.Tag m.Tag

let renderClass (g: GeneratedClass) =
    let sb = StringBuilder()
    let tparams =
        if g.Generics = 0 then ""
        else "(" + String.concat ", " [ for i in 0 .. g.Generics - 1 -> typeParamName i ] + ") "
    sb.AppendLine Header |> ignore
    match g.Alias with
    | Some rep -> sb.AppendLine(sprintf "type %st = %s.t" tparams rep) |> ignore
    | None -> sb.AppendLine(sprintf "type %st" tparams) |> ignore
    for m in g.Methods do sb.Append(renderMember m) |> ignore
    for m in g.Fields do sb.Append(renderMember m) |> ignore
    for m in g.Constructors do sb.Append(renderMember m) |> ignore
    sb.ToString()
