(* Generated by scripts/gen-bindings.py. Do not edit. *)
type t
external as_js : t -> Js.t = "%identity"
external of_js : Js.t -> t = "%identity"
external create : unit -> t = "jsnew0:AbortController"
external signal : t -> AbortSignal.t = "jsgp:signal"
external abort  : t -> Js.t -> unit = "jsm:abort"
