(* Generated by scripts/gen-bindings.py. Do not edit. *)
type t = Node.t
external src             : t -> string = "jsgp:src"
external set_src         : t -> string -> unit = "jssp:src"
external source_type     : t -> string = "jsgp:type"
external set_source_type : t -> string -> unit = "jssp:type"
