(* Generated by scripts/gen-bindings.py. Do not edit. *)
type t = Node.t
external label     : t -> string = "jsgp:label"
external set_label : t -> string -> unit = "jssp:label"
external disabled  : t -> bool = "jsgp:disabled"
