(* Generated by scripts/gen-bindings.py. Do not edit. *)
type t = Node.t
external caption       : t -> t = "jsgp:caption"
external t_head        : t -> t = "jsgp:tHead"
external t_body        : t -> t = "jsgp:tBodies"
external t_foot        : t -> t = "jsgp:tFoot"
external rows          : t -> t = "jsgp:rows"
external insert_row    : t -> int -> t = "jsm:insertRow"
external delete_row    : t -> int -> unit = "jsm:deleteRow"
external create_t_head : t -> t = "jsm:createTHead"
external create_t_body : t -> t = "jsm:createTBody"
external create_t_foot : t -> t = "jsm:createTFoot"
