(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external get_Finished : unit -> t = "ws:WebSharper.JavaScript!globalThis.AnimationPlayState#get_Finished|" "ws:WebSharper.JavaScript!globalThis.AnimationPlayState#get_Finished|"
(* inline *)
external get_Paused : unit -> t = "ws:WebSharper.JavaScript!globalThis.AnimationPlayState#get_Paused|" "ws:WebSharper.JavaScript!globalThis.AnimationPlayState#get_Paused|"
(* inline *)
external get_Running : unit -> t = "ws:WebSharper.JavaScript!globalThis.AnimationPlayState#get_Running|" "ws:WebSharper.JavaScript!globalThis.AnimationPlayState#get_Running|"
(* inline *)
external get_Idle : unit -> t = "ws:WebSharper.JavaScript!globalThis.AnimationPlayState#get_Idle|" "ws:WebSharper.JavaScript!globalThis.AnimationPlayState#get_Idle|"
