(* Generated by binding-adaptor. Do not edit. *)
type t = EventTarget.t
(* inline *)
external prefix : t -> string = "ws:WebSharper.JavaScript!globalThis.Attr#get_Prefix|" "ws:WebSharper.JavaScript!globalThis.Attr#get_Prefix|"
(* inline *)
external localName : t -> string = "ws:WebSharper.JavaScript!globalThis.Attr#get_LocalName|" "ws:WebSharper.JavaScript!globalThis.Attr#get_LocalName|"
(* inline *)
external namespaceUri : t -> string = "ws:WebSharper.JavaScript!globalThis.Attr#get_NamespaceUri|" "ws:WebSharper.JavaScript!globalThis.Attr#get_NamespaceUri|"
(* inline *)
external ownerElement : t -> EventTarget.t = "ws:WebSharper.JavaScript!globalThis.Attr#get_OwnerElement|" "ws:WebSharper.JavaScript!globalThis.Attr#get_OwnerElement|"
(* inline *)
external value : t -> string = "ws:WebSharper.JavaScript!globalThis.Attr#get_Value|" "ws:WebSharper.JavaScript!globalThis.Attr#get_Value|"
(* inline *)
external specified : t -> bool = "ws:WebSharper.JavaScript!globalThis.Attr#get_Specified|" "ws:WebSharper.JavaScript!globalThis.Attr#get_Specified|"
(* inline *)
external name : t -> string = "ws:WebSharper.JavaScript!globalThis.Attr#get_Name|" "ws:WebSharper.JavaScript!globalThis.Attr#get_Name|"
(* inline *)
external set_value : t -> string -> unit = "ws:WebSharper.JavaScript!globalThis.Attr#set_Value|System.String" "ws:WebSharper.JavaScript!globalThis.Attr#set_Value|System.String"
