(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external get_Visible : t -> bool = "ws:WebSharper.JavaScript!globalThis.BarProp#get_Visible|" "ws:WebSharper.JavaScript!globalThis.BarProp#get_Visible|"
(* inline *)
external set_Visible : t -> bool -> unit = "ws:WebSharper.JavaScript!globalThis.BarProp#set_Visible|System.Boolean" "ws:WebSharper.JavaScript!globalThis.BarProp#set_Visible|System.Boolean"
