(* Generated by binding-adaptor. Do not edit. *)
type t = Object2.t
(* inline *)
external prototype : unit -> Object2.t = "ws:WebSharper.JavaScript!globalThis.Boolean#get_Prototype|" "ws:WebSharper.JavaScript!globalThis.Boolean#get_Prototype|"
(* inline *)
external self : t -> bool = "ws:WebSharper.JavaScript!globalThis.Boolean#get_Self|" "ws:WebSharper.JavaScript!globalThis.Boolean#get_Self|"
(* inline *)
external create : Js.t -> t = "wsnew:WebSharper.JavaScript!globalThis.Boolean" "wsnew:WebSharper.JavaScript!globalThis.Boolean"
