(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external geometricPrecision : unit -> t = "ws:WebSharper.JavaScript!globalThis.CanvasTextRendering#get_GeometricPrecision|" "ws:WebSharper.JavaScript!globalThis.CanvasTextRendering#get_GeometricPrecision|"
(* inline *)
external optimizeLegibility : unit -> t = "ws:WebSharper.JavaScript!globalThis.CanvasTextRendering#get_OptimizeLegibility|" "ws:WebSharper.JavaScript!globalThis.CanvasTextRendering#get_OptimizeLegibility|"
(* inline *)
external optimizeSpeed : unit -> t = "ws:WebSharper.JavaScript!globalThis.CanvasTextRendering#get_OptimizeSpeed|" "ws:WebSharper.JavaScript!globalThis.CanvasTextRendering#get_OptimizeSpeed|"
(* inline *)
external auto : unit -> t = "ws:WebSharper.JavaScript!globalThis.CanvasTextRendering#get_Auto|" "ws:WebSharper.JavaScript!globalThis.CanvasTextRendering#get_Auto|"
