(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external get_TitlingCaps : unit -> t = "ws:WebSharper.JavaScript!globalThis.CanvasFontVariantCaps#get_TitlingCaps|" "ws:WebSharper.JavaScript!globalThis.CanvasFontVariantCaps#get_TitlingCaps|"
(* inline *)
external get_Unicase : unit -> t = "ws:WebSharper.JavaScript!globalThis.CanvasFontVariantCaps#get_Unicase|" "ws:WebSharper.JavaScript!globalThis.CanvasFontVariantCaps#get_Unicase|"
(* inline *)
external get_AllPetiteCaps : unit -> t = "ws:WebSharper.JavaScript!globalThis.CanvasFontVariantCaps#get_AllPetiteCaps|" "ws:WebSharper.JavaScript!globalThis.CanvasFontVariantCaps#get_AllPetiteCaps|"
(* inline *)
external get_PetiteCaps : unit -> t = "ws:WebSharper.JavaScript!globalThis.CanvasFontVariantCaps#get_PetiteCaps|" "ws:WebSharper.JavaScript!globalThis.CanvasFontVariantCaps#get_PetiteCaps|"
(* inline *)
external get_AllSmallCaps : unit -> t = "ws:WebSharper.JavaScript!globalThis.CanvasFontVariantCaps#get_AllSmallCaps|" "ws:WebSharper.JavaScript!globalThis.CanvasFontVariantCaps#get_AllSmallCaps|"
(* inline *)
external get_SmallCaps : unit -> t = "ws:WebSharper.JavaScript!globalThis.CanvasFontVariantCaps#get_SmallCaps|" "ws:WebSharper.JavaScript!globalThis.CanvasFontVariantCaps#get_SmallCaps|"
(* inline *)
external get_Normal : unit -> t = "ws:WebSharper.JavaScript!globalThis.CanvasFontVariantCaps#get_Normal|" "ws:WebSharper.JavaScript!globalThis.CanvasFontVariantCaps#get_Normal|"
