(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external bottom : unit -> t = "ws:WebSharper.JavaScript!globalThis.CanvasTextBaseLine#get_Bottom|" "ws:WebSharper.JavaScript!globalThis.CanvasTextBaseLine#get_Bottom|"
(* inline *)
external ideographic : unit -> t = "ws:WebSharper.JavaScript!globalThis.CanvasTextBaseLine#get_Ideographic|" "ws:WebSharper.JavaScript!globalThis.CanvasTextBaseLine#get_Ideographic|"
(* inline *)
external alphabetic : unit -> t = "ws:WebSharper.JavaScript!globalThis.CanvasTextBaseLine#get_Alphabetic|" "ws:WebSharper.JavaScript!globalThis.CanvasTextBaseLine#get_Alphabetic|"
(* inline *)
external middle : unit -> t = "ws:WebSharper.JavaScript!globalThis.CanvasTextBaseLine#get_Middle|" "ws:WebSharper.JavaScript!globalThis.CanvasTextBaseLine#get_Middle|"
(* inline *)
external hanging : unit -> t = "ws:WebSharper.JavaScript!globalThis.CanvasTextBaseLine#get_Hanging|" "ws:WebSharper.JavaScript!globalThis.CanvasTextBaseLine#get_Hanging|"
(* inline *)
external top : unit -> t = "ws:WebSharper.JavaScript!globalThis.CanvasTextBaseLine#get_Top|" "ws:WebSharper.JavaScript!globalThis.CanvasTextBaseLine#get_Top|"
