(* Generated by binding-adaptor. Do not edit. *)
type t = EventTarget.t
(* inline *)
external transferControlToOffScreen : t -> Js.t = "ws:WebSharper.JavaScript!globalThis.CanvasElement#TransferControlToOffScreen|" "ws:WebSharper.JavaScript!globalThis.CanvasElement#TransferControlToOffScreen|"
(* inline *)
external toBlob : t -> Blob.t = "ws:WebSharper.JavaScript!globalThis.CanvasElement#ToBlob|" "ws:WebSharper.JavaScript!globalThis.CanvasElement#ToBlob|"
(* inline *)
external toDataURL : t -> string = "ws:WebSharper.JavaScript!globalThis.CanvasElement#ToDataURL|" "ws:WebSharper.JavaScript!globalThis.CanvasElement#ToDataURL|"
(* inline *)
external height : t -> int = "ws:WebSharper.JavaScript!globalThis.CanvasElement#get_Height|" "ws:WebSharper.JavaScript!globalThis.CanvasElement#get_Height|"
(* inline *)
external width : t -> int = "ws:WebSharper.JavaScript!globalThis.CanvasElement#get_Width|" "ws:WebSharper.JavaScript!globalThis.CanvasElement#get_Width|"
(* inline *)
external captureStream : t -> int -> EventTarget.t = "ws:WebSharper.JavaScript!globalThis.CanvasElement#CaptureStream|System.Int32" "ws:WebSharper.JavaScript!globalThis.CanvasElement#CaptureStream|System.Int32"
(* inline *)
external getContext : t -> string -> EventTarget.t = "ws:WebSharper.JavaScript!globalThis.CanvasElement#GetContext|System.String" "ws:WebSharper.JavaScript!globalThis.CanvasElement#GetContext|System.String"
(* inline *)
external toDataURL_2 : t -> string -> string = "ws:WebSharper.JavaScript!globalThis.CanvasElement#ToDataURL|System.String" "ws:WebSharper.JavaScript!globalThis.CanvasElement#ToDataURL|System.String"
(* inline *)
external set_height : t -> int -> unit = "ws:WebSharper.JavaScript!globalThis.CanvasElement#set_Height|System.Int32" "ws:WebSharper.JavaScript!globalThis.CanvasElement#set_Height|System.Int32"
(* inline *)
external set_width : t -> int -> unit = "ws:WebSharper.JavaScript!globalThis.CanvasElement#set_Width|System.Int32" "ws:WebSharper.JavaScript!globalThis.CanvasElement#set_Width|System.Int32"
(* inline *)
external toDataURL_3 : t -> string -> float -> string = "ws:WebSharper.JavaScript!globalThis.CanvasElement#ToDataURL|System.String|System.Double" "ws:WebSharper.JavaScript!globalThis.CanvasElement#ToDataURL|System.String|System.Double"
(* inline *)
external create : unit -> t = "wsnew:WebSharper.JavaScript!globalThis.CanvasElement" "wsnew:WebSharper.JavaScript!globalThis.CanvasElement"
