(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external get_Inherit : unit -> t = "ws:WebSharper.JavaScript!globalThis.CanvasTextDirection#get_Inherit|" "ws:WebSharper.JavaScript!globalThis.CanvasTextDirection#get_Inherit|"
(* inline *)
external get_Rtl : unit -> t = "ws:WebSharper.JavaScript!globalThis.CanvasTextDirection#get_Rtl|" "ws:WebSharper.JavaScript!globalThis.CanvasTextDirection#get_Rtl|"
(* inline *)
external get_Ltr : unit -> t = "ws:WebSharper.JavaScript!globalThis.CanvasTextDirection#get_Ltr|" "ws:WebSharper.JavaScript!globalThis.CanvasTextDirection#get_Ltr|"
