(* Generated by binding-adaptor. Do not edit. *)
type t = ULongRange.t
(* inline *)
external ideal : t -> int64 = "ws:WebSharper.JavaScript!globalThis.ConstrainULongRange#get_Ideal|" "ws:WebSharper.JavaScript!globalThis.ConstrainULongRange#get_Ideal|"
(* inline *)
external exact : t -> int64 = "ws:WebSharper.JavaScript!globalThis.ConstrainULongRange#get_Exact|" "ws:WebSharper.JavaScript!globalThis.ConstrainULongRange#get_Exact|"
(* inline *)
external set_ideal : t -> int64 -> unit = "ws:WebSharper.JavaScript!globalThis.ConstrainULongRange#set_Ideal|System.UInt64" "ws:WebSharper.JavaScript!globalThis.ConstrainULongRange#set_Ideal|System.UInt64"
(* inline *)
external set_exact : t -> int64 -> unit = "ws:WebSharper.JavaScript!globalThis.ConstrainULongRange#set_Exact|System.UInt64" "ws:WebSharper.JavaScript!globalThis.ConstrainULongRange#set_Exact|System.UInt64"
(* inline *)
external create : unit -> t = "wsnew:WebSharper.JavaScript!globalThis.ConstrainULongRange" "wsnew:WebSharper.JavaScript!globalThis.ConstrainULongRange"
