(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external get_ImplementationSpecific : unit -> t = "ws:WebSharper.JavaScript!globalThis.DocumentPosition#get_ImplementationSpecific|" "ws:WebSharper.JavaScript!globalThis.DocumentPosition#get_ImplementationSpecific|"
(* inline *)
external get_ContainedBy : unit -> t = "ws:WebSharper.JavaScript!globalThis.DocumentPosition#get_ContainedBy|" "ws:WebSharper.JavaScript!globalThis.DocumentPosition#get_ContainedBy|"
(* inline *)
external get_Contains : unit -> t = "ws:WebSharper.JavaScript!globalThis.DocumentPosition#get_Contains|" "ws:WebSharper.JavaScript!globalThis.DocumentPosition#get_Contains|"
(* inline *)
external get_Following : unit -> t = "ws:WebSharper.JavaScript!globalThis.DocumentPosition#get_Following|" "ws:WebSharper.JavaScript!globalThis.DocumentPosition#get_Following|"
(* inline *)
external get_Preceding : unit -> t = "ws:WebSharper.JavaScript!globalThis.DocumentPosition#get_Preceding|" "ws:WebSharper.JavaScript!globalThis.DocumentPosition#get_Preceding|"
(* inline *)
external get_Disconnected : unit -> t = "ws:WebSharper.JavaScript!globalThis.DocumentPosition#get_Disconnected|" "ws:WebSharper.JavaScript!globalThis.DocumentPosition#get_Disconnected|"
