(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external get_Name : unit -> string = "ws:WebSharper.JavaScript!globalThis.DOMException#get_Name|" "ws:WebSharper.JavaScript!globalThis.DOMException#get_Name|"
(* inline *)
external get_Message : unit -> string = "ws:WebSharper.JavaScript!globalThis.DOMException#get_Message|" "ws:WebSharper.JavaScript!globalThis.DOMException#get_Message|"
(* inline *)
external get_Code : unit -> ExceptionType.t = "ws:WebSharper.JavaScript!globalThis.DOMException#get_Code|" "ws:WebSharper.JavaScript!globalThis.DOMException#get_Code|"
