(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external get_Uri : t -> string = "ws:WebSharper.JavaScript!globalThis.DOMLocator#get_Uri|" "ws:WebSharper.JavaScript!globalThis.DOMLocator#get_Uri|"
(* inline *)
external get_RelatedNode : t -> EventTarget.t = "ws:WebSharper.JavaScript!globalThis.DOMLocator#get_RelatedNode|" "ws:WebSharper.JavaScript!globalThis.DOMLocator#get_RelatedNode|"
(* inline *)
external get_Utf16Offset : t -> int = "ws:WebSharper.JavaScript!globalThis.DOMLocator#get_Utf16Offset|" "ws:WebSharper.JavaScript!globalThis.DOMLocator#get_Utf16Offset|"
(* inline *)
external get_ByteOffset : t -> int = "ws:WebSharper.JavaScript!globalThis.DOMLocator#get_ByteOffset|" "ws:WebSharper.JavaScript!globalThis.DOMLocator#get_ByteOffset|"
(* inline *)
external get_ColumnNumber : t -> int = "ws:WebSharper.JavaScript!globalThis.DOMLocator#get_ColumnNumber|" "ws:WebSharper.JavaScript!globalThis.DOMLocator#get_ColumnNumber|"
(* inline *)
external get_LineNumber : t -> int = "ws:WebSharper.JavaScript!globalThis.DOMLocator#get_LineNumber|" "ws:WebSharper.JavaScript!globalThis.DOMLocator#get_LineNumber|"
