(* Generated by binding-adaptor. Do not edit. *)
type t = Object2.t
(* inline *)
external prototype : unit -> Object2.t = "ws:WebSharper.JavaScript!globalThis.Error#get_Prototype|" "ws:WebSharper.JavaScript!globalThis.Error#get_Prototype|"
(* inline *)
external self : t -> Js.t = "ws:WebSharper.JavaScript!globalThis.Error#get_Self|" "ws:WebSharper.JavaScript!globalThis.Error#get_Self|"
(* inline *)
external message : t -> string = "ws:WebSharper.JavaScript!globalThis.Error#get_Message|" "ws:WebSharper.JavaScript!globalThis.Error#get_Message|"
(* inline *)
external name : t -> string = "ws:WebSharper.JavaScript!globalThis.Error#get_Name|" "ws:WebSharper.JavaScript!globalThis.Error#get_Name|"
(* inline *)
external set_message : t -> string -> unit = "ws:WebSharper.JavaScript!globalThis.Error#set_Message|System.String" "ws:WebSharper.JavaScript!globalThis.Error#set_Message|System.String"
(* inline *)
external create : unit -> t = "wsnew:WebSharper.JavaScript!globalThis.Error" "wsnew:WebSharper.JavaScript!globalThis.Error"
(* inline *)
external create_2 : string -> t = "wsnew:WebSharper.JavaScript!globalThis.Error" "wsnew:WebSharper.JavaScript!globalThis.Error"
