(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external withCredentials : t -> bool = "ws:WebSharper.JavaScript!globalThis.EventSourceOptions#get_WithCredentials|" "ws:WebSharper.JavaScript!globalThis.EventSourceOptions#get_WithCredentials|"
(* inline *)
external set_withCredentials : t -> bool -> unit = "ws:WebSharper.JavaScript!globalThis.EventSourceOptions#set_WithCredentials|System.Boolean" "ws:WebSharper.JavaScript!globalThis.EventSourceOptions#set_WithCredentials|System.Boolean"
(* inline *)
external create : unit -> t = "wsnew:WebSharper.JavaScript!globalThis.EventSourceOptions" "wsnew:WebSharper.JavaScript!globalThis.EventSourceOptions"
