(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external get_TypeMismatch : unit -> t = "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_TypeMismatch|" "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_TypeMismatch|"
(* inline *)
external get_Validation : unit -> t = "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_Validation|" "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_Validation|"
(* inline *)
external get_InvalidAccess : unit -> t = "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_InvalidAccess|" "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_InvalidAccess|"
(* inline *)
external get_Namespace : unit -> t = "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_Namespace|" "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_Namespace|"
(* inline *)
external get_InvalidModification : unit -> t = "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_InvalidModification|" "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_InvalidModification|"
(* inline *)
external get_Syntax : unit -> t = "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_Syntax|" "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_Syntax|"
(* inline *)
external get_InvalidState : unit -> t = "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_InvalidState|" "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_InvalidState|"
(* inline *)
external get_InuseAttribute : unit -> t = "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_InuseAttribute|" "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_InuseAttribute|"
(* inline *)
external get_NotSupported : unit -> t = "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_NotSupported|" "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_NotSupported|"
(* inline *)
external get_NotFound : unit -> t = "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_NotFound|" "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_NotFound|"
(* inline *)
external get_NoModificationAllowed : unit -> t = "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_NoModificationAllowed|" "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_NoModificationAllowed|"
(* inline *)
external get_NoDataAllowed : unit -> t = "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_NoDataAllowed|" "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_NoDataAllowed|"
(* inline *)
external get_InvalidCharacter : unit -> t = "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_InvalidCharacter|" "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_InvalidCharacter|"
(* inline *)
external get_WrongDocument : unit -> t = "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_WrongDocument|" "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_WrongDocument|"
(* inline *)
external get_HierarchyRequestE : unit -> t = "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_HierarchyRequestE|" "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_HierarchyRequestE|"
(* inline *)
external get_DomstringSize : unit -> t = "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_DomstringSize|" "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_DomstringSize|"
(* inline *)
external get_IndexSize : unit -> t = "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_IndexSize|" "ws:WebSharper.JavaScript!globalThis.ExceptionType#get_IndexSize|"
