(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external clearWatch : t -> int -> unit = "ws:WebSharper.JavaScript!globalThis.Geolocation#ClearWatch|System.Int32" "ws:WebSharper.JavaScript!globalThis.Geolocation#ClearWatch|System.Int32"
(* inline *)
external watchPosition : t -> Js.t -> int = "ws:WebSharper.JavaScript!globalThis.Geolocation#WatchPosition|System.Action`1<WebSharper.JavaScript.Geolocation.Position>" "ws:WebSharper.JavaScript!globalThis.Geolocation#WatchPosition|System.Action`1<WebSharper.JavaScript.Geolocation.Position>"
(* inline *)
external getCurrentPosition : t -> Js.t -> unit = "ws:WebSharper.JavaScript!globalThis.Geolocation#GetCurrentPosition|System.Action`1<WebSharper.JavaScript.Geolocation.Position>" "ws:WebSharper.JavaScript!globalThis.Geolocation#GetCurrentPosition|System.Action`1<WebSharper.JavaScript.Geolocation.Position>"
(* inline *)
external watchPosition_2 : t -> Js.t -> Js.t -> int = "ws:WebSharper.JavaScript!globalThis.Geolocation#WatchPosition|System.Action`1<WebSharper.JavaScript.Geolocation.Position>|System.Action`1<WebSharper.JavaScript.Geolocation.PositionError>" "ws:WebSharper.JavaScript!globalThis.Geolocation#WatchPosition|System.Action`1<WebSharper.JavaScript.Geolocation.Position>|System.Action`1<WebSharper.JavaScript.Geolocation.PositionError>"
(* inline *)
external getCurrentPosition_2 : t -> Js.t -> Js.t -> unit = "ws:WebSharper.JavaScript!globalThis.Geolocation#GetCurrentPosition|System.Action`1<WebSharper.JavaScript.Geolocation.Position>|System.Action`1<WebSharper.JavaScript.Geolocation.PositionError>" "ws:WebSharper.JavaScript!globalThis.Geolocation#GetCurrentPosition|System.Action`1<WebSharper.JavaScript.Geolocation.Position>|System.Action`1<WebSharper.JavaScript.Geolocation.PositionError>"
(* inline *)
external watchPosition_3 : t -> Js.t -> Js.t -> PositionOptions.t -> int = "ws:WebSharper.JavaScript!globalThis.Geolocation#WatchPosition|System.Action`1<WebSharper.JavaScript.Geolocation.Position>|System.Action`1<WebSharper.JavaScript.Geolocation.PositionError>|WebSharper.JavaScript.Geolocation.PositionOptions" "ws:WebSharper.JavaScript!globalThis.Geolocation#WatchPosition|System.Action`1<WebSharper.JavaScript.Geolocation.Position>|System.Action`1<WebSharper.JavaScript.Geolocation.PositionError>|WebSharper.JavaScript.Geolocation.PositionOptions"
(* inline *)
external getCurrentPosition_3 : t -> Js.t -> Js.t -> PositionOptions.t -> unit = "ws:WebSharper.JavaScript!globalThis.Geolocation#GetCurrentPosition|System.Action`1<WebSharper.JavaScript.Geolocation.Position>|System.Action`1<WebSharper.JavaScript.Geolocation.PositionError>|WebSharper.JavaScript.Geolocation.PositionOptions" "ws:WebSharper.JavaScript!globalThis.Geolocation#GetCurrentPosition|System.Action`1<WebSharper.JavaScript.Geolocation.Position>|System.Action`1<WebSharper.JavaScript.Geolocation.PositionError>|WebSharper.JavaScript.Geolocation.PositionOptions"
