(* Generated by binding-adaptor. Do not edit. *)
type t = EventTarget.t
(* inline *)
external pause : t -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#Pause|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#Pause|"
(* inline *)
external play : t -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#Play|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#Play|"
(* inline *)
external load : t -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#Load|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#Load|"
(* inline *)
external tracks : t -> (TimedTrack.t) array = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Tracks|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Tracks|"
(* inline *)
external muted : t -> bool = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Muted|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Muted|"
(* inline *)
external volume : t -> float = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Volume|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Volume|"
(* inline *)
external controls : t -> bool = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Controls|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Controls|"
(* inline *)
external preload : t -> Preload.t = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Preload|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Preload|"
(* inline *)
external mediaGroup : t -> string = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_MediaGroup|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_MediaGroup|"
(* inline *)
external disableRemotePlayback : t -> bool = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_DisableRemotePlayback|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_DisableRemotePlayback|"
(* inline *)
external defaultMuted : t -> bool = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_DefaultMuted|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_DefaultMuted|"
(* inline *)
external crossOrigin : t -> string = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_CrossOrigin|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_CrossOrigin|"
(* inline *)
external initialTime : t -> float = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_InitialTime|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_InitialTime|"
(* inline *)
external duration : t -> float = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Duration|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Duration|"
(* inline *)
external paused : t -> bool = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Paused|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Paused|"
(* inline *)
external ended : t -> bool = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Ended|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Ended|"
(* inline *)
external seekable : t -> TimeRanges.t = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Seekable|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Seekable|"
(* inline *)
external played : t -> TimeRanges.t = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Played|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Played|"
(* inline *)
external startOffsetTime : t -> Date.t = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_StartOffsetTime|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_StartOffsetTime|"
(* inline *)
external playbackRate : t -> float = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_PlaybackRate|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_PlaybackRate|"
(* inline *)
external defaultPlaybackRate : t -> float = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_DefaultPlaybackRate|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_DefaultPlaybackRate|"
(* inline *)
external currentTime : t -> float = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_CurrentTime|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_CurrentTime|"
(* inline *)
external loop : t -> bool = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Loop|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Loop|"
(* inline *)
external autoplay : t -> bool = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Autoplay|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Autoplay|"
(* inline *)
external seeking : t -> bool = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Seeking|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Seeking|"
(* inline *)
external readyState : t -> int = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_ReadyState|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_ReadyState|"
(* inline *)
external hAVE_ENOUGH_DATA : t -> int = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_HAVE_ENOUGH_DATA|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_HAVE_ENOUGH_DATA|"
(* inline *)
external hAVE_FUTURE_DATA : t -> int = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_HAVE_FUTURE_DATA|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_HAVE_FUTURE_DATA|"
(* inline *)
external hAVE_CURRENT_DATA : t -> int = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_HAVE_CURRENT_DATA|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_HAVE_CURRENT_DATA|"
(* inline *)
external hAVE_METADATA : t -> int = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_HAVE_METADATA|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_HAVE_METADATA|"
(* inline *)
external hAVE_NOTHING : t -> int = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_HAVE_NOTHING|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_HAVE_NOTHING|"
(* inline *)
external buffered : t -> TimeRanges.t = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Buffered|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Buffered|"
(* inline *)
external networkState : t -> int = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_NetworkState|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_NetworkState|"
(* inline *)
external nETWORK_NO_SOURCE : t -> int = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_NETWORK_NO_SOURCE|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_NETWORK_NO_SOURCE|"
(* inline *)
external nETWORK_LOADING : t -> int = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_NETWORK_LOADING|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_NETWORK_LOADING|"
(* inline *)
external nETWORK_IDLE : t -> int = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_NETWORK_IDLE|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_NETWORK_IDLE|"
(* inline *)
external nETWORK_EMPTY : t -> int = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_NETWORK_EMPTY|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_NETWORK_EMPTY|"
(* inline *)
external currentSrc : t -> string = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_CurrentSrc|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_CurrentSrc|"
(* inline *)
external src : t -> string = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Src|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Src|"
(* inline *)
external error : t -> MediaError.t = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Error|" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#get_Error|"
(* inline *)
external canPlayType : t -> string -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#CanPlayType|System.String" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#CanPlayType|System.String"
(* inline *)
external set_muted : t -> bool -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#set_Muted|System.Boolean" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#set_Muted|System.Boolean"
(* inline *)
external set_volume : t -> float -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#set_Volume|System.Double" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#set_Volume|System.Double"
(* inline *)
external set_controls : t -> bool -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#set_Controls|System.Boolean" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#set_Controls|System.Boolean"
(* inline *)
external set_preload : t -> Preload.t -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#set_Preload|WebSharper.JavaScript.Preload" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#set_Preload|WebSharper.JavaScript.Preload"
(* inline *)
external set_mediaGroup : t -> string -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#set_MediaGroup|System.String" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#set_MediaGroup|System.String"
(* inline *)
external set_disableRemotePlayback : t -> bool -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#set_DisableRemotePlayback|System.Boolean" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#set_DisableRemotePlayback|System.Boolean"
(* inline *)
external set_defaultMuted : t -> bool -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#set_DefaultMuted|System.Boolean" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#set_DefaultMuted|System.Boolean"
(* inline *)
external set_crossOrigin : t -> string -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#set_CrossOrigin|System.String" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#set_CrossOrigin|System.String"
(* inline *)
external set_playbackRate : t -> float -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#set_PlaybackRate|System.Double" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#set_PlaybackRate|System.Double"
(* inline *)
external set_defaultPlaybackRate : t -> float -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#set_DefaultPlaybackRate|System.Double" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#set_DefaultPlaybackRate|System.Double"
(* inline *)
external set_currentTime : t -> float -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#set_CurrentTime|System.Double" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#set_CurrentTime|System.Double"
(* inline *)
external set_loop : t -> bool -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#set_Loop|System.Boolean" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#set_Loop|System.Boolean"
(* inline *)
external set_autoplay : t -> bool -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#set_Autoplay|System.Boolean" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#set_Autoplay|System.Boolean"
(* inline *)
external set_src : t -> string -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#set_Src|System.String" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#set_Src|System.String"
(* inline *)
external addTrack : t -> string -> TrackType.t -> string -> TimedTrack.t = "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#AddTrack|System.String|WebSharper.JavaScript.TrackType|System.String" "ws:WebSharper.JavaScript!globalThis.HTMLMediaElement#AddTrack|System.String|WebSharper.JavaScript.TrackType|System.String"
