(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external setCustomValidity : t -> string -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#SetCustomValidity|System.String" "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#SetCustomValidity|System.String"
(* inline *)
external reportValidity : t -> bool = "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#ReportValidity|" "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#ReportValidity|"
(* inline *)
external checkValidity : t -> bool = "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#CheckValidity|" "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#CheckValidity|"
(* inline *)
external get_Labels : t -> NodeList.t = "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#get_Labels|" "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#get_Labels|"
(* inline *)
external get_ValidationMessage : t -> string = "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#get_ValidationMessage|" "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#get_ValidationMessage|"
(* inline *)
external get_Validity : t -> Js.t = "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#get_Validity|" "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#get_Validity|"
(* inline *)
external get_WillValidate : t -> bool = "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#get_WillValidate|" "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#get_WillValidate|"
(* inline *)
external get_Value : t -> string = "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#get_Value|" "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#get_Value|"
(* inline *)
external set_Value : t -> string -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#set_Value|System.String" "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#set_Value|System.String"
(* inline *)
external get_DefaultValue : t -> string = "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#get_DefaultValue|" "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#get_DefaultValue|"
(* inline *)
external set_DefaultValue : t -> string -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#set_DefaultValue|System.String" "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#set_DefaultValue|System.String"
(* inline *)
external get_Type : t -> string = "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#get_Type|" "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#get_Type|"
(* inline *)
external get_Name : t -> string = "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#get_Name|" "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#get_Name|"
(* inline *)
external set_Name : t -> string -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#set_Name|System.String" "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#set_Name|System.String"
(* inline *)
external get_Form : t -> HTMLFormElement.t = "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#get_Form|" "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#get_Form|"
(* inline *)
external get_HtmlFor : t -> Js.t = "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#get_HtmlFor|" "ws:WebSharper.JavaScript!globalThis.HTMLOutputElement#get_HtmlFor|"
