(* Generated by binding-adaptor. Do not edit. *)
type t = EventTarget.t
(* inline *)
external label : t -> string = "ws:WebSharper.JavaScript!globalThis.HTMLOptGroupElement#get_Label|" "ws:WebSharper.JavaScript!globalThis.HTMLOptGroupElement#get_Label|"
(* inline *)
external disabled : t -> bool = "ws:WebSharper.JavaScript!globalThis.HTMLOptGroupElement#get_Disabled|" "ws:WebSharper.JavaScript!globalThis.HTMLOptGroupElement#get_Disabled|"
(* inline *)
external set_label : t -> string -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLOptGroupElement#set_Label|System.String" "ws:WebSharper.JavaScript!globalThis.HTMLOptGroupElement#set_Label|System.String"
(* inline *)
external set_disabled : t -> bool -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLOptGroupElement#set_Disabled|System.Boolean" "ws:WebSharper.JavaScript!globalThis.HTMLOptGroupElement#set_Disabled|System.Boolean"
