(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external setCustomValidity : t -> string -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#SetCustomValidity|System.String" "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#SetCustomValidity|System.String"
(* inline *)
external reportValidity : t -> bool = "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#ReportValidity|" "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#ReportValidity|"
(* inline *)
external checkValidity : t -> bool = "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#CheckValidity|" "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#CheckValidity|"
(* inline *)
external get_Labels : t -> NodeList.t = "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_Labels|" "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_Labels|"
(* inline *)
external get_ValidationMessage : t -> string = "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_ValidationMessage|" "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_ValidationMessage|"
(* inline *)
external get_Validity : t -> Js.t = "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_Validity|" "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_Validity|"
(* inline *)
external get_WillValidate : t -> bool = "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_WillValidate|" "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_WillValidate|"
(* inline *)
external get_Menu : t -> HTMLMenuElement.t = "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_Menu|" "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_Menu|"
(* inline *)
external set_Menu : t -> HTMLMenuElement.t -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#set_Menu|WebSharper.JavaScript.HTMLMenuElement" "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#set_Menu|WebSharper.JavaScript.HTMLMenuElement"
(* inline *)
external get_Value : t -> string = "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_Value|" "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_Value|"
(* inline *)
external set_Value : t -> string -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#set_Value|System.String" "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#set_Value|System.String"
(* inline *)
external get_Type : t -> string = "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_Type|" "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_Type|"
(* inline *)
external set_Type : t -> string -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#set_Type|System.String" "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#set_Type|System.String"
(* inline *)
external get_Name : t -> string = "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_Name|" "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_Name|"
(* inline *)
external set_Name : t -> string -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#set_Name|System.String" "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#set_Name|System.String"
(* inline *)
external get_FormTarget : t -> string = "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_FormTarget|" "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_FormTarget|"
(* inline *)
external set_FormTarget : t -> string -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#set_FormTarget|System.String" "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#set_FormTarget|System.String"
(* inline *)
external get_FormMethod : t -> string = "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_FormMethod|" "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_FormMethod|"
(* inline *)
external set_FormMethod : t -> string -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#set_FormMethod|System.String" "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#set_FormMethod|System.String"
(* inline *)
external get_FormEnctype : t -> string = "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_FormEnctype|" "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_FormEnctype|"
(* inline *)
external set_FormEnctype : t -> string -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#set_FormEnctype|System.String" "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#set_FormEnctype|System.String"
(* inline *)
external get_FormAction : t -> string = "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_FormAction|" "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_FormAction|"
(* inline *)
external set_FormAction : t -> string -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#set_FormAction|System.String" "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#set_FormAction|System.String"
(* inline *)
external get_Form : t -> HTMLFormElement.t = "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_Form|" "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_Form|"
(* inline *)
external get_Disabled : t -> bool = "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_Disabled|" "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_Disabled|"
(* inline *)
external set_Disabled : t -> bool -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#set_Disabled|System.Boolean" "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#set_Disabled|System.Boolean"
(* inline *)
external get_Autofocus : t -> bool = "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_Autofocus|" "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#get_Autofocus|"
(* inline *)
external set_Autofocus : t -> bool -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#set_Autofocus|System.Boolean" "ws:WebSharper.JavaScript!globalThis.HTMLButtonElement#set_Autofocus|System.Boolean"
