(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external get_Open : t -> bool = "ws:WebSharper.JavaScript!globalThis.HTMLDetailsElement#get_Open|" "ws:WebSharper.JavaScript!globalThis.HTMLDetailsElement#get_Open|"
(* inline *)
external set_Open : t -> bool -> unit = "ws:WebSharper.JavaScript!globalThis.HTMLDetailsElement#set_Open|System.Boolean" "ws:WebSharper.JavaScript!globalThis.HTMLDetailsElement#set_Open|System.Boolean"
