(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external namedItem : t -> string -> Js.t = "ws:WebSharper.JavaScript!globalThis.HTMLFormControlsCollection#NamedItem|System.String" "ws:WebSharper.JavaScript!globalThis.HTMLFormControlsCollection#NamedItem|System.String"
