(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external get_Script : unit -> t = "ws:WebSharper.JavaScript!globalThis.InputModeCode#get_Script|" "ws:WebSharper.JavaScript!globalThis.InputModeCode#get_Script|"
(* inline *)
external get_Multimodal : unit -> t = "ws:WebSharper.JavaScript!globalThis.InputModeCode#get_Multimodal|" "ws:WebSharper.JavaScript!globalThis.InputModeCode#get_Multimodal|"
(* inline *)
external get_Voice : unit -> t = "ws:WebSharper.JavaScript!globalThis.InputModeCode#get_Voice|" "ws:WebSharper.JavaScript!globalThis.InputModeCode#get_Voice|"
(* inline *)
external get_Handwriting : unit -> t = "ws:WebSharper.JavaScript!globalThis.InputModeCode#get_Handwriting|" "ws:WebSharper.JavaScript!globalThis.InputModeCode#get_Handwriting|"
(* inline *)
external get_Option : unit -> t = "ws:WebSharper.JavaScript!globalThis.InputModeCode#get_Option|" "ws:WebSharper.JavaScript!globalThis.InputModeCode#get_Option|"
(* inline *)
external get_Ime : unit -> t = "ws:WebSharper.JavaScript!globalThis.InputModeCode#get_Ime|" "ws:WebSharper.JavaScript!globalThis.InputModeCode#get_Ime|"
(* inline *)
external get_Drop : unit -> t = "ws:WebSharper.JavaScript!globalThis.InputModeCode#get_Drop|" "ws:WebSharper.JavaScript!globalThis.InputModeCode#get_Drop|"
(* inline *)
external get_Paste : unit -> t = "ws:WebSharper.JavaScript!globalThis.InputModeCode#get_Paste|" "ws:WebSharper.JavaScript!globalThis.InputModeCode#get_Paste|"
(* inline *)
external get_Keyboard : unit -> t = "ws:WebSharper.JavaScript!globalThis.InputModeCode#get_Keyboard|" "ws:WebSharper.JavaScript!globalThis.InputModeCode#get_Keyboard|"
(* inline *)
external get_Unknown : unit -> t = "ws:WebSharper.JavaScript!globalThis.InputModeCode#get_Unknown|" "ws:WebSharper.JavaScript!globalThis.InputModeCode#get_Unknown|"
