(* Generated by binding-adaptor. Do not edit. *)
type t = EventTarget.t
(* inline *)
external which : t -> int = "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#get_Which|" "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#get_Which|"
(* inline *)
external shiftKey : t -> bool = "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#get_ShiftKey|" "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#get_ShiftKey|"
(* inline *)
external repeat : t -> bool = "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#get_Repeat|" "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#get_Repeat|"
(* inline *)
external metaKey : t -> bool = "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#get_MetaKey|" "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#get_MetaKey|"
(* inline *)
external location : t -> int = "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#get_Location|" "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#get_Location|"
(* inline *)
external keyLocation : t -> KeyLocationCode.t = "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#get_KeyLocation|" "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#get_KeyLocation|"
(* inline *)
external keyIdentifier : t -> string = "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#get_KeyIdentifier|" "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#get_KeyIdentifier|"
(* inline *)
external keyCode : t -> int = "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#get_KeyCode|" "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#get_KeyCode|"
(* inline *)
external key : t -> string = "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#get_Key|" "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#get_Key|"
(* inline *)
external isComposing : t -> bool = "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#get_IsComposing|" "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#get_IsComposing|"
(* inline *)
external ctrlKey : t -> bool = "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#get_CtrlKey|" "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#get_CtrlKey|"
(* inline *)
external code : t -> string = "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#get_Code|" "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#get_Code|"
(* inline *)
external charCode : t -> int = "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#get_CharCode|" "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#get_CharCode|"
(* inline *)
external altKey : t -> bool = "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#get_AltKey|" "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#get_AltKey|"
(* inline *)
external getModifierState : t -> string -> bool = "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#GetModifierState|System.String" "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#GetModifierState|System.String"
(* inline *)
external set_keyLocation : t -> KeyLocationCode.t -> unit = "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#set_KeyLocation|WebSharper.JavaScript.Dom.KeyLocationCode" "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#set_KeyLocation|WebSharper.JavaScript.Dom.KeyLocationCode"
(* inline *)
external initKeyboardEvent : t -> string -> bool -> bool -> AbstractView.t -> string -> KeyLocationCode.t -> string -> unit = "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#InitKeyboardEvent|System.String|System.Boolean|System.Boolean|WebSharper.JavaScript.Dom.AbstractView|System.String|WebSharper.JavaScript.Dom.KeyLocationCode|System.String" "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#InitKeyboardEvent|System.String|System.Boolean|System.Boolean|WebSharper.JavaScript.Dom.AbstractView|System.String|WebSharper.JavaScript.Dom.KeyLocationCode|System.String"
(* inline *)
external initKeyboardEventNS : t -> string -> string -> bool -> bool -> AbstractView.t -> string -> KeyLocationCode.t -> string -> unit = "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#InitKeyboardEventNS|System.String|System.String|System.Boolean|System.Boolean|WebSharper.JavaScript.Dom.AbstractView|System.String|WebSharper.JavaScript.Dom.KeyLocationCode|System.String" "ws:WebSharper.JavaScript!globalThis.KeyboardEvent#InitKeyboardEventNS|System.String|System.String|System.Boolean|System.Boolean|WebSharper.JavaScript.Dom.AbstractView|System.String|WebSharper.JavaScript.Dom.KeyLocationCode|System.String"
