(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external joystick : unit -> t = "ws:WebSharper.JavaScript!globalThis.KeyLocationCode#get_Joystick|" "ws:WebSharper.JavaScript!globalThis.KeyLocationCode#get_Joystick|"
(* inline *)
external mobile : unit -> t = "ws:WebSharper.JavaScript!globalThis.KeyLocationCode#get_Mobile|" "ws:WebSharper.JavaScript!globalThis.KeyLocationCode#get_Mobile|"
(* inline *)
external standard : unit -> t = "ws:WebSharper.JavaScript!globalThis.KeyLocationCode#get_Standard|" "ws:WebSharper.JavaScript!globalThis.KeyLocationCode#get_Standard|"
(* inline *)
external right : unit -> t = "ws:WebSharper.JavaScript!globalThis.KeyLocationCode#get_Right|" "ws:WebSharper.JavaScript!globalThis.KeyLocationCode#get_Right|"
(* inline *)
external numpad : unit -> t = "ws:WebSharper.JavaScript!globalThis.KeyLocationCode#get_Numpad|" "ws:WebSharper.JavaScript!globalThis.KeyLocationCode#get_Numpad|"
(* inline *)
external left : unit -> t = "ws:WebSharper.JavaScript!globalThis.KeyLocationCode#get_Left|" "ws:WebSharper.JavaScript!globalThis.KeyLocationCode#get_Left|"
