(* Generated by binding-adaptor. Do not edit. *)
type t = EventTarget.t
(* inline *)
external onDeviceChange : t -> EventTarget.t -> unit = "ws:WebSharper.JavaScript!globalThis.MediaDevices#OnDeviceChange|WebSharper.JavaScript.Dom.Event" "ws:WebSharper.JavaScript!globalThis.MediaDevices#OnDeviceChange|WebSharper.JavaScript.Dom.Event"
(* inline *)
external ondevicechange : t -> EventTarget.t -> unit = "ws:WebSharper.JavaScript!globalThis.MediaDevices#Ondevicechange|WebSharper.JavaScript.Dom.Event" "ws:WebSharper.JavaScript!globalThis.MediaDevices#Ondevicechange|WebSharper.JavaScript.Dom.Event"
(* inline *)
external enumerateDevices : t -> ((Js.t) array) Promise.t = "ws:WebSharper.JavaScript!globalThis.MediaDevices#EnumerateDevices|" "ws:WebSharper.JavaScript!globalThis.MediaDevices#EnumerateDevices|"
