(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external get_Videoinput : unit -> t = "ws:WebSharper.JavaScript!globalThis.MediaDeviceKind#get_Videoinput|" "ws:WebSharper.JavaScript!globalThis.MediaDeviceKind#get_Videoinput|"
(* inline *)
external get_Audiooutput : unit -> t = "ws:WebSharper.JavaScript!globalThis.MediaDeviceKind#get_Audiooutput|" "ws:WebSharper.JavaScript!globalThis.MediaDeviceKind#get_Audiooutput|"
(* inline *)
external get_Audioinput : unit -> t = "ws:WebSharper.JavaScript!globalThis.MediaDeviceKind#get_Audioinput|" "ws:WebSharper.JavaScript!globalThis.MediaDeviceKind#get_Audioinput|"
