(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external parseInt : string -> int = "ws:WebSharper.JavaScript!globalThis.Number#ParseInt|System.String" "ws:WebSharper.JavaScript!globalThis.Number#ParseInt|System.String"
(* inline *)
external parseInt_2 : string -> int -> int = "ws:WebSharper.JavaScript!globalThis.Number#ParseInt|System.String|System.Int32" "ws:WebSharper.JavaScript!globalThis.Number#ParseInt|System.String|System.Int32"
(* inline *)
external parseFloat : string -> float = "ws:WebSharper.JavaScript!globalThis.Number#ParseFloat|System.String" "ws:WebSharper.JavaScript!globalThis.Number#ParseFloat|System.String"
(* inline *)
external isSafeInteger : Js.t -> bool = "ws:WebSharper.JavaScript!globalThis.Number#IsSafeInteger|System.Object" "ws:WebSharper.JavaScript!globalThis.Number#IsSafeInteger|System.Object"
(* inline *)
external isInteger : Js.t -> bool = "ws:WebSharper.JavaScript!globalThis.Number#IsInteger|System.Object" "ws:WebSharper.JavaScript!globalThis.Number#IsInteger|System.Object"
(* inline *)
external isFinite : Js.t -> bool = "ws:WebSharper.JavaScript!globalThis.Number#IsFinite|System.Object" "ws:WebSharper.JavaScript!globalThis.Number#IsFinite|System.Object"
(* inline *)
external isNaN : Js.t -> bool = "ws:WebSharper.JavaScript!globalThis.Number#IsNaN|System.Object" "ws:WebSharper.JavaScript!globalThis.Number#IsNaN|System.Object"
(* inline *)
external toPrecision : t -> float -> string = "ws:WebSharper.JavaScript!globalThis.Number#ToPrecision|System.Double" "ws:WebSharper.JavaScript!globalThis.Number#ToPrecision|System.Double"
(* inline *)
external toExponential : t -> string = "ws:WebSharper.JavaScript!globalThis.Number#ToExponential|" "ws:WebSharper.JavaScript!globalThis.Number#ToExponential|"
(* inline *)
external toExponential_2 : t -> int -> string = "ws:WebSharper.JavaScript!globalThis.Number#ToExponential|System.Int32" "ws:WebSharper.JavaScript!globalThis.Number#ToExponential|System.Int32"
(* inline *)
external toFixed : t -> string = "ws:WebSharper.JavaScript!globalThis.Number#ToFixed|" "ws:WebSharper.JavaScript!globalThis.Number#ToFixed|"
(* inline *)
external toFixed_2 : t -> int -> string = "ws:WebSharper.JavaScript!globalThis.Number#ToFixed|System.Int32" "ws:WebSharper.JavaScript!globalThis.Number#ToFixed|System.Int32"
(* inline *)
external toString : t -> int -> string = "ws:WebSharper.JavaScript!globalThis.Number#ToString|System.Int32" "ws:WebSharper.JavaScript!globalThis.Number#ToString|System.Int32"
(* inline *)
external get_Prototype : unit -> t = "ws:WebSharper.JavaScript!globalThis.Number#get_Prototype|" "ws:WebSharper.JavaScript!globalThis.Number#get_Prototype|"
(* inline *)
external get_MIN_SAFE_INTEGER : unit -> float = "ws:WebSharper.JavaScript!globalThis.Number#get_MIN_SAFE_INTEGER|" "ws:WebSharper.JavaScript!globalThis.Number#get_MIN_SAFE_INTEGER|"
(* inline *)
external get_MAX_SAFE_INTEGER : unit -> float = "ws:WebSharper.JavaScript!globalThis.Number#get_MAX_SAFE_INTEGER|" "ws:WebSharper.JavaScript!globalThis.Number#get_MAX_SAFE_INTEGER|"
(* inline *)
external get_EPSILON : unit -> float = "ws:WebSharper.JavaScript!globalThis.Number#get_EPSILON|" "ws:WebSharper.JavaScript!globalThis.Number#get_EPSILON|"
(* inline *)
external get_POSITIVE_INFINITY : unit -> float = "ws:WebSharper.JavaScript!globalThis.Number#get_POSITIVE_INFINITY|" "ws:WebSharper.JavaScript!globalThis.Number#get_POSITIVE_INFINITY|"
(* inline *)
external get_NEGATIVE_INFINITY : unit -> float = "ws:WebSharper.JavaScript!globalThis.Number#get_NEGATIVE_INFINITY|" "ws:WebSharper.JavaScript!globalThis.Number#get_NEGATIVE_INFINITY|"
(* inline *)
external get_NaN : unit -> float = "ws:WebSharper.JavaScript!globalThis.Number#get_NaN|" "ws:WebSharper.JavaScript!globalThis.Number#get_NaN|"
(* inline *)
external get_MIN_VALUE : unit -> float = "ws:WebSharper.JavaScript!globalThis.Number#get_MIN_VALUE|" "ws:WebSharper.JavaScript!globalThis.Number#get_MIN_VALUE|"
(* inline *)
external get_MAX_VALUE : unit -> float = "ws:WebSharper.JavaScript!globalThis.Number#get_MAX_VALUE|" "ws:WebSharper.JavaScript!globalThis.Number#get_MAX_VALUE|"
(* inline *)
external get_Self : t -> float = "ws:WebSharper.JavaScript!globalThis.Number#get_Self|" "ws:WebSharper.JavaScript!globalThis.Number#get_Self|"
(* inline *)
external create : unit -> t = "wsnew:WebSharper.JavaScript!globalThis.Number" "wsnew:WebSharper.JavaScript!globalThis.Number"
(* inline *)
external create_2 : Js.t -> t = "wsnew:WebSharper.JavaScript!globalThis.Number" "wsnew:WebSharper.JavaScript!globalThis.Number"
