(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external addPath : t -> t -> unit = "ws:WebSharper.JavaScript!globalThis.Path2D#AddPath|WebSharper.JavaScript.Path2D" "ws:WebSharper.JavaScript!globalThis.Path2D#AddPath|WebSharper.JavaScript.Path2D"
(* inline *)
external addPath_2 : t -> t -> DOMMatrix2DInit.t -> unit = "ws:WebSharper.JavaScript!globalThis.Path2D#AddPath|WebSharper.JavaScript.Path2D|WebSharper.JavaScript.DOMMatrix2DInit" "ws:WebSharper.JavaScript!globalThis.Path2D#AddPath|WebSharper.JavaScript.Path2D|WebSharper.JavaScript.DOMMatrix2DInit"
(* instance *)
external rect : t -> float -> float -> float -> float -> unit = "ws:WebSharper.JavaScript!globalThis.Path2D#Rect|System.Double|System.Double|System.Double|System.Double" "ws:WebSharper.JavaScript!globalThis.Path2D#Rect|System.Double|System.Double|System.Double|System.Double"
(* instance *)
external ellipse : t -> float -> float -> float -> float -> float -> float -> float -> unit = "ws:WebSharper.JavaScript!globalThis.Path2D#Ellipse|System.Double|System.Double|System.Double|System.Double|System.Double|System.Double|System.Double" "ws:WebSharper.JavaScript!globalThis.Path2D#Ellipse|System.Double|System.Double|System.Double|System.Double|System.Double|System.Double|System.Double"
(* instance *)
external ellipse_2 : t -> float -> float -> float -> float -> float -> float -> float -> bool -> unit = "ws:WebSharper.JavaScript!globalThis.Path2D#Ellipse|System.Double|System.Double|System.Double|System.Double|System.Double|System.Double|System.Double|System.Boolean" "ws:WebSharper.JavaScript!globalThis.Path2D#Ellipse|System.Double|System.Double|System.Double|System.Double|System.Double|System.Double|System.Double|System.Boolean"
(* instance *)
external arcTo : t -> float -> float -> float -> float -> float -> unit = "ws:WebSharper.JavaScript!globalThis.Path2D#ArcTo|System.Double|System.Double|System.Double|System.Double|System.Double" "ws:WebSharper.JavaScript!globalThis.Path2D#ArcTo|System.Double|System.Double|System.Double|System.Double|System.Double"
(* instance *)
external arc : t -> float -> float -> float -> float -> float -> unit = "ws:WebSharper.JavaScript!globalThis.Path2D#Arc|System.Double|System.Double|System.Double|System.Double|System.Double" "ws:WebSharper.JavaScript!globalThis.Path2D#Arc|System.Double|System.Double|System.Double|System.Double|System.Double"
(* instance *)
external arc_2 : t -> float -> float -> float -> float -> float -> bool -> unit = "ws:WebSharper.JavaScript!globalThis.Path2D#Arc|System.Double|System.Double|System.Double|System.Double|System.Double|System.Boolean" "ws:WebSharper.JavaScript!globalThis.Path2D#Arc|System.Double|System.Double|System.Double|System.Double|System.Double|System.Boolean"
(* instance *)
external quadraticCurveTo : t -> float -> float -> float -> float -> unit = "ws:WebSharper.JavaScript!globalThis.Path2D#QuadraticCurveTo|System.Double|System.Double|System.Double|System.Double" "ws:WebSharper.JavaScript!globalThis.Path2D#QuadraticCurveTo|System.Double|System.Double|System.Double|System.Double"
(* instance *)
external bezierCurveTo : t -> float -> float -> float -> float -> float -> float -> unit = "ws:WebSharper.JavaScript!globalThis.Path2D#BezierCurveTo|System.Double|System.Double|System.Double|System.Double|System.Double|System.Double" "ws:WebSharper.JavaScript!globalThis.Path2D#BezierCurveTo|System.Double|System.Double|System.Double|System.Double|System.Double|System.Double"
(* instance *)
external lineTo : t -> float -> float -> unit = "ws:WebSharper.JavaScript!globalThis.Path2D#LineTo|System.Double|System.Double" "ws:WebSharper.JavaScript!globalThis.Path2D#LineTo|System.Double|System.Double"
(* instance *)
external moveTo : t -> float -> float -> unit = "ws:WebSharper.JavaScript!globalThis.Path2D#MoveTo|System.Double|System.Double" "ws:WebSharper.JavaScript!globalThis.Path2D#MoveTo|System.Double|System.Double"
(* instance *)
external roundRect : t -> float -> float -> float -> float -> unit = "ws:WebSharper.JavaScript!globalThis.Path2D#RoundRect|System.Double|System.Double|System.Double|System.Double" "ws:WebSharper.JavaScript!globalThis.Path2D#RoundRect|System.Double|System.Double|System.Double|System.Double"
(* instance *)
external roundRect_2 : t -> float -> float -> float -> float -> float -> unit = "ws:WebSharper.JavaScript!globalThis.Path2D#RoundRect|System.Double|System.Double|System.Double|System.Double|System.Double" "ws:WebSharper.JavaScript!globalThis.Path2D#RoundRect|System.Double|System.Double|System.Double|System.Double|System.Double"
(* instance *)
external roundRect_3 : t -> float -> float -> float -> float -> DOMPointInit.t -> unit = "ws:WebSharper.JavaScript!globalThis.Path2D#RoundRect|System.Double|System.Double|System.Double|System.Double|WebSharper.JavaScript.DOMPointInit" "ws:WebSharper.JavaScript!globalThis.Path2D#RoundRect|System.Double|System.Double|System.Double|System.Double|WebSharper.JavaScript.DOMPointInit"
(* instance *)
external roundRect_4 : t -> float -> float -> float -> float -> (float) array -> unit = "ws:WebSharper.JavaScript!globalThis.Path2D#RoundRect|System.Double|System.Double|System.Double|System.Double|System.Double[]" "ws:WebSharper.JavaScript!globalThis.Path2D#RoundRect|System.Double|System.Double|System.Double|System.Double|System.Double[]"
(* instance *)
external roundRect_5 : t -> float -> float -> float -> float -> (DOMPointInit.t) array -> unit = "ws:WebSharper.JavaScript!globalThis.Path2D#RoundRect|System.Double|System.Double|System.Double|System.Double|WebSharper.JavaScript.DOMPointInit[]" "ws:WebSharper.JavaScript!globalThis.Path2D#RoundRect|System.Double|System.Double|System.Double|System.Double|WebSharper.JavaScript.DOMPointInit[]"
(* instance *)
external closePath : t -> unit = "ws:WebSharper.JavaScript!globalThis.Path2D#ClosePath|" "ws:WebSharper.JavaScript!globalThis.Path2D#ClosePath|"
(* inline *)
external create : string -> t = "wsnew:WebSharper.JavaScript!globalThis.Path2D" "wsnew:WebSharper.JavaScript!globalThis.Path2D"
(* inline *)
external create_2 : t -> t = "wsnew:WebSharper.JavaScript!globalThis.Path2D" "wsnew:WebSharper.JavaScript!globalThis.Path2D"
(* inline *)
external create_3 : unit -> t = "wsnew:WebSharper.JavaScript!globalThis.Path2D" "wsnew:WebSharper.JavaScript!globalThis.Path2D"
