(* Generated by binding-adaptor. Do not edit. *)
type t = EventTarget.t
(* inline *)
external total : t -> int = "ws:WebSharper.JavaScript!globalThis.ProgressEvent#get_Total|" "ws:WebSharper.JavaScript!globalThis.ProgressEvent#get_Total|"
(* inline *)
external loaded : t -> int = "ws:WebSharper.JavaScript!globalThis.ProgressEvent#get_Loaded|" "ws:WebSharper.JavaScript!globalThis.ProgressEvent#get_Loaded|"
(* inline *)
external lengthComputable : t -> bool = "ws:WebSharper.JavaScript!globalThis.ProgressEvent#get_LengthComputable|" "ws:WebSharper.JavaScript!globalThis.ProgressEvent#get_LengthComputable|"
