(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external intersectsNode : t -> Js.t -> bool = "ws:WebSharper.JavaScript!globalThis.Range#IntersectsNode|WebSharper.JavaScript.Dom.Node" "ws:WebSharper.JavaScript!globalThis.Range#IntersectsNode|WebSharper.JavaScript.Dom.Node"
(* inline *)
external comparePoint : t -> Js.t -> int -> int = "ws:WebSharper.JavaScript!globalThis.Range#ComparePoint|WebSharper.JavaScript.Dom.Node|System.Int32" "ws:WebSharper.JavaScript!globalThis.Range#ComparePoint|WebSharper.JavaScript.Dom.Node|System.Int32"
(* inline *)
external isPointInRange : t -> Js.t -> int -> bool = "ws:WebSharper.JavaScript!globalThis.Range#IsPointInRange|WebSharper.JavaScript.Dom.Node|System.Int32" "ws:WebSharper.JavaScript!globalThis.Range#IsPointInRange|WebSharper.JavaScript.Dom.Node|System.Int32"
(* inline *)
external detach : t -> unit = "ws:WebSharper.JavaScript!globalThis.Range#Detach|" "ws:WebSharper.JavaScript!globalThis.Range#Detach|"
(* inline *)
external cloneRange : t -> t = "ws:WebSharper.JavaScript!globalThis.Range#CloneRange|" "ws:WebSharper.JavaScript!globalThis.Range#CloneRange|"
(* inline *)
external surroundContents : t -> Js.t -> unit = "ws:WebSharper.JavaScript!globalThis.Range#SurroundContents|WebSharper.JavaScript.Dom.Node" "ws:WebSharper.JavaScript!globalThis.Range#SurroundContents|WebSharper.JavaScript.Dom.Node"
(* inline *)
external insertNode : t -> Js.t -> unit = "ws:WebSharper.JavaScript!globalThis.Range#InsertNode|WebSharper.JavaScript.Dom.Node" "ws:WebSharper.JavaScript!globalThis.Range#InsertNode|WebSharper.JavaScript.Dom.Node"
(* inline *)
external cloneContents : t -> Js.t = "ws:WebSharper.JavaScript!globalThis.Range#CloneContents|" "ws:WebSharper.JavaScript!globalThis.Range#CloneContents|"
(* inline *)
external extractContents : t -> Js.t = "ws:WebSharper.JavaScript!globalThis.Range#ExtractContents|" "ws:WebSharper.JavaScript!globalThis.Range#ExtractContents|"
(* inline *)
external deleteContents : t -> unit = "ws:WebSharper.JavaScript!globalThis.Range#DeleteContents|" "ws:WebSharper.JavaScript!globalThis.Range#DeleteContents|"
(* inline *)
external compareBoundaryPoints : t -> int -> Js.t -> int = "ws:WebSharper.JavaScript!globalThis.Range#CompareBoundaryPoints|System.Int32|WebSharper.JavaScript.Dom.Node" "ws:WebSharper.JavaScript!globalThis.Range#CompareBoundaryPoints|System.Int32|WebSharper.JavaScript.Dom.Node"
(* inline *)
external selectNodeContents : t -> Js.t -> unit = "ws:WebSharper.JavaScript!globalThis.Range#SelectNodeContents|WebSharper.JavaScript.Dom.Node" "ws:WebSharper.JavaScript!globalThis.Range#SelectNodeContents|WebSharper.JavaScript.Dom.Node"
(* inline *)
external selectNode : t -> Js.t -> unit = "ws:WebSharper.JavaScript!globalThis.Range#SelectNode|WebSharper.JavaScript.Dom.Node" "ws:WebSharper.JavaScript!globalThis.Range#SelectNode|WebSharper.JavaScript.Dom.Node"
(* inline *)
external collapse : t -> unit = "ws:WebSharper.JavaScript!globalThis.Range#Collapse|" "ws:WebSharper.JavaScript!globalThis.Range#Collapse|"
(* inline *)
external collapse_2 : t -> bool -> unit = "ws:WebSharper.JavaScript!globalThis.Range#Collapse|System.Boolean" "ws:WebSharper.JavaScript!globalThis.Range#Collapse|System.Boolean"
(* inline *)
external setEndAfter : t -> Js.t -> unit = "ws:WebSharper.JavaScript!globalThis.Range#SetEndAfter|WebSharper.JavaScript.Dom.Node" "ws:WebSharper.JavaScript!globalThis.Range#SetEndAfter|WebSharper.JavaScript.Dom.Node"
(* inline *)
external setEndBefore : t -> Js.t -> unit = "ws:WebSharper.JavaScript!globalThis.Range#SetEndBefore|WebSharper.JavaScript.Dom.Node" "ws:WebSharper.JavaScript!globalThis.Range#SetEndBefore|WebSharper.JavaScript.Dom.Node"
(* inline *)
external setStartAfter : t -> Js.t -> unit = "ws:WebSharper.JavaScript!globalThis.Range#SetStartAfter|WebSharper.JavaScript.Dom.Node" "ws:WebSharper.JavaScript!globalThis.Range#SetStartAfter|WebSharper.JavaScript.Dom.Node"
(* inline *)
external setStartBefore : t -> Js.t -> unit = "ws:WebSharper.JavaScript!globalThis.Range#SetStartBefore|WebSharper.JavaScript.Dom.Node" "ws:WebSharper.JavaScript!globalThis.Range#SetStartBefore|WebSharper.JavaScript.Dom.Node"
(* inline *)
external setEnd : t -> Js.t -> int -> unit = "ws:WebSharper.JavaScript!globalThis.Range#SetEnd|WebSharper.JavaScript.Dom.Node|System.Int32" "ws:WebSharper.JavaScript!globalThis.Range#SetEnd|WebSharper.JavaScript.Dom.Node|System.Int32"
(* inline *)
external setStart : t -> Js.t -> int -> unit = "ws:WebSharper.JavaScript!globalThis.Range#SetStart|WebSharper.JavaScript.Dom.Node|System.Int32" "ws:WebSharper.JavaScript!globalThis.Range#SetStart|WebSharper.JavaScript.Dom.Node|System.Int32"
(* inline *)
external get_CommonAncestorContainer : t -> Js.t = "ws:WebSharper.JavaScript!globalThis.Range#get_CommonAncestorContainer|" "ws:WebSharper.JavaScript!globalThis.Range#get_CommonAncestorContainer|"
(* inline *)
external get_Collapsed : t -> bool = "ws:WebSharper.JavaScript!globalThis.Range#get_Collapsed|" "ws:WebSharper.JavaScript!globalThis.Range#get_Collapsed|"
(* inline *)
external get_EndOffset : t -> int = "ws:WebSharper.JavaScript!globalThis.Range#get_EndOffset|" "ws:WebSharper.JavaScript!globalThis.Range#get_EndOffset|"
(* inline *)
external get_EndContainer : t -> Js.t = "ws:WebSharper.JavaScript!globalThis.Range#get_EndContainer|" "ws:WebSharper.JavaScript!globalThis.Range#get_EndContainer|"
(* inline *)
external get_StartOffset : t -> int = "ws:WebSharper.JavaScript!globalThis.Range#get_StartOffset|" "ws:WebSharper.JavaScript!globalThis.Range#get_StartOffset|"
(* inline *)
external get_StartContainer : t -> Js.t = "ws:WebSharper.JavaScript!globalThis.Range#get_StartContainer|" "ws:WebSharper.JavaScript!globalThis.Range#get_StartContainer|"
(* inline *)
external get_END_TO_START : unit -> int = "ws:WebSharper.JavaScript!globalThis.Range#get_END_TO_START|" "ws:WebSharper.JavaScript!globalThis.Range#get_END_TO_START|"
(* inline *)
external get_END_TO_END : unit -> int = "ws:WebSharper.JavaScript!globalThis.Range#get_END_TO_END|" "ws:WebSharper.JavaScript!globalThis.Range#get_END_TO_END|"
(* inline *)
external get_START_TO_END : unit -> int = "ws:WebSharper.JavaScript!globalThis.Range#get_START_TO_END|" "ws:WebSharper.JavaScript!globalThis.Range#get_START_TO_END|"
(* inline *)
external get_START_TO_START : unit -> int = "ws:WebSharper.JavaScript!globalThis.Range#get_START_TO_START|" "ws:WebSharper.JavaScript!globalThis.Range#get_START_TO_START|"
(* inline *)
external create : unit -> t = "wsnew:WebSharper.JavaScript!globalThis.Range" "wsnew:WebSharper.JavaScript!globalThis.Range"
