(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external get_Writable : t -> WritableStream.t = "ws:WebSharper.JavaScript!globalThis.ReadableWritablePair#get_Writable|" "ws:WebSharper.JavaScript!globalThis.ReadableWritablePair#get_Writable|"
(* inline *)
external get_Readable : t -> Js.t = "ws:WebSharper.JavaScript!globalThis.ReadableWritablePair#get_Readable|" "ws:WebSharper.JavaScript!globalThis.ReadableWritablePair#get_Readable|"
(* inline *)
external create : Js.t -> WritableStream.t -> t = "wsnew:WebSharper.JavaScript!globalThis.ReadableWritablePair" "wsnew:WebSharper.JavaScript!globalThis.ReadableWritablePair"
