(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external byob : unit -> t = "ws:WebSharper.JavaScript!globalThis.ReadableStreamReaderMode#get_Byob|" "ws:WebSharper.JavaScript!globalThis.ReadableStreamReaderMode#get_Byob|"
