(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external closed : unit -> t = "ws:WebSharper.JavaScript!globalThis.ReadyState#get_Closed|" "ws:WebSharper.JavaScript!globalThis.ReadyState#get_Closed|"
(* inline *)
external open_ : unit -> t = "ws:WebSharper.JavaScript!globalThis.ReadyState#get_Open|" "ws:WebSharper.JavaScript!globalThis.ReadyState#get_Open|"
(* inline *)
external connecting : unit -> t = "ws:WebSharper.JavaScript!globalThis.ReadyState#get_Connecting|" "ws:WebSharper.JavaScript!globalThis.ReadyState#get_Connecting|"
