(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external pipeTo : t -> WritableStream.t -> (unit) Promise.t = "ws:WebSharper.JavaScript!globalThis.ReadableStream#PipeTo|WebSharper.JavaScript.WritableStream" "ws:WebSharper.JavaScript!globalThis.ReadableStream#PipeTo|WebSharper.JavaScript.WritableStream"
(* inline *)
external pipeTo_2 : t -> WritableStream.t -> StreamPipeOptions.t -> (unit) Promise.t = "ws:WebSharper.JavaScript!globalThis.ReadableStream#PipeTo|WebSharper.JavaScript.WritableStream|WebSharper.JavaScript.StreamPipeOptions" "ws:WebSharper.JavaScript!globalThis.ReadableStream#PipeTo|WebSharper.JavaScript.WritableStream|WebSharper.JavaScript.StreamPipeOptions"
(* inline *)
external pipeThrough : t -> Js.t -> t = "ws:WebSharper.JavaScript!globalThis.ReadableStream#PipeThrough|WebSharper.JavaScript.ReadableWritablePair" "ws:WebSharper.JavaScript!globalThis.ReadableStream#PipeThrough|WebSharper.JavaScript.ReadableWritablePair"
(* inline *)
external pipeThrough_2 : t -> Js.t -> StreamPipeOptions.t -> t = "ws:WebSharper.JavaScript!globalThis.ReadableStream#PipeThrough|WebSharper.JavaScript.ReadableWritablePair|WebSharper.JavaScript.StreamPipeOptions" "ws:WebSharper.JavaScript!globalThis.ReadableStream#PipeThrough|WebSharper.JavaScript.ReadableWritablePair|WebSharper.JavaScript.StreamPipeOptions"
(* inline *)
external getReader : t -> Js.t = "ws:WebSharper.JavaScript!globalThis.ReadableStream#GetReader|" "ws:WebSharper.JavaScript!globalThis.ReadableStream#GetReader|"
(* inline *)
external getReader_2 : t -> ReadableStreamGetReaderOptions.t -> Js.t = "ws:WebSharper.JavaScript!globalThis.ReadableStream#GetReader|WebSharper.JavaScript.ReadableStreamGetReaderOptions" "ws:WebSharper.JavaScript!globalThis.ReadableStream#GetReader|WebSharper.JavaScript.ReadableStreamGetReaderOptions"
(* inline *)
external cancel : t -> (unit) Promise.t = "ws:WebSharper.JavaScript!globalThis.ReadableStream#Cancel|" "ws:WebSharper.JavaScript!globalThis.ReadableStream#Cancel|"
(* inline *)
external cancel_2 : t -> Js.t -> (unit) Promise.t = "ws:WebSharper.JavaScript!globalThis.ReadableStream#Cancel|System.Object" "ws:WebSharper.JavaScript!globalThis.ReadableStream#Cancel|System.Object"
(* inline *)
external get_Locked : t -> bool = "ws:WebSharper.JavaScript!globalThis.ReadableStream#get_Locked|" "ws:WebSharper.JavaScript!globalThis.ReadableStream#get_Locked|"
(* inline *)
external create : unit -> t = "wsnew:WebSharper.JavaScript!globalThis.ReadableStream" "wsnew:WebSharper.JavaScript!globalThis.ReadableStream"
(* inline *)
external create_2 : Js.t -> t = "wsnew:WebSharper.JavaScript!globalThis.ReadableStream" "wsnew:WebSharper.JavaScript!globalThis.ReadableStream"
(* inline *)
external create_3 : Js.t -> QueuingStrategy.t -> t = "wsnew:WebSharper.JavaScript!globalThis.ReadableStream" "wsnew:WebSharper.JavaScript!globalThis.ReadableStream"
(* inline *)
external create_4 : Js.t -> CountQueuingStrategy.t -> t = "wsnew:WebSharper.JavaScript!globalThis.ReadableStream" "wsnew:WebSharper.JavaScript!globalThis.ReadableStream"
(* inline *)
external create_5 : Js.t -> ByteLengthQueuingStrategy.t -> t = "wsnew:WebSharper.JavaScript!globalThis.ReadableStream" "wsnew:WebSharper.JavaScript!globalThis.ReadableStream"
