(* Generated by binding-adaptor. Do not edit. *)
type t = ReadableStream.t
(* inline *)
external writable : t -> WritableStream.t = "ws:WebSharper.JavaScript!globalThis.ReadableWritablePair#get_Writable|" "ws:WebSharper.JavaScript!globalThis.ReadableWritablePair#get_Writable|"
(* inline *)
external readable : t -> ReadableStream.t = "ws:WebSharper.JavaScript!globalThis.ReadableWritablePair#get_Readable|" "ws:WebSharper.JavaScript!globalThis.ReadableWritablePair#get_Readable|"
(* inline *)
external create : ReadableStream.t -> WritableStream.t -> t = "wsnew:WebSharper.JavaScript!globalThis.ReadableWritablePair" "wsnew:WebSharper.JavaScript!globalThis.ReadableWritablePair"
