(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external releaseLock : t -> unit = "ws:WebSharper.JavaScript!globalThis.ReadableStreamBYOBReader#ReleaseLock|" "ws:WebSharper.JavaScript!globalThis.ReadableStreamBYOBReader#ReleaseLock|"
(* inline *)
external read : t -> ArrayBufferView.t -> ReadableStreamResult.t = "ws:WebSharper.JavaScript!globalThis.ReadableStreamBYOBReader#Read|WebSharper.JavaScript.ArrayBufferView" "ws:WebSharper.JavaScript!globalThis.ReadableStreamBYOBReader#Read|WebSharper.JavaScript.ArrayBufferView"
(* inline *)
external create : ReadableStream.t -> t = "wsnew:WebSharper.JavaScript!globalThis.ReadableStreamBYOBReader" "wsnew:WebSharper.JavaScript!globalThis.ReadableStreamBYOBReader"
