(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external behavior : t -> ScrollAnimateMode.t = "ws:WebSharper.JavaScript!globalThis.ScrollOptions#get_Behavior|" "ws:WebSharper.JavaScript!globalThis.ScrollOptions#get_Behavior|"
(* inline *)
external left : t -> int = "ws:WebSharper.JavaScript!globalThis.ScrollOptions#get_Left|" "ws:WebSharper.JavaScript!globalThis.ScrollOptions#get_Left|"
(* inline *)
external top : t -> int = "ws:WebSharper.JavaScript!globalThis.ScrollOptions#get_Top|" "ws:WebSharper.JavaScript!globalThis.ScrollOptions#get_Top|"
(* inline *)
external set_behavior : t -> ScrollAnimateMode.t -> unit = "ws:WebSharper.JavaScript!globalThis.ScrollOptions#set_Behavior|WebSharper.JavaScript.Dom.ScrollAnimateMode" "ws:WebSharper.JavaScript!globalThis.ScrollOptions#set_Behavior|WebSharper.JavaScript.Dom.ScrollAnimateMode"
(* inline *)
external create : int -> int -> t = "wsnew:WebSharper.JavaScript!globalThis.ScrollOptions" "wsnew:WebSharper.JavaScript!globalThis.ScrollOptions"
