(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external get_Preserve : unit -> t = "ws:WebSharper.JavaScript!globalThis.SelectionMode#get_Preserve|" "ws:WebSharper.JavaScript!globalThis.SelectionMode#get_Preserve|"
(* inline *)
external get_End : unit -> t = "ws:WebSharper.JavaScript!globalThis.SelectionMode#get_End|" "ws:WebSharper.JavaScript!globalThis.SelectionMode#get_End|"
(* inline *)
external get_Start : unit -> t = "ws:WebSharper.JavaScript!globalThis.SelectionMode#get_Start|" "ws:WebSharper.JavaScript!globalThis.SelectionMode#get_Start|"
(* inline *)
external get_Select : unit -> t = "ws:WebSharper.JavaScript!globalThis.SelectionMode#get_Select|" "ws:WebSharper.JavaScript!globalThis.SelectionMode#get_Select|"
