(* Generated by binding-adaptor. Do not edit. *)
type t = EventTarget.t
(* inline *)
external port : t -> EventTarget.t = "ws:WebSharper.JavaScript!globalThis.SharedWorker#get_Port|" "ws:WebSharper.JavaScript!globalThis.SharedWorker#get_Port|"
(* inline *)
external onError : t -> Js.t = "ws:WebSharper.JavaScript!globalThis.SharedWorker#get_OnError|" "ws:WebSharper.JavaScript!globalThis.SharedWorker#get_OnError|"
(* inline *)
external onerror : t -> Js.t = "ws:WebSharper.JavaScript!globalThis.SharedWorker#get_Onerror|" "ws:WebSharper.JavaScript!globalThis.SharedWorker#get_Onerror|"
(* inline *)
external set_onError : t -> Js.t -> unit = "ws:WebSharper.JavaScript!globalThis.SharedWorker#set_OnError|System.Action`1<WebSharper.JavaScript.ErrorEvent>" "ws:WebSharper.JavaScript!globalThis.SharedWorker#set_OnError|System.Action`1<WebSharper.JavaScript.ErrorEvent>"
(* inline *)
external set_onerror : t -> Js.t -> unit = "ws:WebSharper.JavaScript!globalThis.SharedWorker#set_Onerror|System.Action`1<WebSharper.JavaScript.ErrorEvent>" "ws:WebSharper.JavaScript!globalThis.SharedWorker#set_Onerror|System.Action`1<WebSharper.JavaScript.ErrorEvent>"
(* inline *)
external create : string -> t = "wsnew:WebSharper.JavaScript!globalThis.SharedWorker" "wsnew:WebSharper.JavaScript!globalThis.SharedWorker"
(* inline *)
external create_2 : string -> WorkerOptions.t -> t = "wsnew:WebSharper.JavaScript!globalThis.SharedWorker" "wsnew:WebSharper.JavaScript!globalThis.SharedWorker"
