(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external after : unit -> t = "ws:WebSharper.JavaScript!globalThis.TimelinePhase#get_After|" "ws:WebSharper.JavaScript!globalThis.TimelinePhase#get_After|"
(* inline *)
external active : unit -> t = "ws:WebSharper.JavaScript!globalThis.TimelinePhase#get_Active|" "ws:WebSharper.JavaScript!globalThis.TimelinePhase#get_Active|"
(* inline *)
external before : unit -> t = "ws:WebSharper.JavaScript!globalThis.TimelinePhase#get_Before|" "ws:WebSharper.JavaScript!globalThis.TimelinePhase#get_Before|"
(* inline *)
external inactive : unit -> t = "ws:WebSharper.JavaScript!globalThis.TimelinePhase#get_Inactive|" "ws:WebSharper.JavaScript!globalThis.TimelinePhase#get_Inactive|"
