(* Generated by binding-adaptor. Do not edit. *)
type t = TimedTrack.t
(* inline *)
external onExit : t -> unit = "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#OnExit|" "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#OnExit|"
(* inline *)
external onexit : t -> unit = "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#Onexit|" "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#Onexit|"
(* inline *)
external onEnter : t -> unit = "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#OnEnter|" "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#OnEnter|"
(* inline *)
external onenter : t -> unit = "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#Onenter|" "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#Onenter|"
(* inline *)
external getCueAsHTML : t -> Js.t = "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#GetCueAsHTML|" "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#GetCueAsHTML|"
(* inline *)
external getCueAsSource : t -> string = "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#GetCueAsSource|" "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#GetCueAsSource|"
(* inline *)
external get_Voice : t -> string = "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#get_Voice|" "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#get_Voice|"
(* inline *)
external get_Alignment : t -> string = "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#get_Alignment|" "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#get_Alignment|"
(* inline *)
external get_Size : t -> int = "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#get_Size|" "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#get_Size|"
(* inline *)
external get_TextPosition : t -> int = "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#get_TextPosition|" "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#get_TextPosition|"
(* inline *)
external get_LinePosition : t -> int = "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#get_LinePosition|" "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#get_LinePosition|"
(* inline *)
external get_SnapToLines : t -> bool = "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#get_SnapToLines|" "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#get_SnapToLines|"
(* inline *)
external get_Direction : t -> string = "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#get_Direction|" "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#get_Direction|"
(* inline *)
external get_PauseOnExit : t -> bool = "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#get_PauseOnExit|" "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#get_PauseOnExit|"
(* inline *)
external get_EndTime : t -> float = "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#get_EndTime|" "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#get_EndTime|"
(* inline *)
external get_StartTime : t -> float = "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#get_StartTime|" "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#get_StartTime|"
(* inline *)
external get_Track : t -> TimedTrack.t = "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#get_Track|" "ws:WebSharper.JavaScript!globalThis.TimedTrackCue#get_Track|"
