(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external get_Metadata : unit -> t = "ws:WebSharper.JavaScript!globalThis.TrackType#get_Metadata|" "ws:WebSharper.JavaScript!globalThis.TrackType#get_Metadata|"
(* inline *)
external get_Chapters : unit -> t = "ws:WebSharper.JavaScript!globalThis.TrackType#get_Chapters|" "ws:WebSharper.JavaScript!globalThis.TrackType#get_Chapters|"
(* inline *)
external get_Descriptions : unit -> t = "ws:WebSharper.JavaScript!globalThis.TrackType#get_Descriptions|" "ws:WebSharper.JavaScript!globalThis.TrackType#get_Descriptions|"
(* inline *)
external get_Captions : unit -> t = "ws:WebSharper.JavaScript!globalThis.TrackType#get_Captions|" "ws:WebSharper.JavaScript!globalThis.TrackType#get_Captions|"
(* inline *)
external get_Subtitles : unit -> t = "ws:WebSharper.JavaScript!globalThis.TrackType#get_Subtitles|" "ws:WebSharper.JavaScript!globalThis.TrackType#get_Subtitles|"
