(* Generated by binding-adaptor. Do not edit. *)
type t = EventTarget.t
(* inline *)
external nextNode : t -> EventTarget.t = "ws:WebSharper.JavaScript!globalThis.TreeWalker#NextNode|" "ws:WebSharper.JavaScript!globalThis.TreeWalker#NextNode|"
(* inline *)
external previousNode : t -> EventTarget.t = "ws:WebSharper.JavaScript!globalThis.TreeWalker#PreviousNode|" "ws:WebSharper.JavaScript!globalThis.TreeWalker#PreviousNode|"
(* inline *)
external nextSibling : t -> EventTarget.t = "ws:WebSharper.JavaScript!globalThis.TreeWalker#NextSibling|" "ws:WebSharper.JavaScript!globalThis.TreeWalker#NextSibling|"
(* inline *)
external previousSibling : t -> EventTarget.t = "ws:WebSharper.JavaScript!globalThis.TreeWalker#PreviousSibling|" "ws:WebSharper.JavaScript!globalThis.TreeWalker#PreviousSibling|"
(* inline *)
external lastChild : t -> EventTarget.t = "ws:WebSharper.JavaScript!globalThis.TreeWalker#LastChild|" "ws:WebSharper.JavaScript!globalThis.TreeWalker#LastChild|"
(* inline *)
external firstChild : t -> EventTarget.t = "ws:WebSharper.JavaScript!globalThis.TreeWalker#FirstChild|" "ws:WebSharper.JavaScript!globalThis.TreeWalker#FirstChild|"
(* inline *)
external parentNode : t -> EventTarget.t = "ws:WebSharper.JavaScript!globalThis.TreeWalker#ParentNode|" "ws:WebSharper.JavaScript!globalThis.TreeWalker#ParentNode|"
(* inline *)
external currentNode : t -> EventTarget.t = "ws:WebSharper.JavaScript!globalThis.TreeWalker#get_CurrentNode|" "ws:WebSharper.JavaScript!globalThis.TreeWalker#get_CurrentNode|"
(* inline *)
external filter : t -> EventTarget.t = "ws:WebSharper.JavaScript!globalThis.TreeWalker#get_Filter|" "ws:WebSharper.JavaScript!globalThis.TreeWalker#get_Filter|"
(* inline *)
external whatToShow : t -> int = "ws:WebSharper.JavaScript!globalThis.TreeWalker#get_WhatToShow|" "ws:WebSharper.JavaScript!globalThis.TreeWalker#get_WhatToShow|"
(* inline *)
external root : t -> EventTarget.t = "ws:WebSharper.JavaScript!globalThis.TreeWalker#get_Root|" "ws:WebSharper.JavaScript!globalThis.TreeWalker#get_Root|"
(* inline *)
external set_currentNode : t -> EventTarget.t -> unit = "ws:WebSharper.JavaScript!globalThis.TreeWalker#set_CurrentNode|WebSharper.JavaScript.Dom.Node" "ws:WebSharper.JavaScript!globalThis.TreeWalker#set_CurrentNode|WebSharper.JavaScript.Dom.Node"
