(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external userAgent : t -> string = "ws:WebSharper.JavaScript!globalThis.WorkerNavigator#get_UserAgent|" "ws:WebSharper.JavaScript!globalThis.WorkerNavigator#get_UserAgent|"
(* inline *)
external onLine : t -> bool = "ws:WebSharper.JavaScript!globalThis.WorkerNavigator#get_OnLine|" "ws:WebSharper.JavaScript!globalThis.WorkerNavigator#get_OnLine|"
(* inline *)
external languages : t -> (string) array = "ws:WebSharper.JavaScript!globalThis.WorkerNavigator#get_Languages|" "ws:WebSharper.JavaScript!globalThis.WorkerNavigator#get_Languages|"
(* inline *)
external language : t -> string = "ws:WebSharper.JavaScript!globalThis.WorkerNavigator#get_Language|" "ws:WebSharper.JavaScript!globalThis.WorkerNavigator#get_Language|"
(* inline *)
external hardwareConcurrency : t -> int = "ws:WebSharper.JavaScript!globalThis.WorkerNavigator#get_HardwareConcurrency|" "ws:WebSharper.JavaScript!globalThis.WorkerNavigator#get_HardwareConcurrency|"
