(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external name : t -> string = "ws:WebSharper.JavaScript!globalThis.WorkerOptions#get_Name|" "ws:WebSharper.JavaScript!globalThis.WorkerOptions#get_Name|"
(* inline *)
external credentials : t -> string = "ws:WebSharper.JavaScript!globalThis.WorkerOptions#get_Credentials|" "ws:WebSharper.JavaScript!globalThis.WorkerOptions#get_Credentials|"
(* inline *)
external type_ : t -> WorkerType.t = "ws:WebSharper.JavaScript!globalThis.WorkerOptions#get_Type|" "ws:WebSharper.JavaScript!globalThis.WorkerOptions#get_Type|"
(* inline *)
external set_name : t -> string -> unit = "ws:WebSharper.JavaScript!globalThis.WorkerOptions#set_Name|System.String" "ws:WebSharper.JavaScript!globalThis.WorkerOptions#set_Name|System.String"
(* inline *)
external set_credentials : t -> string -> unit = "ws:WebSharper.JavaScript!globalThis.WorkerOptions#set_Credentials|System.String" "ws:WebSharper.JavaScript!globalThis.WorkerOptions#set_Credentials|System.String"
(* inline *)
external set_type : t -> WorkerType.t -> unit = "ws:WebSharper.JavaScript!globalThis.WorkerOptions#set_Type|WebSharper.JavaScript.WorkerType" "ws:WebSharper.JavaScript!globalThis.WorkerOptions#set_Type|WebSharper.JavaScript.WorkerType"
(* inline *)
external create : unit -> t = "wsnew:WebSharper.JavaScript!globalThis.WorkerOptions" "wsnew:WebSharper.JavaScript!globalThis.WorkerOptions"
