(* Generated by binding-adaptor. Do not edit. *)
type t = EventTarget.t
(* inline *)
external get_OnLanguageChange : t -> Js.t = "ws:WebSharper.JavaScript!globalThis.WorkerGlobalScope#get_OnLanguageChange|" "ws:WebSharper.JavaScript!globalThis.WorkerGlobalScope#get_OnLanguageChange|"
(* inline *)
external get_Onlanguagechange : t -> Js.t = "ws:WebSharper.JavaScript!globalThis.WorkerGlobalScope#get_Onlanguagechange|" "ws:WebSharper.JavaScript!globalThis.WorkerGlobalScope#get_Onlanguagechange|"
(* inline *)
external get_OnOnline : t -> Js.t = "ws:WebSharper.JavaScript!globalThis.WorkerGlobalScope#get_OnOnline|" "ws:WebSharper.JavaScript!globalThis.WorkerGlobalScope#get_OnOnline|"
(* inline *)
external get_Ononline : t -> Js.t = "ws:WebSharper.JavaScript!globalThis.WorkerGlobalScope#get_Ononline|" "ws:WebSharper.JavaScript!globalThis.WorkerGlobalScope#get_Ononline|"
(* inline *)
external get_OnOffline : t -> Js.t = "ws:WebSharper.JavaScript!globalThis.WorkerGlobalScope#get_OnOffline|" "ws:WebSharper.JavaScript!globalThis.WorkerGlobalScope#get_OnOffline|"
(* inline *)
external get_Onoffline : t -> Js.t = "ws:WebSharper.JavaScript!globalThis.WorkerGlobalScope#get_Onoffline|" "ws:WebSharper.JavaScript!globalThis.WorkerGlobalScope#get_Onoffline|"
(* inline *)
external get_OnError : t -> Js.t = "ws:WebSharper.JavaScript!globalThis.WorkerGlobalScope#get_OnError|" "ws:WebSharper.JavaScript!globalThis.WorkerGlobalScope#get_OnError|"
(* inline *)
external get_Onerror : t -> Js.t = "ws:WebSharper.JavaScript!globalThis.WorkerGlobalScope#get_Onerror|" "ws:WebSharper.JavaScript!globalThis.WorkerGlobalScope#get_Onerror|"
(* inline *)
external get_Location : t -> WorkerLocation.t = "ws:WebSharper.JavaScript!globalThis.WorkerGlobalScope#get_Location|" "ws:WebSharper.JavaScript!globalThis.WorkerGlobalScope#get_Location|"
(* inline *)
external get_Self : t -> EventTarget.t = "ws:WebSharper.JavaScript!globalThis.WorkerGlobalScope#get_Self|" "ws:WebSharper.JavaScript!globalThis.WorkerGlobalScope#get_Self|"
(* inline *)
external get_Navigator : t -> WorkerNavigator.t = "ws:WebSharper.JavaScript!globalThis.WorkerGlobalScope#get_Navigator|" "ws:WebSharper.JavaScript!globalThis.WorkerGlobalScope#get_Navigator|"
(* inline *)
external importScripts : t -> (string) array -> unit = "ws:WebSharper.JavaScript!globalThis.WorkerGlobalScope#ImportScripts|System.String[]" "ws:WebSharper.JavaScript!globalThis.WorkerGlobalScope#ImportScripts|System.String[]"
