(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external data : string -> string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#data-|System.String|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#data-|System.String|System.String"
(* macro *)
external accept : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#accept|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#accept|System.String"
(* macro *)
external acceptCharset : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#acceptCharset|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#acceptCharset|System.String"
(* macro *)
external accesskey : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#accesskey|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#accesskey|System.String"
(* macro *)
external action : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#action|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#action|System.String"
(* macro *)
external align : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#align|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#align|System.String"
(* macro *)
external alink : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#alink|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#alink|System.String"
(* macro *)
external alt : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#alt|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#alt|System.String"
(* macro *)
external altcode : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#altcode|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#altcode|System.String"
(* macro *)
external archive : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#archive|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#archive|System.String"
(* macro *)
external async : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#async|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#async|System.String"
(* macro *)
external autocomplete : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#autocomplete|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#autocomplete|System.String"
(* macro *)
external autofocus : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#autofocus|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#autofocus|System.String"
(* macro *)
external autoplay : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#autoplay|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#autoplay|System.String"
(* macro *)
external autosave : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#autosave|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#autosave|System.String"
(* macro *)
external axis : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#axis|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#axis|System.String"
(* macro *)
external background : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#background|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#background|System.String"
(* macro *)
external bgcolor : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#bgcolor|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#bgcolor|System.String"
(* macro *)
external border : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#border|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#border|System.String"
(* macro *)
external bordercolor : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#bordercolor|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#bordercolor|System.String"
(* macro *)
external buffered : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#buffered|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#buffered|System.String"
(* macro *)
external cellpadding : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#cellpadding|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#cellpadding|System.String"
(* macro *)
external cellspacing : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#cellspacing|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#cellspacing|System.String"
(* macro *)
external challenge : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#challenge|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#challenge|System.String"
(* macro *)
external char : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#char|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#char|System.String"
(* macro *)
external charoff : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#charoff|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#charoff|System.String"
(* macro *)
external charset : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#charset|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#charset|System.String"
(* macro *)
external checked : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#checked|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#checked|System.String"
(* macro *)
external cite : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#cite|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#cite|System.String"
(* macro *)
external class_ : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#class|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#class|System.String"
(* macro *)
external classid : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#classid|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#classid|System.String"
(* macro *)
external clear : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#clear|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#clear|System.String"
(* macro *)
external code : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#code|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#code|System.String"
(* macro *)
external codebase : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#codebase|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#codebase|System.String"
(* macro *)
external codetype : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#codetype|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#codetype|System.String"
(* macro *)
external color : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#color|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#color|System.String"
(* macro *)
external cols : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#cols|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#cols|System.String"
(* macro *)
external colspan : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#colspan|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#colspan|System.String"
(* macro *)
external compact : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#compact|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#compact|System.String"
(* macro *)
external content : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#content|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#content|System.String"
(* macro *)
external contenteditable : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#contenteditable|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#contenteditable|System.String"
(* macro *)
external contextmenu : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#contextmenu|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#contextmenu|System.String"
(* macro *)
external controls : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#controls|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#controls|System.String"
(* macro *)
external coords : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#coords|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#coords|System.String"
(* macro *)
external data_2 : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#data|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#data|System.String"
(* macro *)
external datetime : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#datetime|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#datetime|System.String"
(* macro *)
external declare : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#declare|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#declare|System.String"
(* macro *)
external default : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#default|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#default|System.String"
(* macro *)
external defer : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#defer|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#defer|System.String"
(* macro *)
external dir : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#dir|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#dir|System.String"
(* macro *)
external disabled : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#disabled|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#disabled|System.String"
(* macro *)
external download : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#download|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#download|System.String"
(* macro *)
external draggable : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#draggable|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#draggable|System.String"
(* macro *)
external dropzone : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#dropzone|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#dropzone|System.String"
(* macro *)
external enctype : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#enctype|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#enctype|System.String"
(* macro *)
external face : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#face|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#face|System.String"
(* macro *)
external for_ : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#for|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#for|System.String"
(* macro *)
external form : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#form|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#form|System.String"
(* macro *)
external formaction : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#formaction|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#formaction|System.String"
(* macro *)
external formenctype : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#formenctype|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#formenctype|System.String"
(* macro *)
external formmethod : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#formmethod|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#formmethod|System.String"
(* macro *)
external formnovalidate : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#formnovalidate|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#formnovalidate|System.String"
(* macro *)
external formtarget : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#formtarget|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#formtarget|System.String"
(* macro *)
external frame : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#frame|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#frame|System.String"
(* macro *)
external frameborder : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#frameborder|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#frameborder|System.String"
(* macro *)
external headers : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#headers|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#headers|System.String"
(* macro *)
external height : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#height|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#height|System.String"
(* macro *)
external hidden : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#hidden|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#hidden|System.String"
(* macro *)
external high : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#high|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#high|System.String"
(* macro *)
external href : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#href|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#href|System.String"
(* macro *)
external hreflang : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#hreflang|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#hreflang|System.String"
(* macro *)
external hspace : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#hspace|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#hspace|System.String"
(* macro *)
external http : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#http|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#http|System.String"
(* macro *)
external icon : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#icon|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#icon|System.String"
(* macro *)
external id : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#id|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#id|System.String"
(* macro *)
external ismap : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#ismap|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#ismap|System.String"
(* macro *)
external itemprop : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#itemprop|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#itemprop|System.String"
(* macro *)
external keytype : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#keytype|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#keytype|System.String"
(* macro *)
external kind : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#kind|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#kind|System.String"
(* macro *)
external label : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#label|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#label|System.String"
(* macro *)
external lang : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#lang|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#lang|System.String"
(* macro *)
external language : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#language|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#language|System.String"
(* macro *)
external link : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#link|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#link|System.String"
(* macro *)
external list : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#list|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#list|System.String"
(* macro *)
external longdesc : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#longdesc|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#longdesc|System.String"
(* macro *)
external loop : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#loop|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#loop|System.String"
(* macro *)
external low : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#low|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#low|System.String"
(* macro *)
external manifest : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#manifest|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#manifest|System.String"
(* macro *)
external marginheight : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#marginheight|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#marginheight|System.String"
(* macro *)
external marginwidth : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#marginwidth|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#marginwidth|System.String"
(* macro *)
external max : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#max|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#max|System.String"
(* macro *)
external maxlength : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#maxlength|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#maxlength|System.String"
(* macro *)
external media : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#media|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#media|System.String"
(* macro *)
external method_ : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#method|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#method|System.String"
(* macro *)
external min : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#min|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#min|System.String"
(* macro *)
external multiple : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#multiple|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#multiple|System.String"
(* macro *)
external name : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#name|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#name|System.String"
(* macro *)
external nohref : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#nohref|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#nohref|System.String"
(* macro *)
external noresize : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#noresize|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#noresize|System.String"
(* macro *)
external noshade : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#noshade|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#noshade|System.String"
(* macro *)
external novalidate : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#novalidate|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#novalidate|System.String"
(* macro *)
external nowrap : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#nowrap|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#nowrap|System.String"
(* macro *)
external object_ : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#object|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#object|System.String"
(* macro *)
external open_ : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#open|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#open|System.String"
(* macro *)
external optimum : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#optimum|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#optimum|System.String"
(* macro *)
external pattern : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#pattern|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#pattern|System.String"
(* macro *)
external ping : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#ping|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#ping|System.String"
(* macro *)
external placeholder : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#placeholder|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#placeholder|System.String"
(* macro *)
external popover : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#popover|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#popover|System.String"
(* macro *)
external popovertarget : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#popovertarget|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#popovertarget|System.String"
(* macro *)
external popovertargetaction : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#popovertargetaction|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#popovertargetaction|System.String"
(* macro *)
external poster : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#poster|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#poster|System.String"
(* macro *)
external preload : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#preload|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#preload|System.String"
(* macro *)
external profile : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#profile|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#profile|System.String"
(* macro *)
external prompt : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#prompt|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#prompt|System.String"
(* macro *)
external pubdate : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#pubdate|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#pubdate|System.String"
(* macro *)
external radiogroup : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#radiogroup|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#radiogroup|System.String"
(* macro *)
external readonly : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#readonly|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#readonly|System.String"
(* macro *)
external rel : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#rel|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#rel|System.String"
(* macro *)
external required : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#required|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#required|System.String"
(* macro *)
external rev : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#rev|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#rev|System.String"
(* macro *)
external reversed : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#reversed|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#reversed|System.String"
(* macro *)
external rows : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#rows|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#rows|System.String"
(* macro *)
external rowspan : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#rowspan|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#rowspan|System.String"
(* macro *)
external rules : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#rules|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#rules|System.String"
(* macro *)
external sandbox : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#sandbox|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#sandbox|System.String"
(* macro *)
external scheme : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#scheme|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#scheme|System.String"
(* macro *)
external scope : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#scope|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#scope|System.String"
(* macro *)
external scoped : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#scoped|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#scoped|System.String"
(* macro *)
external scrolling : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#scrolling|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#scrolling|System.String"
(* macro *)
external seamless : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#seamless|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#seamless|System.String"
(* macro *)
external selected : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#selected|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#selected|System.String"
(* macro *)
external shape : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#shape|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#shape|System.String"
(* macro *)
external size : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#size|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#size|System.String"
(* macro *)
external sizes : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#sizes|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#sizes|System.String"
(* macro *)
external span : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#span|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#span|System.String"
(* macro *)
external spellcheck : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#spellcheck|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#spellcheck|System.String"
(* macro *)
external src : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#src|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#src|System.String"
(* macro *)
external srcdoc : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#srcdoc|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#srcdoc|System.String"
(* macro *)
external srclang : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#srclang|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#srclang|System.String"
(* macro *)
external standby : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#standby|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#standby|System.String"
(* macro *)
external start : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#start|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#start|System.String"
(* macro *)
external step : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#step|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#step|System.String"
(* macro *)
external style : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#style|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#style|System.String"
(* macro *)
external subject : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#subject|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#subject|System.String"
(* macro *)
external summary : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#summary|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#summary|System.String"
(* macro *)
external tabindex : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#tabindex|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#tabindex|System.String"
(* macro *)
external target : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#target|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#target|System.String"
(* macro *)
external text : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#text|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#text|System.String"
(* macro *)
external title : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#title|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#title|System.String"
(* macro *)
external type_ : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#type|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#type|System.String"
(* macro *)
external usemap : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#usemap|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#usemap|System.String"
(* macro *)
external valign : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#valign|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#valign|System.String"
(* macro *)
external value : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#value|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#value|System.String"
(* macro *)
external valuetype : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#valuetype|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#valuetype|System.String"
(* macro *)
external version : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#version|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#version|System.String"
(* macro *)
external vlink : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#vlink|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#vlink|System.String"
(* macro *)
external vspace : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#vspace|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#vspace|System.String"
(* macro *)
external width : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#width|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#width|System.String"
(* macro *)
external wrap : string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#wrap|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default#wrap|System.String"
(* new *)
external create : unit -> t = "wsnew:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default" "wsnew:WebSharper.UI!WebSharper.UI/WebSharper.UI.HtmlModule.attr::default"
