(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external static : WebSharper_JavaScript.Element.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#Static|WebSharper.JavaScript.Dom.Element" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#Static|WebSharper.JavaScript.Dom.Element"
(* inline *)
external embedView : ('a) View.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#EmbedView|WebSharper.UI.View`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#EmbedView|WebSharper.UI.View`1<'0>"
(* inline *)
external async : WebSharper_StdLib.FSharpAsync.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#Async|Microsoft.FSharp.Control.FSharpAsync`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#Async|Microsoft.FSharp.Control.FSharpAsync`1<'0>"
(* inline *)
external loadLocalTemplates : string -> unit = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#LoadLocalTemplates|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#LoadLocalTemplates|System.String"
(* inline *)
external runFullDocTemplate : (TemplateHole.t) list -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#RunFullDocTemplate|System.Collections.Generic.IEnumerable`1<WebSharper.UI.TemplateHole>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#RunFullDocTemplate|System.Collections.Generic.IEnumerable`1<WebSharper.UI.TemplateHole>"
(* inline *)
external registerGlobalTemplateHole : TemplateHole.t -> unit = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#RegisterGlobalTemplateHole|WebSharper.UI.TemplateHole" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#RegisterGlobalTemplateHole|WebSharper.UI.TemplateHole"
(* inline *)
external textView : (string) View.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#TextView|WebSharper.UI.View`1<System.String>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#TextView|WebSharper.UI.View`1<System.String>"
(* macro *)
external inputV : (Attr.t) list -> string -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#InputV|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#InputV|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|System.String"
(* macro *)
external passwordBoxV : (Attr.t) list -> string -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#PasswordBoxV|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#PasswordBoxV|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|System.String"
(* macro *)
external intInputV : (Attr.t) list -> (int) CheckedInput.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#IntInputV|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|WebSharper.UI.Client.CheckedInput`1<System.Int32>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#IntInputV|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|WebSharper.UI.Client.CheckedInput`1<System.Int32>"
(* macro *)
external intInputUncheckedV : (Attr.t) list -> int -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#IntInputUncheckedV|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|System.Int32" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#IntInputUncheckedV|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|System.Int32"
(* macro *)
external floatInputV : (Attr.t) list -> (float) CheckedInput.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#FloatInputV|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|WebSharper.UI.Client.CheckedInput`1<System.Double>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#FloatInputV|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|WebSharper.UI.Client.CheckedInput`1<System.Double>"
(* macro *)
external floatInputUncheckedV : (Attr.t) list -> float -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#FloatInputUncheckedV|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|System.Double" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#FloatInputUncheckedV|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|System.Double"
(* macro *)
external inputAreaV : (Attr.t) list -> string -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#InputAreaV|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#InputAreaV|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|System.String"
(* inline *)
external bindView : ('a -> 'b) -> ('a) View.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#BindView|fn|WebSharper.UI.View`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#BindView|fn|WebSharper.UI.View`1<'0>"
(* inline *)
external run : WebSharper_JavaScript.Element.t -> Doc.t -> unit = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#Run|WebSharper.JavaScript.Dom.Element|WebSharper.UI.Doc" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#Run|WebSharper.JavaScript.Dom.Element|WebSharper.UI.Doc"
(* inline *)
external runById : string -> Doc.t -> unit = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#RunById|System.String|WebSharper.UI.Doc" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#RunById|System.String|WebSharper.UI.Doc"
(* inline *)
external runBefore : WebSharper_JavaScript.Node.t -> Doc.t -> unit = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#RunBefore|WebSharper.JavaScript.Dom.Node|WebSharper.UI.Doc" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#RunBefore|WebSharper.JavaScript.Dom.Node|WebSharper.UI.Doc"
(* inline *)
external runBeforeById : string -> Doc.t -> unit = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#RunBeforeById|System.String|WebSharper.UI.Doc" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#RunBeforeById|System.String|WebSharper.UI.Doc"
(* inline *)
external runAfter : WebSharper_JavaScript.Node.t -> Doc.t -> unit = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#RunAfter|WebSharper.JavaScript.Dom.Node|WebSharper.UI.Doc" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#RunAfter|WebSharper.JavaScript.Dom.Node|WebSharper.UI.Doc"
(* inline *)
external runAfterById : string -> Doc.t -> unit = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#RunAfterById|System.String|WebSharper.UI.Doc" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#RunAfterById|System.String|WebSharper.UI.Doc"
(* inline *)
external runAppend : WebSharper_JavaScript.Element.t -> Doc.t -> unit = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#RunAppend|WebSharper.JavaScript.Dom.Element|WebSharper.UI.Doc" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#RunAppend|WebSharper.JavaScript.Dom.Element|WebSharper.UI.Doc"
(* inline *)
external runAppendById : string -> Doc.t -> unit = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#RunAppendById|System.String|WebSharper.UI.Doc" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#RunAppendById|System.String|WebSharper.UI.Doc"
(* inline *)
external runPrepend : WebSharper_JavaScript.Element.t -> Doc.t -> unit = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#RunPrepend|WebSharper.JavaScript.Dom.Element|WebSharper.UI.Doc" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#RunPrepend|WebSharper.JavaScript.Dom.Element|WebSharper.UI.Doc"
(* inline *)
external runPrependById : string -> Doc.t -> unit = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#RunPrependById|System.String|WebSharper.UI.Doc" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#RunPrependById|System.String|WebSharper.UI.Doc"
(* inline *)
external runReplace : WebSharper_JavaScript.Node.t -> Doc.t -> unit = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#RunReplace|WebSharper.JavaScript.Dom.Node|WebSharper.UI.Doc" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#RunReplace|WebSharper.JavaScript.Dom.Node|WebSharper.UI.Doc"
(* inline *)
external runReplaceById : string -> Doc.t -> unit = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#RunReplaceById|System.String|WebSharper.UI.Doc" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#RunReplaceById|System.String|WebSharper.UI.Doc"
(* inline *)
external bindSeqCached : ('a -> 'b) -> ('c) View.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#BindSeqCached|fn|WebSharper.UI.View`1<'2>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#BindSeqCached|fn|WebSharper.UI.View`1<'2>"
(* inline *)
external convert : ('a -> 'b) -> (('a) WebSharper_StdLib.IEnumerable2.t) View.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#Convert|fn|WebSharper.UI.View`1<System.Collections.Generic.IEnumerable`1<'0>>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#Convert|fn|WebSharper.UI.View`1<System.Collections.Generic.IEnumerable`1<'0>>"
(* inline *)
external bindSeqCachedView : (('a) View.t -> 'b) -> ('c) View.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#BindSeqCachedView|fn|WebSharper.UI.View`1<'2>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#BindSeqCachedView|fn|WebSharper.UI.View`1<'2>"
(* inline *)
external convertSeq : (('a) View.t -> 'b) -> (('a) WebSharper_StdLib.IEnumerable2.t) View.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#ConvertSeq|fn|WebSharper.UI.View`1<System.Collections.Generic.IEnumerable`1<'0>>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#ConvertSeq|fn|WebSharper.UI.View`1<System.Collections.Generic.IEnumerable`1<'0>>"
(* inline *)
external bindListModel : ('a -> 'b) -> ('c, 'a) ListModel.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#BindListModel|fn|WebSharper.UI.ListModel`2<'2,'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#BindListModel|fn|WebSharper.UI.ListModel`2<'2,'0>"
(* inline *)
external bindListModelView : ('a -> (('b) View.t -> 'c)) -> ('a, 'b) ListModel.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#BindListModelView|fn|WebSharper.UI.ListModel`2<'0,'1>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#BindListModelView|fn|WebSharper.UI.ListModel`2<'0,'1>"
(* inline *)
external bindListModelLens : ('a -> (('b) Var.t -> 'c)) -> ('a, 'b) ListModel.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#BindListModelLens|fn|WebSharper.UI.ListModel`2<'0,'1>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#BindListModelLens|fn|WebSharper.UI.ListModel`2<'0,'1>"
(* inline *)
external input : (Attr.t) list -> (string) Var.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#Input|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|WebSharper.UI.Var`1<System.String>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#Input|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|WebSharper.UI.Var`1<System.String>"
(* inline *)
external passwordBox : (Attr.t) list -> (string) Var.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#PasswordBox|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|WebSharper.UI.Var`1<System.String>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#PasswordBox|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|WebSharper.UI.Var`1<System.String>"
(* inline *)
external intInput : (Attr.t) list -> ((int) CheckedInput.t) Var.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#IntInput|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|WebSharper.UI.Var`1<WebSharper.UI.Client.CheckedInput`1<System.Int32>>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#IntInput|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|WebSharper.UI.Var`1<WebSharper.UI.Client.CheckedInput`1<System.Int32>>"
(* inline *)
external intInputUnchecked : (Attr.t) list -> (int) Var.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#IntInputUnchecked|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|WebSharper.UI.Var`1<System.Int32>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#IntInputUnchecked|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|WebSharper.UI.Var`1<System.Int32>"
(* inline *)
external floatInput : (Attr.t) list -> ((float) CheckedInput.t) Var.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#FloatInput|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|WebSharper.UI.Var`1<WebSharper.UI.Client.CheckedInput`1<System.Double>>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#FloatInput|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|WebSharper.UI.Var`1<WebSharper.UI.Client.CheckedInput`1<System.Double>>"
(* inline *)
external floatInputUnchecked : (Attr.t) list -> (float) Var.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#FloatInputUnchecked|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|WebSharper.UI.Var`1<System.Double>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#FloatInputUnchecked|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|WebSharper.UI.Var`1<System.Double>"
(* inline *)
external inputArea : (Attr.t) list -> (string) Var.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#InputArea|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|WebSharper.UI.Var`1<System.String>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#InputArea|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|WebSharper.UI.Var`1<System.String>"
(* inline *)
external checkBox : (Attr.t) list -> (bool) Var.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#CheckBox|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|WebSharper.UI.Var`1<System.Boolean>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#CheckBox|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|WebSharper.UI.Var`1<System.Boolean>"
(* inline *)
external loadTemplate : string -> (string) WebSharper_StdLib.FSharpOption.t -> (unit -> WebSharper_JavaScript.Element.t) -> unit = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#LoadTemplate|System.String|Microsoft.FSharp.Core.FSharpOption`1<System.String>|fn" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#LoadTemplate|System.String|Microsoft.FSharp.Core.FSharpOption`1<System.String>|fn"
(* inline *)
external namedTemplate : string -> (string) WebSharper_StdLib.FSharpOption.t -> (TemplateHole.t) list -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#NamedTemplate|System.String|Microsoft.FSharp.Core.FSharpOption`1<System.String>|System.Collections.Generic.IEnumerable`1<WebSharper.UI.TemplateHole>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#NamedTemplate|System.String|Microsoft.FSharp.Core.FSharpOption`1<System.String>|System.Collections.Generic.IEnumerable`1<WebSharper.UI.TemplateHole>"
(* inline *)
external bindSeqCachedBy : ('a -> 'b) -> ('a -> 'c) -> ('d) View.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#BindSeqCachedBy|fn|fn|WebSharper.UI.View`1<'3>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#BindSeqCachedBy|fn|fn|WebSharper.UI.View`1<'3>"
(* inline *)
external convertBy : ('a -> 'b) -> ('a -> 'c) -> (('a) WebSharper_StdLib.IEnumerable2.t) View.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#ConvertBy|fn|fn|WebSharper.UI.View`1<System.Collections.Generic.IEnumerable`1<'0>>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#ConvertBy|fn|fn|WebSharper.UI.View`1<System.Collections.Generic.IEnumerable`1<'0>>"
(* inline *)
external bindSeqCachedViewBy : ('a -> 'b) -> ('b -> (('a) View.t -> 'c)) -> ('d) View.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#BindSeqCachedViewBy|fn|fn|WebSharper.UI.View`1<'3>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#BindSeqCachedViewBy|fn|fn|WebSharper.UI.View`1<'3>"
(* inline *)
external bindLens : ('a -> 'b) -> (('a) Var.t -> 'c) -> (('a) WebSharper_StdLib.FSharpList.t) Var.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#BindLens|fn|fn|WebSharper.UI.Var`1<Microsoft.FSharp.Collections.FSharpList`1<'0>>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#BindLens|fn|fn|WebSharper.UI.Var`1<Microsoft.FSharp.Collections.FSharpList`1<'0>>"
(* inline *)
external convertSeqBy : ('a -> 'b) -> ('b -> (('a) View.t -> 'c)) -> (('a) WebSharper_StdLib.IEnumerable2.t) View.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#ConvertSeqBy|fn|fn|WebSharper.UI.View`1<System.Collections.Generic.IEnumerable`1<'0>>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#ConvertSeqBy|fn|fn|WebSharper.UI.View`1<System.Collections.Generic.IEnumerable`1<'0>>"
(* inline *)
external checkBoxGroup : (Attr.t) list -> 'a -> (('a) WebSharper_StdLib.FSharpList.t) Var.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#CheckBoxGroup|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|'0|WebSharper.UI.Var`1<Microsoft.FSharp.Collections.FSharpList`1<'0>>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#CheckBoxGroup|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|'0|WebSharper.UI.Var`1<Microsoft.FSharp.Collections.FSharpList`1<'0>>"
(* inline *)
external button : string -> (Attr.t) list -> (unit -> unit) -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#Button|System.String|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|fn" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#Button|System.String|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|fn"
(* inline *)
external link : string -> (Attr.t) list -> (unit -> unit) -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#Link|System.String|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|fn" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#Link|System.String|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|fn"
(* inline *)
external radio : (Attr.t) list -> 'a -> ('a) Var.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#Radio|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|'0|WebSharper.UI.Var`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#Radio|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|'0|WebSharper.UI.Var`1<'0>"
(* inline *)
external getOrLoadTemplate : string -> (string) WebSharper_StdLib.FSharpOption.t -> (unit -> WebSharper_JavaScript.Element.t) -> (TemplateHole.t) list -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#GetOrLoadTemplate|System.String|Microsoft.FSharp.Core.FSharpOption`1<System.String>|fn|System.Collections.Generic.IEnumerable`1<WebSharper.UI.TemplateHole>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#GetOrLoadTemplate|System.String|Microsoft.FSharp.Core.FSharpOption`1<System.String>|fn|System.Collections.Generic.IEnumerable`1<WebSharper.UI.TemplateHole>"
(* inline *)
external select : (Attr.t) list -> ('a -> string) -> ('a) WebSharper_StdLib.FSharpList.t -> ('a) Var.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#Select|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|fn|Microsoft.FSharp.Collections.FSharpList`1<'0>|WebSharper.UI.Var`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#Select|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|fn|Microsoft.FSharp.Collections.FSharpList`1<'0>|WebSharper.UI.Var`1<'0>"
(* inline *)
external selectDyn : (Attr.t) list -> ('a -> string) -> (('a) WebSharper_StdLib.FSharpList.t) View.t -> ('a) Var.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#SelectDyn|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|fn|WebSharper.UI.View`1<Microsoft.FSharp.Collections.FSharpList`1<'0>>|WebSharper.UI.Var`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#SelectDyn|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|fn|WebSharper.UI.View`1<Microsoft.FSharp.Collections.FSharpList`1<'0>>|WebSharper.UI.Var`1<'0>"
(* inline *)
external buttonView : string -> (Attr.t) list -> ('a) View.t -> ('a -> unit) -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#ButtonView|System.String|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|WebSharper.UI.View`1<'0>|fn" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#ButtonView|System.String|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|WebSharper.UI.View`1<'0>|fn"
(* inline *)
external linkView : string -> (Attr.t) list -> ('a) View.t -> ('a -> unit) -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#LinkView|System.String|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|WebSharper.UI.View`1<'0>|fn" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#LinkView|System.String|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|WebSharper.UI.View`1<'0>|fn"
(* inline *)
external selectOptional : (Attr.t) list -> string -> ('a -> string) -> ('a) WebSharper_StdLib.FSharpList.t -> (('a) WebSharper_StdLib.FSharpOption.t) Var.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#SelectOptional|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|System.String|fn|Microsoft.FSharp.Collections.FSharpList`1<'0>|WebSharper.UI.Var`1<Microsoft.FSharp.Core.FSharpOption`1<'0>>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#SelectOptional|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|System.String|fn|Microsoft.FSharp.Collections.FSharpList`1<'0>|WebSharper.UI.Var`1<Microsoft.FSharp.Core.FSharpOption`1<'0>>"
(* inline *)
external selectDynOptional : (Attr.t) list -> string -> ('a -> string) -> (('a) WebSharper_StdLib.FSharpList.t) View.t -> (('a) WebSharper_StdLib.FSharpOption.t) Var.t -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#SelectDynOptional|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|System.String|fn|WebSharper.UI.View`1<Microsoft.FSharp.Collections.FSharpList`1<'0>>|WebSharper.UI.Var`1<Microsoft.FSharp.Core.FSharpOption`1<'0>>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.Doc::#SelectDynOptional|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|System.String|fn|WebSharper.UI.View`1<Microsoft.FSharp.Collections.FSharpList`1<'0>>|WebSharper.UI.Var`1<Microsoft.FSharp.Core.FSharpOption`1<'0>>"
