(* Generated by binding-adaptor. Do not edit. *)
type t
(* static *)
external get_CubicInOut : unit -> t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Easing::default#get_CubicInOut|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Easing::default#get_CubicInOut|"
(* static *)
external custom : Js.t -> t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Easing::default#Custom|fn" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Easing::default#Custom|fn"
(* instance *)
external transformTime : t -> float -> float = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Easing::default#TransformTime|System.Double" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Easing::default#TransformTime|System.Double"
(* instance *)
external get_transformTime : t -> Js.t = "wsget:WebSharper.UI!WebSharper.UI/WebSharper.UI.Easing::default#transformTime" "wsget:WebSharper.UI!WebSharper.UI/WebSharper.UI.Easing::default#transformTime"
(* new *)
external create : Js.t -> t = "wsnew:WebSharper.UI!WebSharper.UI/WebSharper.UI.Easing::default" "wsnew:WebSharper.UI!WebSharper.UI/WebSharper.UI.Easing::default"
