(* Generated by binding-adaptor. Do not edit. *)
type t = TemplateHole.t
(* instance *)
external removeAllUpdated : t -> unit = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.EltUpdater::default#RemoveAllUpdated|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.EltUpdater::default#RemoveAllUpdated|"
(* instance *)
external removeUpdated : t -> TemplateHole.t -> unit = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.EltUpdater::default#RemoveUpdated|WebSharper.UI.Elt" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.EltUpdater::default#RemoveUpdated|WebSharper.UI.Elt"
(* instance *)
external addUpdated : t -> TemplateHole.t -> unit = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.EltUpdater::default#AddUpdated|WebSharper.UI.Elt" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.EltUpdater::default#AddUpdated|WebSharper.UI.Elt"
(* instance *)
external clearHoles : t -> unit = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.EltUpdater::default#ClearHoles|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.EltUpdater::default#ClearHoles|"
(* instance *)
external addHole : t -> DocElemNode.t -> unit = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.EltUpdater::default#AddHole|WebSharper.UI.Client.DocElemNode" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.EltUpdater::default#AddHole|WebSharper.UI.Client.DocElemNode"
(* instance *)
external get_origHoles : t -> (DocElemNode.t) array = "wsget:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.EltUpdater::default#origHoles" "wsget:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.EltUpdater::default#origHoles"
(* instance *)
external get_holeUpdates : t -> ((int * (unit) View.t) array) Var.t = "wsget:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.EltUpdater::default#holeUpdates" "wsget:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.EltUpdater::default#holeUpdates"
(* instance *)
external get_treeNode : t -> Js.t = "wsget:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.EltUpdater::default#treeNode" "wsget:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.EltUpdater::default#treeNode"
(* new *)
external create : Js.t -> (unit) View.t -> Websharper_javascript.Element.t -> Updates.t -> ((int * (unit) View.t) array) Var.t -> t = "wsnew:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.EltUpdater::default" "wsnew:WebSharper.UI!WebSharper.UI/WebSharper.UI.Client.EltUpdater::default"
