(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external asyncBuilderBind : WebSharper_StdLib.FSharpAsyncBuilder.t -> ('a) Var.t -> ('a -> WebSharper_StdLib.FSharpAsync.t) -> WebSharper_StdLib.FSharpAsync.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Extensions::#AsyncBuilder.Bind|Microsoft.FSharp.Control.FSharpAsyncBuilder|WebSharper.UI.Var`1<'0>|fn" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Extensions::#AsyncBuilder.Bind|Microsoft.FSharp.Control.FSharpAsyncBuilder|WebSharper.UI.Var`1<'0>|fn"
(* inline *)
external asyncBuilderBind_2 : WebSharper_StdLib.FSharpAsyncBuilder.t -> ('a) View.t -> ('a -> WebSharper_StdLib.FSharpAsync.t) -> WebSharper_StdLib.FSharpAsync.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Extensions::#AsyncBuilder.Bind|Microsoft.FSharp.Control.FSharpAsyncBuilder|WebSharper.UI.View`1<'0>|fn" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Extensions::#AsyncBuilder.Bind|Microsoft.FSharp.Control.FSharpAsyncBuilder|WebSharper.UI.View`1<'0>|fn"
