(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external mousePosSt : unit -> Js.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input::#get_MousePosSt|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input::#get_MousePosSt|"
(* inline *)
external mouseBtnSt : unit -> Js.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input::#get_MouseBtnSt|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input::#get_MouseBtnSt|"
(* inline *)
external activateButtonListener : unit -> unit = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input::#get_ActivateButtonListener|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input::#get_ActivateButtonListener|"
(* inline *)
external keyListenerState : unit -> Js.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input::#get_KeyListenerState|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input::#get_KeyListenerState|"
(* inline *)
external activateKeyListener : unit -> unit = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input::#get_ActivateKeyListener|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input::#get_ActivateKeyListener|"
(* func *)
external activateKeyListener_2 : unit -> unit = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input::#ActivateKeyListener|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input::#ActivateKeyListener|"
(* func *)
external keyListenerState_2 : unit -> Js.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input::#KeyListenerState|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input::#KeyListenerState|"
(* func *)
external activateButtonListener_2 : unit -> unit = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input::#ActivateButtonListener|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input::#ActivateButtonListener|"
(* func *)
external mouseBtnSt_2 : unit -> Js.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input::#MouseBtnSt|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input::#MouseBtnSt|"
(* func *)
external mousePosSt_2 : unit -> Js.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input::#MousePosSt|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input::#MousePosSt|"
