(* Generated by binding-adaptor. Do not edit. *)
type t
(* func *)
external mousePressed : unit -> (bool) View.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input.Mouse::#get_MousePressed|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input.Mouse::#get_MousePressed|"
(* func *)
external rightPressed : unit -> (bool) View.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input.Mouse::#get_RightPressed|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input.Mouse::#get_RightPressed|"
(* func *)
external middlePressed : unit -> (bool) View.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input.Mouse::#get_MiddlePressed|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input.Mouse::#get_MiddlePressed|"
(* func *)
external leftPressed : unit -> (bool) View.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input.Mouse::#get_LeftPressed|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input.Mouse::#get_LeftPressed|"
(* func *)
external position : unit -> (int * int) View.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input.Mouse::#get_Position|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Input.Mouse::#get_Position|"
