(* Generated by binding-adaptor. Do not edit. *)
type t
(* func *)
external install : t -> ('a) Var.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.RouteMap::#Install|WebSharper.UI.RouteMap`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.RouteMap::#Install|WebSharper.UI.RouteMap`1<'0>"
(* func *)
external create : ('a -> (string) WebSharper_StdLib.FSharpList.t) -> ((string) WebSharper_StdLib.FSharpList.t -> 'a) -> t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.RouteMap::#Create|fn|fn" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.RouteMap::#Create|fn|fn"
(* func *)
external createWithQuery : ('a -> (string) WebSharper_StdLib.FSharpList.t * (string, string) WebSharper_StdLib.FSharpMap.t) -> ((string) WebSharper_StdLib.FSharpList.t * (string, string) WebSharper_StdLib.FSharpMap.t -> 'a) -> t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.RouteMap::#CreateWithQuery|fn|fn" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.RouteMap::#CreateWithQuery|fn|fn"
