(* Generated by binding-adaptor. Do not edit. *)
type ('a) t
(* instance *)
external get_TFlags : ('a) t -> Js.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Trans`1::default#get_TFlags|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Trans`1::default#get_TFlags|"
(* instance *)
external get_TExit : ('a) t -> Js.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Trans`1::default#get_TExit|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Trans`1::default#get_TExit|"
(* instance *)
external get_TEnter : ('a) t -> Js.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Trans`1::default#get_TEnter|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Trans`1::default#get_TEnter|"
(* instance *)
external tChange : ('a) t -> 'a -> 'a -> Js.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Trans`1::default#TChange|'0|'0" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Trans`1::default#TChange|'0|'0"
(* instance *)
external copy : ('a) t -> Js.t -> Js.t -> Js.t -> Js.t -> ('a) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Trans`1::default#Copy|Microsoft.FSharp.Core.FSharpOption`1<fn>|Microsoft.FSharp.Core.FSharpOption`1<fn>|Microsoft.FSharp.Core.FSharpOption`1<fn>|Microsoft.FSharp.Core.FSharpOption`1<WebSharper.UI.TFlags>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.Trans`1::default#Copy|Microsoft.FSharp.Core.FSharpOption`1<fn>|Microsoft.FSharp.Core.FSharpOption`1<fn>|Microsoft.FSharp.Core.FSharpOption`1<fn>|Microsoft.FSharp.Core.FSharpOption`1<WebSharper.UI.TFlags>"
(* instance *)
external get_flags : ('a) t -> Js.t = "wsget:WebSharper.UI!WebSharper.UI/WebSharper.UI.Trans`1::default#flags" "wsget:WebSharper.UI!WebSharper.UI/WebSharper.UI.Trans`1::default#flags"
(* instance *)
external get_exit : ('a) t -> Js.t = "wsget:WebSharper.UI!WebSharper.UI/WebSharper.UI.Trans`1::default#exit" "wsget:WebSharper.UI!WebSharper.UI/WebSharper.UI.Trans`1::default#exit"
(* instance *)
external get_enter : ('a) t -> Js.t = "wsget:WebSharper.UI!WebSharper.UI/WebSharper.UI.Trans`1::default#enter" "wsget:WebSharper.UI!WebSharper.UI/WebSharper.UI.Trans`1::default#enter"
(* instance *)
external get_change : ('a) t -> Js.t = "wsget:WebSharper.UI!WebSharper.UI/WebSharper.UI.Trans`1::default#change" "wsget:WebSharper.UI!WebSharper.UI/WebSharper.UI.Trans`1::default#change"
(* new *)
external create : Js.t -> Js.t -> Js.t -> ('a) t = "wsnew:WebSharper.UI!WebSharper.UI/WebSharper.UI.Trans`1::default" "wsnew:WebSharper.UI!WebSharper.UI/WebSharper.UI.Trans`1::default"
(* new *)
external create_2 : Js.t -> ('a) t = "wsnew:WebSharper.UI!WebSharper.UI/WebSharper.UI.Trans`1::default" "wsnew:WebSharper.UI!WebSharper.UI/WebSharper.UI.Trans`1::default"
(* new *)
external create_3 : unit -> ('a) t = "wsnew:WebSharper.UI!WebSharper.UI/WebSharper.UI.Trans`1::default" "wsnew:WebSharper.UI!WebSharper.UI/WebSharper.UI.Trans`1::default"
(* new *)
external create_4 : Js.t -> Js.t -> Js.t -> Js.t -> ('a) t = "wsnew:WebSharper.UI!WebSharper.UI/WebSharper.UI.Trans`1::default" "wsnew:WebSharper.UI!WebSharper.UI/WebSharper.UI.Trans`1::default"
