(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external attrHandler : string -> (WebSharper_JavaScript.Element.t -> ('a -> unit)) -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TypeProviderHelpers::#AttrHandler|System.String|fn" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TypeProviderHelpers::#AttrHandler|System.String|fn"
(* inline *)
external attrCreate : string -> string -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TypeProviderHelpers::#AttrCreate|System.String|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TypeProviderHelpers::#AttrCreate|System.String|System.String"
(* inline *)
external viewMap : ('a -> 'b) -> ('a) View.t -> ('b) View.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TypeProviderHelpers::#ViewMap|fn|WebSharper.UI.View`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TypeProviderHelpers::#ViewMap|fn|WebSharper.UI.View`1<'0>"
(* inline *)
external attrDynamic : string -> (string) View.t -> Attr.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TypeProviderHelpers::#AttrDynamic|System.String|WebSharper.UI.View`1<System.String>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TypeProviderHelpers::#AttrDynamic|System.String|WebSharper.UI.View`1<System.String>"
(* inline *)
external viewAppendString : (string) View.t -> string -> (string) View.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TypeProviderHelpers::#ViewAppendString|WebSharper.UI.View`1<System.String>|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TypeProviderHelpers::#ViewAppendString|WebSharper.UI.View`1<System.String>|System.String"
(* inline *)
external viewPrependString : string -> (string) View.t -> (string) View.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TypeProviderHelpers::#ViewPrependString|System.String|WebSharper.UI.View`1<System.String>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TypeProviderHelpers::#ViewPrependString|System.String|WebSharper.UI.View`1<System.String>"
(* inline *)
external viewConcatString : (string) View.t -> (string) View.t -> (string) View.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TypeProviderHelpers::#ViewConcatString|WebSharper.UI.View`1<System.String>|WebSharper.UI.View`1<System.String>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TypeProviderHelpers::#ViewConcatString|WebSharper.UI.View`1<System.String>|WebSharper.UI.View`1<System.String>"
(* inline *)
external viewMap2 : ('a -> ('b -> 'c)) -> ('a) View.t -> ('b) View.t -> ('c) View.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TypeProviderHelpers::#ViewMap2|fn|WebSharper.UI.View`1<'0>|WebSharper.UI.View`1<'1>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TypeProviderHelpers::#ViewMap2|fn|WebSharper.UI.View`1<'0>|WebSharper.UI.View`1<'1>"
(* inline *)
external docElement : string -> (Attr.t) list -> (Doc.t) list -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TypeProviderHelpers::#DocElement|System.String|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Doc>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TypeProviderHelpers::#DocElement|System.String|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Doc>"
(* inline *)
external docSvgElement : string -> (Attr.t) list -> (Doc.t) list -> Doc.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TypeProviderHelpers::#DocSvgElement|System.String|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Doc>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TypeProviderHelpers::#DocSvgElement|System.String|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Attr>|System.Collections.Generic.IEnumerable`1<WebSharper.UI.Doc>"
(* inline *)
external viewPrependAppendString : string -> (string) View.t -> string -> (string) View.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TypeProviderHelpers::#ViewPrependAppendString|System.String|WebSharper.UI.View`1<System.String>|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TypeProviderHelpers::#ViewPrependAppendString|System.String|WebSharper.UI.View`1<System.String>|System.String"
(* inline *)
external viewPrependConcatString : string -> (string) View.t -> (string) View.t -> (string) View.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TypeProviderHelpers::#ViewPrependConcatString|System.String|WebSharper.UI.View`1<System.String>|WebSharper.UI.View`1<System.String>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TypeProviderHelpers::#ViewPrependConcatString|System.String|WebSharper.UI.View`1<System.String>|WebSharper.UI.View`1<System.String>"
(* inline *)
external stringConcat : (string) array -> string = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TypeProviderHelpers::#StringConcat|System.String[]" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TypeProviderHelpers::#StringConcat|System.String[]"
