(* Generated by binding-adaptor. Do not edit. *)
type t
(* func *)
external getAsync : ('a) Var.t -> WebSharper_StdLib.FSharpAsync.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.VarExteions::#GetAsync|WebSharper.UI.Var`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.VarExteions::#GetAsync|WebSharper.UI.Var`1<'0>"
