(* Generated by binding-adaptor. Do not edit. *)
type t = TemplateHole.t
(* instance *)
external get_Value : t -> ((int) CheckedInput.t) Var.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TemplateHoleModule.VarInt::default#get_Value|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TemplateHoleModule.VarInt::default#get_Value|"
(* instance *)
external forTextView : t -> Js.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TemplateHoleModule.VarInt::default#ForTextView|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TemplateHoleModule.VarInt::default#ForTextView|"
(* instance *)
external get_AsChoiceView : t -> Js.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TemplateHoleModule.VarInt::default#get_AsChoiceView|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TemplateHoleModule.VarInt::default#get_AsChoiceView|"
(* instance *)
external get_ValueObj : t -> Js.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TemplateHoleModule.VarInt::default#get_ValueObj|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TemplateHoleModule.VarInt::default#get_ValueObj|"
(* instance *)
external get_Name : t -> string = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TemplateHoleModule.VarInt::default#get_Name|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TemplateHoleModule.VarInt::default#get_Name|"
(* instance *)
external applyVarHole : t -> WebSharper_JavaScript.Element.t -> unit = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TemplateHoleModule.VarInt::default#ApplyVarHole|WebSharper.JavaScript.Dom.Element" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TemplateHoleModule.VarInt::default#ApplyVarHole|WebSharper.JavaScript.Dom.Element"
(* instance *)
external withName : t -> string -> TemplateHole.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TemplateHoleModule.VarInt::default#WithName|System.String" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TemplateHoleModule.VarInt::default#WithName|System.String"
(* instance *)
external addAttribute : t -> Js.t -> WebSharper_JavaScript.Element.t -> unit = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TemplateHoleModule.VarInt::default#AddAttribute|fn|WebSharper.JavaScript.Dom.Element" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.TemplateHoleModule.VarInt::default#AddAttribute|fn|WebSharper.JavaScript.Dom.Element"
(* instance *)
external get_fillWith : t -> ((int) CheckedInput.t) Var.t = "wsget:WebSharper.UI!WebSharper.UI/WebSharper.UI.TemplateHoleModule.VarInt::default#fillWith" "wsget:WebSharper.UI!WebSharper.UI/WebSharper.UI.TemplateHoleModule.VarInt::default#fillWith"
(* instance *)
external get_name : t -> string = "wsget:WebSharper.UI!WebSharper.UI/WebSharper.UI.TemplateHoleModule.VarInt::default#name" "wsget:WebSharper.UI!WebSharper.UI/WebSharper.UI.TemplateHoleModule.VarInt::default#name"
(* new *)
external create : string -> ((int) CheckedInput.t) Var.t -> t = "wsnew:WebSharper.UI!WebSharper.UI/WebSharper.UI.TemplateHoleModule.VarInt::default" "wsnew:WebSharper.UI!WebSharper.UI/WebSharper.UI.TemplateHoleModule.VarInt::default"
