(* Generated by binding-adaptor. Do not edit. *)
type ('a) t = ('a) VarViewViewBuilderTypes.View.t
(* func *)
external do_ : unit -> VarViewViewBuilderTypes.ViewBuilder.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#get_Do|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#get_Do|"
(* inline *)
external fromVar : ('a) VarViewViewBuilderTypes.Var.t -> ('a) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#FromVar|WebSharper.UI.Var`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#FromVar|WebSharper.UI.Var`1<'0>"
(* func *)
external constAsync : WebSharper_StdLib.FSharpAsync.t -> ('a) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#ConstAsync|Microsoft.FSharp.Control.FSharpAsync`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#ConstAsync|Microsoft.FSharp.Control.FSharpAsync`1<'0>"
(* func *)
external const : 'a -> ('a) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#Const|'0" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#Const|'0"
(* func *)
external sequence : (('a) t) list -> (('a) WebSharper_StdLib.IEnumerable2.t) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#Sequence|System.Collections.Generic.IEnumerable`1<WebSharper.UI.View`1<'0>>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#Sequence|System.Collections.Generic.IEnumerable`1<WebSharper.UI.View`1<'0>>"
(* func *)
external joinInner : (('a) t) t -> ('a) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#JoinInner|WebSharper.UI.View`1<WebSharper.UI.View`1<'0>>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#JoinInner|WebSharper.UI.View`1<WebSharper.UI.View`1<'0>>"
(* func *)
external join : (('a) t) t -> ('a) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#Join|WebSharper.UI.View`1<WebSharper.UI.View`1<'0>>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#Join|WebSharper.UI.View`1<WebSharper.UI.View`1<'0>>"
(* func *)
external getAsync : ('a) t -> WebSharper_StdLib.FSharpAsync.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#GetAsync|WebSharper.UI.View`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#GetAsync|WebSharper.UI.View`1<'0>"
(* func *)
external withInitOption : ('a) t -> (('a) WebSharper_StdLib.FSharpOption.t) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#WithInitOption|WebSharper.UI.View`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#WithInitOption|WebSharper.UI.View`1<'0>"
(* func *)
external tryGet : ('a) t -> ('a) WebSharper_StdLib.FSharpOption.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#TryGet|WebSharper.UI.View`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#TryGet|WebSharper.UI.View`1<'0>"
(* func *)
external createLazy : (unit -> Js.t) -> ('a) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#CreateLazy|fn" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#CreateLazy|fn"
(* inline *)
external convert : ('a -> 'b) -> (('a) WebSharper_StdLib.IEnumerable2.t) t -> (('b) WebSharper_StdLib.IEnumerable2.t) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#Convert|fn|WebSharper.UI.View`1<System.Collections.Generic.IEnumerable`1<'0>>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#Convert|fn|WebSharper.UI.View`1<System.Collections.Generic.IEnumerable`1<'0>>"
(* inline *)
external convertSeq : (('a) t -> 'b) -> (('a) WebSharper_StdLib.IEnumerable2.t) t -> (('b) WebSharper_StdLib.IEnumerable2.t) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#ConvertSeq|fn|WebSharper.UI.View`1<System.Collections.Generic.IEnumerable`1<'0>>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#ConvertSeq|fn|WebSharper.UI.View`1<System.Collections.Generic.IEnumerable`1<'0>>"
(* func *)
external apply : (('a -> 'b)) t -> ('a) t -> ('b) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#Apply|WebSharper.UI.View`1<fn>|WebSharper.UI.View`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#Apply|WebSharper.UI.View`1<fn>|WebSharper.UI.View`1<'0>"
(* func *)
external asyncAwait : ('a -> bool) -> ('a) t -> WebSharper_StdLib.FSharpAsync.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#AsyncAwait|fn|WebSharper.UI.View`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#AsyncAwait|fn|WebSharper.UI.View`1<'0>"
(* func *)
external removableSink : ('a -> unit) -> ('a) t -> (unit -> unit) = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#RemovableSink|fn|WebSharper.UI.View`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#RemovableSink|fn|WebSharper.UI.View`1<'0>"
(* func *)
external sink : ('a -> unit) -> ('a) t -> unit = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#Sink|fn|WebSharper.UI.View`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#Sink|fn|WebSharper.UI.View`1<'0>"
(* func *)
external tryFinally : (unit -> unit) -> ('a) t -> ('a) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#TryFinally|fn|WebSharper.UI.View`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#TryFinally|fn|WebSharper.UI.View`1<'0>"
(* func *)
external tryWith : (WebSharper_StdLib.Error.t -> ('a) t) -> ('a) t -> ('a) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#TryWith|fn|WebSharper.UI.View`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#TryWith|fn|WebSharper.UI.View`1<'0>"
(* func *)
external bindInner : ('a -> ('b) t) -> ('a) t -> ('b) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#BindInner|fn|WebSharper.UI.View`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#BindInner|fn|WebSharper.UI.View`1<'0>"
(* func *)
external bind : ('a -> ('b) t) -> ('a) t -> ('b) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#Bind|fn|WebSharper.UI.View`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#Bind|fn|WebSharper.UI.View`1<'0>"
(* func *)
external mapSeqCachedView : (('a) t -> 'b) -> ('c) t -> (('b) WebSharper_StdLib.IEnumerable2.t) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#MapSeqCachedView|fn|WebSharper.UI.View`1<'2>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#MapSeqCachedView|fn|WebSharper.UI.View`1<'2>"
(* func *)
external convertSeqNode : (('a) t -> 'b) -> 'a -> Js.t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#ConvertSeqNode|fn|'0" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#ConvertSeqNode|fn|'0"
(* func *)
external mapSeqCached : ('a -> 'b) -> ('c) t -> (('b) WebSharper_StdLib.IEnumerable2.t) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#MapSeqCached|fn|WebSharper.UI.View`1<'2>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#MapSeqCached|fn|WebSharper.UI.View`1<'2>"
(* func *)
external withInit : 'a -> ('a) t -> ('a) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#WithInit|'0|WebSharper.UI.View`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#WithInit|'0|WebSharper.UI.View`1<'0>"
(* func *)
external get : ('a -> unit) -> ('a) t -> unit = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#Get|fn|WebSharper.UI.View`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#Get|fn|WebSharper.UI.View`1<'0>"
(* func *)
external mapAsync : ('a -> WebSharper_StdLib.FSharpAsync.t) -> ('a) t -> ('b) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#MapAsync|fn|WebSharper.UI.View`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#MapAsync|fn|WebSharper.UI.View`1<'0>"
(* func *)
external map2Unit : (unit) t -> (unit) t -> (unit) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#Map2Unit|WebSharper.UI.View`1<void>|WebSharper.UI.View`1<void>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#Map2Unit|WebSharper.UI.View`1<void>|WebSharper.UI.View`1<void>"
(* func *)
external mapCached : ('a -> 'b) -> ('a) t -> ('b) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#MapCached|fn|WebSharper.UI.View`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#MapCached|fn|WebSharper.UI.View`1<'0>"
(* func *)
external map : ('a -> 'b) -> ('a) t -> ('b) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#Map|fn|WebSharper.UI.View`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#Map|fn|WebSharper.UI.View`1<'0>"
(* inline *)
external convertBy : ('a -> 'c) -> ('a -> 'b) -> (('a) WebSharper_StdLib.IEnumerable2.t) t -> (('b) WebSharper_StdLib.IEnumerable2.t) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#ConvertBy|fn|fn|WebSharper.UI.View`1<System.Collections.Generic.IEnumerable`1<'0>>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#ConvertBy|fn|fn|WebSharper.UI.View`1<System.Collections.Generic.IEnumerable`1<'0>>"
(* inline *)
external convertSeqBy : ('a -> 'c) -> ('c -> (('a) t -> 'b)) -> (('a) WebSharper_StdLib.IEnumerable2.t) t -> (('b) WebSharper_StdLib.IEnumerable2.t) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#ConvertSeqBy|fn|fn|WebSharper.UI.View`1<System.Collections.Generic.IEnumerable`1<'0>>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#ConvertSeqBy|fn|fn|WebSharper.UI.View`1<System.Collections.Generic.IEnumerable`1<'0>>"
(* func *)
external updateWhile : 'a -> (bool) t -> ('a) t -> ('a) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#UpdateWhile|'0|WebSharper.UI.View`1<System.Boolean>|WebSharper.UI.View`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#UpdateWhile|'0|WebSharper.UI.View`1<System.Boolean>|WebSharper.UI.View`1<'0>"
(* func *)
external mapSeqCachedViewBy : ('a -> 'c) -> ('c -> (('a) t -> 'b)) -> ('d) t -> (('b) WebSharper_StdLib.IEnumerable2.t) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#MapSeqCachedViewBy|fn|fn|WebSharper.UI.View`1<'3>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#MapSeqCachedViewBy|fn|fn|WebSharper.UI.View`1<'3>"
(* func *)
external mapSeqCachedBy : ('a -> 'c) -> ('a -> 'b) -> ('d) t -> (('b) WebSharper_StdLib.IEnumerable2.t) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#MapSeqCachedBy|fn|fn|WebSharper.UI.View`1<'3>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#MapSeqCachedBy|fn|fn|WebSharper.UI.View`1<'3>"
(* func *)
external snapshotOn : 'a -> ('b) t -> ('a) t -> ('a) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#SnapshotOn|'0|WebSharper.UI.View`1<'1>|WebSharper.UI.View`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#SnapshotOn|'0|WebSharper.UI.View`1<'1>|WebSharper.UI.View`1<'0>"
(* func *)
external mapAsync2 : ('a -> ('b -> WebSharper_StdLib.FSharpAsync.t)) -> ('a) t -> ('b) t -> ('c) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#MapAsync2|fn|WebSharper.UI.View`1<'0>|WebSharper.UI.View`1<'1>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#MapAsync2|fn|WebSharper.UI.View`1<'0>|WebSharper.UI.View`1<'1>"
(* func *)
external map2 : ('a -> ('b -> 'c)) -> ('a) t -> ('b) t -> ('c) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#Map2|fn|WebSharper.UI.View`1<'0>|WebSharper.UI.View`1<'1>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#Map2|fn|WebSharper.UI.View`1<'0>|WebSharper.UI.View`1<'1>"
(* func *)
external mapCachedBy : ('a -> ('a -> bool)) -> ('a -> 'b) -> ('a) t -> ('b) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#MapCachedBy|fn|fn|WebSharper.UI.View`1<'0>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#MapCachedBy|fn|fn|WebSharper.UI.View`1<'0>"
(* func *)
external map3 : ('a -> ('b -> ('c -> 'd))) -> ('a) t -> ('b) t -> ('c) t -> ('d) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#Map3|fn|WebSharper.UI.View`1<'0>|WebSharper.UI.View`1<'1>|WebSharper.UI.View`1<'2>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View::#Map3|fn|WebSharper.UI.View`1<'0>|WebSharper.UI.View`1<'1>|WebSharper.UI.View`1<'2>"
(* inline *)
external withInitOption_2 : ('a) t -> (('a) WebSharper_StdLib.FSharpOption.t) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View`1::default#WithInitOption|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View`1::default#WithInitOption|"
(* macro *)
external v : unit -> 'a = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View`1::default#get_V|" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View`1::default#get_V|"
(* inline *)
external map_2 : ('a) t -> ('a -> 'b) -> ('b) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View`1::default#Map|fn" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View`1::default#Map|fn"
(* inline *)
external mapAsync_2 : ('a) t -> ('a -> WebSharper_StdLib.FSharpAsync.t) -> ('b) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View`1::default#MapAsync|fn" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View`1::default#MapAsync|fn"
(* inline *)
external mapAsyncOption : ('a) t -> ('a -> WebSharper_StdLib.FSharpAsync.t) -> (('b) WebSharper_StdLib.FSharpOption.t) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View`1::default#MapAsyncOption|fn" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View`1::default#MapAsyncOption|fn"
(* inline *)
external bind_2 : ('a) t -> ('a -> ('b) t) -> ('b) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View`1::default#Bind|fn" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View`1::default#Bind|fn"
(* inline *)
external bindInner_2 : ('a) t -> ('a -> ('b) t) -> ('b) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View`1::default#BindInner|fn" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View`1::default#BindInner|fn"
(* inline *)
external withInit_2 : ('a) t -> 'a -> ('a) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View`1::default#WithInit|'0" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View`1::default#WithInit|'0"
(* static *)
external newView : (unit -> Js.t) -> ('a) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View`1::default#NewView|fn" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View`1::default#NewView|fn"
(* inline *)
external mapAsyncLoading : ('a) t -> 'b -> ('a -> WebSharper_StdLib.FSharpAsync.t) -> ('b) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View`1::default#MapAsyncLoading|'1|fn" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View`1::default#MapAsyncLoading|'1|fn"
(* inline *)
external snapshotOn_2 : ('a) t -> 'a -> ('b) t -> ('a) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View`1::default#SnapshotOn|'0|WebSharper.UI.View`1<'1>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View`1::default#SnapshotOn|'0|WebSharper.UI.View`1<'1>"
(* inline *)
external updateWhile_2 : ('a) t -> 'a -> (bool) t -> ('a) t = "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View`1::default#UpdateWhile|'0|WebSharper.UI.View`1<System.Boolean>" "ws:WebSharper.UI!WebSharper.UI/WebSharper.UI.View`1::default#UpdateWhile|'0|WebSharper.UI.View`1<System.Boolean>"
