(* Generated by binding-adaptor. Do not edit. *)
type t
(* instance *)
external get_Headers : t -> (string * string) array = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.Remoting.AjaxRemotingProvider::default#get_Headers|" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.Remoting.AjaxRemotingProvider::default#get_Headers|"
(* instance *)
external get_EndPoint : t -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.Remoting.AjaxRemotingProvider::default#get_EndPoint|" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.Remoting.AjaxRemotingProvider::default#get_EndPoint|"
(* instance *)
external asyncBase : t -> string -> (Js.t) array -> Js.t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.Remoting.AjaxRemotingProvider::default#AsyncBase|System.String|System.Object[]" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.Remoting.AjaxRemotingProvider::default#AsyncBase|System.String|System.Object[]"
(* new *)
external create : unit -> t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/WebSharper.Remoting.AjaxRemotingProvider::default" "wsnew:WebSharper.StdLib!WebSharper.StdLib/WebSharper.Remoting.AjaxRemotingProvider::default"
