(* Generated by binding-adaptor. Do not edit. *)
type ('a) t
(* instance *)
external getHashCode : ('a) t -> 'a -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.Comparers.BaseEqualityComparer`1::default#GetHashCode|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.Comparers.BaseEqualityComparer`1::default#GetHashCode|'0"
(* instance *)
external equals : ('a) t -> 'a -> 'a -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.Comparers.BaseEqualityComparer`1::default#Equals|'0|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.Comparers.BaseEqualityComparer`1::default#Equals|'0|'0"
(* new *)
external create : unit -> ('a) t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/WebSharper.Comparers.BaseEqualityComparer`1::default" "wsnew:WebSharper.StdLib!WebSharper.StdLib/WebSharper.Comparers.BaseEqualityComparer`1::default"
