(* Generated by binding-adaptor. Do not edit. *)
type t
(* func *)
external toBin : int -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.BigIntProxyHelpers::#ToBin|System.Byte" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.BigIntProxyHelpers::#ToBin|System.Byte"
(* func *)
external toBinaryStr : (int) array -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.BigIntProxyHelpers::#ToBinaryStr|System.Byte[]" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.BigIntProxyHelpers::#ToBinaryStr|System.Byte[]"
