(* Generated by binding-adaptor. Do not edit. *)
type ('a) t
(* instance *)
external get_secondary : ('a) t -> IComparer2.t = "wsget:WebSharper.StdLib!WebSharper.StdLib/WebSharper.CompoundComparer`1::default#secondary" "wsget:WebSharper.StdLib!WebSharper.StdLib/WebSharper.CompoundComparer`1::default#secondary"
(* instance *)
external get_primary : ('a) t -> IComparer2.t = "wsget:WebSharper.StdLib!WebSharper.StdLib/WebSharper.CompoundComparer`1::default#primary" "wsget:WebSharper.StdLib!WebSharper.StdLib/WebSharper.CompoundComparer`1::default#primary"
(* new *)
external create : IComparer2.t -> IComparer2.t -> ('a) t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/WebSharper.CompoundComparer`1::default" "wsnew:WebSharper.StdLib!WebSharper.StdLib/WebSharper.CompoundComparer`1::default"
