(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external throw : t -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Runtime.ExceptionServices.ExceptionDispatchInfo::#Throw|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Runtime.ExceptionServices.ExceptionDispatchInfo::#Throw|"
(* inline *)
external sourceException : t -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Runtime.ExceptionServices.ExceptionDispatchInfo::#get_SourceException|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Runtime.ExceptionServices.ExceptionDispatchInfo::#get_SourceException|"
(* inline *)
external capture : Object.t -> t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Runtime.ExceptionServices.ExceptionDispatchInfo::#Capture|System.Exception" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Runtime.ExceptionServices.ExceptionDispatchInfo::#Capture|System.Exception"
(* inline *)
external throw_2 : Object.t -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Runtime.ExceptionServices.ExceptionDispatchInfo::#Throw|System.Exception" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Runtime.ExceptionServices.ExceptionDispatchInfo::#Throw|System.Exception"
