(* Generated by binding-adaptor. Do not edit. *)
type ('a, 'b, 'c) t
(* func *)
external newChoice1Of3 : 'a -> ('a, 'b, 'c) t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpChoice`3::#NewChoice1Of3|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpChoice`3::#NewChoice1Of3|'0"
(* func *)
external newChoice2Of3 : 'b -> ('a, 'b, 'c) t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpChoice`3::#NewChoice2Of3|'1" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpChoice`3::#NewChoice2Of3|'1"
(* func *)
external newChoice3Of3 : 'c -> ('a, 'b, 'c) t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpChoice`3::#NewChoice3Of3|'2" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpChoice`3::#NewChoice3Of3|'2"
