(* Generated by binding-adaptor. Do not edit. *)
type ('a) t
(* inline *)
external value : ('a) t -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpRef`1::#get_Value|" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpRef`1::#get_Value|"
(* inline *)
external get_contents : ('a) t -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpRef`1::#get_contents|" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpRef`1::#get_contents|"
(* inline *)
external set_value : ('a) t -> 'a -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpRef`1::#set_Value|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpRef`1::#set_Value|'0"
(* inline *)
external set_contents : ('a) t -> 'a -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpRef`1::#set_contents|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpRef`1::#set_contents|'0"
(* indexed *)
external get_contents_2 : ('a) t -> 'a = "wsget:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpRef`1::#contents" "wsget:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpRef`1::#contents"
(* indexed *)
external set_contents_2 : ('a) t -> 'a -> unit = "wsset:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpRef`1::#contents" "wsset:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpRef`1::#contents"
(* func *)
external create : 'a -> ('a) t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpRef`1::" "wsnew:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpRef`1::"
