(* Generated by binding-adaptor. Do not edit. *)
type ('a, 'b, 'c, 'd) t
(* inline *)
external adapt : ('a -> ('b -> ('c -> 'd))) -> ('a, 'b, 'c, 'd) t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.OptimizedClosures.FSharpFunc`4::#Adapt|fn" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.OptimizedClosures.FSharpFunc`4::#Adapt|fn"
(* inline *)
external invoke : ('a, 'b, 'c, 'd) t -> 'a -> 'b -> 'c -> 'd = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.OptimizedClosures.FSharpFunc`4::#Invoke|'0|'1|'2" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.OptimizedClosures.FSharpFunc`4::#Invoke|'0|'1|'2"
