(* Generated by binding-adaptor. Do not edit. *)
type ('a) t
(* inline *)
external isSome : ('a) t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpValueOption`1::#get_IsSome|" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpValueOption`1::#get_IsSome|"
(* inline *)
external isNone : ('a) t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpValueOption`1::#get_IsNone|" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpValueOption`1::#get_IsNone|"
(* inline *)
external none : unit -> ('a) t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpValueOption`1::#get_None|" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpValueOption`1::#get_None|"
(* func *)
external _unique_ValueNone : unit -> (Js.t) t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpValueOption`1::#_unique_ValueNone|" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpValueOption`1::#_unique_ValueNone|"
(* func *)
external value : unit -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpValueOption`1::#get_Value|" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpValueOption`1::#get_Value|"
(* inline *)
external some : 'a -> ('a) t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpValueOption`1::#Some|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpValueOption`1::#Some|'0"
(* inline *)
external op_Implicit : 'a -> ('a) t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpValueOption`1::#op_Implicit|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpValueOption`1::#op_Implicit|'0"
(* func *)
external newValueSome : 'a -> ('a) t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpValueOption`1::#NewValueSome|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FSharpValueOption`1::#NewValueSome|'0"
