(* Generated by binding-adaptor. Do not edit. *)
type ('a) t
(* inline *)
external isEmpty : ('a) t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.FSharpList`1::default#get_IsEmpty|" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.FSharpList`1::default#get_IsEmpty|"
(* inline *)
external empty : unit -> ('a) t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.FSharpList`1::default#get_Empty|" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.FSharpList`1::default#get_Empty|"
(* inline *)
external head : ('a) t -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.FSharpList`1::default#get_Head|" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.FSharpList`1::default#get_Head|"
(* inline *)
external tail : ('a) t -> ('a) t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.FSharpList`1::default#get_Tail|" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.FSharpList`1::default#get_Tail|"
(* static *)
external _unique_Empty : unit -> (Js.t) t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.FSharpList`1::default#_unique_Empty|" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.FSharpList`1::default#_unique_Empty|"
(* instance *)
external length : ('a) t -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.FSharpList`1::default#get_Length|" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.FSharpList`1::default#get_Length|"
(* instance *)
external item : ('a) t -> int -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.FSharpList`1::default#get_Item|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.FSharpList`1::default#get_Item|System.Int32"
(* inline *)
external cons : 'a -> ('a) t -> ('a) t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.FSharpList`1::default#Cons|'0|Microsoft.FSharp.Collections.FSharpList`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.FSharpList`1::default#Cons|'0|Microsoft.FSharp.Collections.FSharpList`1<'0>"
(* static *)
external newCons : 'a -> ('a) t -> ('a) t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.FSharpList`1::default#NewCons|'0|Microsoft.FSharp.Collections.FSharpList`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.FSharpList`1::default#NewCons|'0|Microsoft.FSharp.Collections.FSharpList`1<'0>"
(* instance *)
external getSlice : ('a) t -> (int) FSharpOption.t -> (int) FSharpOption.t -> ('a) t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.FSharpList`1::default#GetSlice|Microsoft.FSharp.Core.FSharpOption`1<System.Int32>|Microsoft.FSharp.Core.FSharpOption`1<System.Int32>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.FSharpList`1::default#GetSlice|Microsoft.FSharp.Core.FSharpOption`1<System.Int32>|Microsoft.FSharp.Core.FSharpOption`1<System.Int32>"
