(* Generated by binding-adaptor. Do not edit. *)
type ('a, 'b, 'c) t
(* inline *)
external adapt : ('a -> ('b -> 'c)) -> ('a, 'b, 'c) t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.OptimizedClosures.FSharpFunc`3::#Adapt|fn" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.OptimizedClosures.FSharpFunc`3::#Adapt|fn"
(* inline *)
external invoke : ('a, 'b, 'c) t -> 'a -> 'b -> 'c = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.OptimizedClosures.FSharpFunc`3::#Invoke|'0|'1" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.OptimizedClosures.FSharpFunc`3::#Invoke|'0|'1"
