(* Generated by binding-adaptor. Do not edit. *)
type ('a, 'b, 'c, 'd, 'e, 'f) t
(* inline *)
external call : ('a, 'b, 'c, 'd, 'e, 'f) t -> 'a -> 'b -> 'c -> 'd -> ('e) array -> 'f = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.FuncWithRest`6::#Call|'0|'1|'2|'3|'4[]" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.FuncWithRest`6::#Call|'0|'1|'2|'3|'4[]"
(* inline *)
external create : ('a * 'b * 'c * 'd * ('e) array -> 'f) -> ('a, 'b, 'c, 'd, 'e, 'f) t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.FuncWithRest`6::" "wsnew:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.FuncWithRest`6::"
