(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external fromAction : Js.t -> (unit -> unit) = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FromAction|System.Action" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FromAction|System.Action"
(* inline *)
external fromAction_2 : Js.t -> ('a -> unit) = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FromAction|System.Action`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FromAction|System.Action`1<'0>"
(* inline *)
external fromAction_3 : Js.t -> ('a -> ('b -> unit)) = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FromAction|System.Action`2<'0,'1>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FromAction|System.Action`2<'0,'1>"
(* inline *)
external fromAction_4 : Js.t -> ('a -> ('b -> ('c -> unit))) = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FromAction|System.Action`3<'0,'1,'2>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FromAction|System.Action`3<'0,'1,'2>"
(* inline *)
external fromAction_5 : Js.t -> ('a -> ('b -> ('c -> ('d -> unit)))) = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FromAction|System.Action`4<'0,'1,'2,'3>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FromAction|System.Action`4<'0,'1,'2,'3>"
(* inline *)
external fromAction_6 : Js.t -> ('a -> ('b -> ('c -> ('d -> ('e -> unit))))) = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FromAction|System.Action`5<'0,'1,'2,'3,'4>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FromAction|System.Action`5<'0,'1,'2,'3,'4>"
(* inline *)
external fromFunc : Js.t -> (unit -> 'a) = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FromFunc|System.Func`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FromFunc|System.Func`1<'0>"
(* inline *)
external fromFunc_2 : Js.t -> ('a -> 'b) = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FromFunc|System.Func`2<'0,'1>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FromFunc|System.Func`2<'0,'1>"
(* inline *)
external fromFunc_3 : Js.t -> ('a -> ('b -> 'c)) = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FromFunc|System.Func`3<'0,'1,'2>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FromFunc|System.Func`3<'0,'1,'2>"
(* inline *)
external fromFunc_4 : Js.t -> ('a -> ('b -> ('c -> 'd))) = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FromFunc|System.Func`4<'0,'1,'2,'3>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FromFunc|System.Func`4<'0,'1,'2,'3>"
(* inline *)
external fromFunc_5 : Js.t -> ('a -> ('b -> ('c -> ('d -> 'e)))) = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FromFunc|System.Func`5<'0,'1,'2,'3,'4>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FromFunc|System.Func`5<'0,'1,'2,'3,'4>"
(* inline *)
external fromFunc_6 : Js.t -> ('a -> ('b -> ('c -> ('d -> ('e -> 'f))))) = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FromFunc|System.Func`6<'0,'1,'2,'3,'4,'5>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FromFunc|System.Func`6<'0,'1,'2,'3,'4,'5>"
(* inline *)
external funcFromTupled : ('a * 'b -> 'c) -> ('a -> ('b -> 'c)) = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FuncFromTupled|fn" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FuncFromTupled|fn"
(* inline *)
external funcFromTupled_2 : ('a * 'b * 'c -> 'd) -> ('a -> ('b -> ('c -> 'd))) = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FuncFromTupled|fn" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FuncFromTupled|fn"
(* inline *)
external funcFromTupled_3 : ('a * 'b * 'c * 'd -> 'e) -> ('a -> ('b -> ('c -> ('d -> 'e)))) = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FuncFromTupled|fn" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FuncFromTupled|fn"
(* inline *)
external funcFromTupled_4 : ('a * 'b * 'c * 'd * 'e -> 'f) -> ('a -> ('b -> ('c -> ('d -> ('e -> 'f))))) = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FuncFromTupled|fn" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#FuncFromTupled|fn"
(* inline *)
external toFSharpFunc : Js.t -> ('a -> unit) = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#ToFSharpFunc|System.Action`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#ToFSharpFunc|System.Action`1<'0>"
(* inline *)
external toFSharpFunc_2 : Js.t -> ('a -> 'b) = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#ToFSharpFunc|System.Converter`2<'0,'1>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.FuncConvert::#ToFSharpFunc|System.Converter`2<'0,'1>"
