(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external convertToBool : 'a -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.Helpers::#convertToBool|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.Helpers::#convertToBool|'0"
