(* Generated by binding-adaptor. Do not edit. *)
type t = Object.t
(* func *)
external isIAjaxProvider : Js.t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.Remoting.IAjaxProvider::#isIAjaxProvider|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.Remoting.IAjaxProvider::#isIAjaxProvider|System.Object"
