(* Generated by binding-adaptor. Do not edit. *)
type ('a) t
(* func *)
external isIAsyncEnumerator : Js.t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Collections.Generic.IAsyncEnumerator`1::#isIAsyncEnumerator|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Collections.Generic.IAsyncEnumerator`1::#isIAsyncEnumerator|System.Object"
