(* Generated by binding-adaptor. Do not edit. *)
type t
(* func *)
external isIComparer : Js.t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Collections.Generic.IComparer`1::#isIComparer|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Collections.Generic.IComparer`1::#isIComparer|System.Object"
