(* Generated by binding-adaptor. Do not edit. *)
type t
(* func *)
external isIDisposable : Js.t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IDisposable::#isIDisposable|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IDisposable::#isIDisposable|System.Object"
