(* Generated by binding-adaptor. Do not edit. *)
type t
(* func *)
external isIGrouping : Js.t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Linq.IGrouping`2::#isIGrouping|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Linq.IGrouping`2::#isIGrouping|System.Object"
