(* Generated by binding-adaptor. Do not edit. *)
type t = Object.t
(* new *)
external create : string -> t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.InvalidOperationException::default" "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.InvalidOperationException::default"
(* new *)
external create_2 : unit -> t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.InvalidOperationException::default" "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.InvalidOperationException::default"
(* new *)
external create_3 : string -> Object.t -> t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.InvalidOperationException::default" "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.InvalidOperationException::default"
