(* Generated by binding-adaptor. Do not edit. *)
type t
(* func *)
external isIObservable : Js.t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IObservable`1::#isIObservable|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IObservable`1::#isIObservable|System.Object"
