(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external toJS : Js.t -> WebSharper_JavaScript.Object2.t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.Object"
(* inline *)
external toJS_2 : string -> WebSharper_JavaScript.String.t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.String"
(* inline *)
external toJS_3 : Object.t -> WebSharper_JavaScript.Error.t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.Exception" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.Exception"
(* inline *)
external toJS_4 : bool -> WebSharper_JavaScript.Boolean.t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.Boolean" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.Boolean"
(* inline *)
external toJS_5 : DateTime2.t -> WebSharper_JavaScript.Date.t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.DateTime" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.DateTime"
(* inline *)
external toJS_6 : int -> WebSharper_JavaScript.Number.t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.Byte" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.Byte"
(* inline *)
external toJS_7 : int -> WebSharper_JavaScript.Number.t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.SByte" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.SByte"
(* inline *)
external toJS_8 : int -> WebSharper_JavaScript.Number.t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.Int16" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.Int16"
(* inline *)
external toJS_9 : int -> WebSharper_JavaScript.Number.t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.Int32"
(* inline *)
external toJS_10 : int64 -> WebSharper_JavaScript.Number.t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.Int64" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.Int64"
(* inline *)
external toJS_11 : int -> WebSharper_JavaScript.Number.t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.UInt16" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.UInt16"
(* inline *)
external toJS_12 : int -> WebSharper_JavaScript.Number.t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.UInt32" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.UInt32"
(* inline *)
external toJS_13 : int64 -> WebSharper_JavaScript.Number.t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.UInt64" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.UInt64"
(* inline *)
external toJS_14 : float -> WebSharper_JavaScript.Number.t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.Single" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.Single"
(* inline *)
external toJS_15 : float -> WebSharper_JavaScript.Number.t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.Double" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|System.Double"
(* inline *)
external setJS : Js.t -> string -> Js.t -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#SetJS|System.Object|System.String|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#SetJS|System.Object|System.String|System.Object"
(* inline *)
external toJS_16 : ('a) array -> ('a) WebSharper_JavaScript.Array.t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|'0[]" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#ToJS|'0[]"
(* macro *)
external getJS : Js.t -> (string) array -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#GetJS|System.Object|System.String[]" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#GetJS|System.Object|System.String[]"
(* macro *)
external getJS_2 : Js.t -> (string) array -> Js.t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#GetJS|System.Object|System.String[]" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.JavaScriptExtensions::#GetJS|System.Object|System.String[]"
