(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external setPrev : ('a) LinkedListNode.t -> ('a) LinkedListNode.t -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.Collections.LinkedList::#setPrev|System.Collections.Generic.LinkedListNode`1<'0>|System.Collections.Generic.LinkedListNode`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.Collections.LinkedList::#setPrev|System.Collections.Generic.LinkedListNode`1<'0>|System.Collections.Generic.LinkedListNode`1<'0>"
(* inline *)
external setNext : ('a) LinkedListNode.t -> ('a) LinkedListNode.t -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.Collections.LinkedList::#setNext|System.Collections.Generic.LinkedListNode`1<'0>|System.Collections.Generic.LinkedListNode`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.Collections.LinkedList::#setNext|System.Collections.Generic.LinkedListNode`1<'0>|System.Collections.Generic.LinkedListNode`1<'0>"
(* inline *)
external newNode : ('a) LinkedListNode.t -> ('a) LinkedListNode.t -> 'a -> ('a) LinkedList.t -> ('a) LinkedListNode.t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.Collections.LinkedList::#newNode|System.Collections.Generic.LinkedListNode`1<'0>|System.Collections.Generic.LinkedListNode`1<'0>|'0|System.Collections.Generic.LinkedList`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.Collections.LinkedList::#newNode|System.Collections.Generic.LinkedListNode`1<'0>|System.Collections.Generic.LinkedListNode`1<'0>|'0|System.Collections.Generic.LinkedList`1<'0>"
