(* Generated by binding-adaptor. Do not edit. *)
type t
(* macro *)
external op_DivideQmark : 'a -> ('b) Nullable2.t -> ('c) Nullable2.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_DivideQmark|'0|System.Nullable`1<'1>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_DivideQmark|'0|System.Nullable`1<'1>"
(* macro *)
external op_EqualsQmark : 'a -> ('a) Nullable2.t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_EqualsQmark|'0|System.Nullable`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_EqualsQmark|'0|System.Nullable`1<'0>"
(* macro *)
external op_GreaterEqualsQmark : 'a -> ('a) Nullable2.t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_GreaterEqualsQmark|'0|System.Nullable`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_GreaterEqualsQmark|'0|System.Nullable`1<'0>"
(* macro *)
external op_GreaterQmark : 'a -> ('a) Nullable2.t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_GreaterQmark|'0|System.Nullable`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_GreaterQmark|'0|System.Nullable`1<'0>"
(* macro *)
external op_LessEqualsQmark : 'a -> ('a) Nullable2.t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_LessEqualsQmark|'0|System.Nullable`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_LessEqualsQmark|'0|System.Nullable`1<'0>"
(* macro *)
external op_LessGreaterQmark : 'a -> ('a) Nullable2.t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_LessGreaterQmark|'0|System.Nullable`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_LessGreaterQmark|'0|System.Nullable`1<'0>"
(* macro *)
external op_LessQmark : 'a -> ('a) Nullable2.t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_LessQmark|'0|System.Nullable`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_LessQmark|'0|System.Nullable`1<'0>"
(* macro *)
external op_MinusQmark : 'a -> ('b) Nullable2.t -> ('c) Nullable2.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_MinusQmark|'0|System.Nullable`1<'1>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_MinusQmark|'0|System.Nullable`1<'1>"
(* macro *)
external op_MultiplyQmark : 'a -> ('b) Nullable2.t -> ('c) Nullable2.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_MultiplyQmark|'0|System.Nullable`1<'1>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_MultiplyQmark|'0|System.Nullable`1<'1>"
(* macro *)
external op_PercentQmark : 'a -> ('b) Nullable2.t -> ('c) Nullable2.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_PercentQmark|'0|System.Nullable`1<'1>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_PercentQmark|'0|System.Nullable`1<'1>"
(* macro *)
external op_PlusQmark : 'a -> ('b) Nullable2.t -> ('c) Nullable2.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_PlusQmark|'0|System.Nullable`1<'1>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_PlusQmark|'0|System.Nullable`1<'1>"
(* macro *)
external op_QmarkDivide : ('a) Nullable2.t -> 'b -> ('c) Nullable2.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkDivide|System.Nullable`1<'0>|'1" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkDivide|System.Nullable`1<'0>|'1"
(* macro *)
external op_QmarkDivideQmark : ('a) Nullable2.t -> ('b) Nullable2.t -> ('c) Nullable2.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkDivideQmark|System.Nullable`1<'0>|System.Nullable`1<'1>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkDivideQmark|System.Nullable`1<'0>|System.Nullable`1<'1>"
(* macro *)
external op_QmarkEquals : ('a) Nullable2.t -> 'a -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkEquals|System.Nullable`1<'0>|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkEquals|System.Nullable`1<'0>|'0"
(* macro *)
external op_QmarkEqualsQmark : ('a) Nullable2.t -> ('a) Nullable2.t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkEqualsQmark|System.Nullable`1<'0>|System.Nullable`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkEqualsQmark|System.Nullable`1<'0>|System.Nullable`1<'0>"
(* macro *)
external op_QmarkGreater : ('a) Nullable2.t -> 'a -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkGreater|System.Nullable`1<'0>|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkGreater|System.Nullable`1<'0>|'0"
(* macro *)
external op_QmarkGreaterEquals : ('a) Nullable2.t -> 'a -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkGreaterEquals|System.Nullable`1<'0>|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkGreaterEquals|System.Nullable`1<'0>|'0"
(* macro *)
external op_QmarkGreaterEqualsQmark : ('a) Nullable2.t -> ('a) Nullable2.t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkGreaterEqualsQmark|System.Nullable`1<'0>|System.Nullable`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkGreaterEqualsQmark|System.Nullable`1<'0>|System.Nullable`1<'0>"
(* macro *)
external op_QmarkGreaterQmark : ('a) Nullable2.t -> ('a) Nullable2.t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkGreaterQmark|System.Nullable`1<'0>|System.Nullable`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkGreaterQmark|System.Nullable`1<'0>|System.Nullable`1<'0>"
(* macro *)
external op_QmarkLess : ('a) Nullable2.t -> 'a -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkLess|System.Nullable`1<'0>|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkLess|System.Nullable`1<'0>|'0"
(* macro *)
external op_QmarkLessEquals : ('a) Nullable2.t -> 'a -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkLessEquals|System.Nullable`1<'0>|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkLessEquals|System.Nullable`1<'0>|'0"
(* macro *)
external op_QmarkLessEqualsQmark : ('a) Nullable2.t -> ('a) Nullable2.t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkLessEqualsQmark|System.Nullable`1<'0>|System.Nullable`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkLessEqualsQmark|System.Nullable`1<'0>|System.Nullable`1<'0>"
(* macro *)
external op_QmarkLessGreater : ('a) Nullable2.t -> 'a -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkLessGreater|System.Nullable`1<'0>|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkLessGreater|System.Nullable`1<'0>|'0"
(* macro *)
external op_QmarkLessGreaterQmark : ('a) Nullable2.t -> ('a) Nullable2.t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkLessGreaterQmark|System.Nullable`1<'0>|System.Nullable`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkLessGreaterQmark|System.Nullable`1<'0>|System.Nullable`1<'0>"
(* macro *)
external op_QmarkLessQmark : ('a) Nullable2.t -> ('a) Nullable2.t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkLessQmark|System.Nullable`1<'0>|System.Nullable`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkLessQmark|System.Nullable`1<'0>|System.Nullable`1<'0>"
(* macro *)
external op_QmarkMinus : ('a) Nullable2.t -> 'b -> ('c) Nullable2.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkMinus|System.Nullable`1<'0>|'1" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkMinus|System.Nullable`1<'0>|'1"
(* macro *)
external op_QmarkMinusQmark : ('a) Nullable2.t -> ('b) Nullable2.t -> ('c) Nullable2.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkMinusQmark|System.Nullable`1<'0>|System.Nullable`1<'1>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkMinusQmark|System.Nullable`1<'0>|System.Nullable`1<'1>"
(* macro *)
external op_QmarkMultiply : ('a) Nullable2.t -> 'b -> ('c) Nullable2.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkMultiply|System.Nullable`1<'0>|'1" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkMultiply|System.Nullable`1<'0>|'1"
(* macro *)
external op_QmarkMultiplyQmark : ('a) Nullable2.t -> ('b) Nullable2.t -> ('c) Nullable2.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkMultiplyQmark|System.Nullable`1<'0>|System.Nullable`1<'1>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkMultiplyQmark|System.Nullable`1<'0>|System.Nullable`1<'1>"
(* macro *)
external op_QmarkPercent : ('a) Nullable2.t -> 'b -> ('c) Nullable2.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkPercent|System.Nullable`1<'0>|'1" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkPercent|System.Nullable`1<'0>|'1"
(* macro *)
external op_QmarkPercentQmark : ('a) Nullable2.t -> ('b) Nullable2.t -> ('c) Nullable2.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkPercentQmark|System.Nullable`1<'0>|System.Nullable`1<'1>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkPercentQmark|System.Nullable`1<'0>|System.Nullable`1<'1>"
(* macro *)
external op_QmarkPlus : ('a) Nullable2.t -> 'b -> ('c) Nullable2.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkPlus|System.Nullable`1<'0>|'1" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkPlus|System.Nullable`1<'0>|'1"
(* macro *)
external op_QmarkPlusQmark : ('a) Nullable2.t -> ('b) Nullable2.t -> ('c) Nullable2.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkPlusQmark|System.Nullable`1<'0>|System.Nullable`1<'1>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableOperators::#op_QmarkPlusQmark|System.Nullable`1<'0>|System.Nullable`1<'1>"
