(* Generated by binding-adaptor. Do not edit. *)
type t
(* macro *)
external toChar : ('a) Nullable2.t -> (char) Nullable2.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableModule::#ToChar|System.Nullable`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableModule::#ToChar|System.Nullable`1<'0>"
(* macro *)
external toDouble : ('a) Nullable2.t -> (float) Nullable2.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableModule::#ToDouble|System.Nullable`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableModule::#ToDouble|System.Nullable`1<'0>"
(* macro *)
external toFloat : ('a) Nullable2.t -> (float) Nullable2.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableModule::#ToFloat|System.Nullable`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableModule::#ToFloat|System.Nullable`1<'0>"
(* macro *)
external toInt : ('a) Nullable2.t -> (int) Nullable2.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableModule::#ToInt|System.Nullable`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableModule::#ToInt|System.Nullable`1<'0>"
(* macro *)
external toSingle : ('a) Nullable2.t -> (float) Nullable2.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableModule::#ToSingle|System.Nullable`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableModule::#ToSingle|System.Nullable`1<'0>"
(* macro *)
external toInt32 : ('a) Nullable2.t -> (int) Nullable2.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableModule::#ToInt32|System.Nullable`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableModule::#ToInt32|System.Nullable`1<'0>"
(* inline *)
external toEnum : (int) Nullable2.t -> ('a) Nullable2.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableModule::#ToEnum|System.Nullable`1<System.Int32>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableModule::#ToEnum|System.Nullable`1<System.Int32>"
(* macro *)
external toInt64 : ('a) Nullable2.t -> (int64) Nullable2.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableModule::#ToInt64|System.Nullable`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Linq.NullableModule::#ToInt64|System.Nullable`1<'0>"
