(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external infinity : unit -> float = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Infinity|" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Infinity|"
(* inline *)
external intRange : unit -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#intRange|" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#intRange|"
(* inline *)
external infinitySingle : unit -> float = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#InfinitySingle|" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#InfinitySingle|"
(* inline *)
external naNSingle : unit -> float = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#NaNSingle|" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#NaNSingle|"
(* inline *)
external naN : unit -> float = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#NaN|" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#NaN|"
(* inline *)
external infinity_2 : unit -> float = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#get_Infinity|" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#get_Infinity|"
(* inline *)
external get_intRange : unit -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#get_intRange|" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#get_intRange|"
(* inline *)
external infinitySingle_2 : unit -> float = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#get_InfinitySingle|" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#get_InfinitySingle|"
(* inline *)
external naNSingle_2 : unit -> float = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#get_NaNSingle|" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#get_NaNSingle|"
(* inline *)
external naN_2 : unit -> float = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#get_NaN|" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#get_NaN|"
(* inline *)
external op_Dereference : ('a) FSharpRef.t -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_Dereference|Microsoft.FSharp.Core.FSharpRef`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_Dereference|Microsoft.FSharp.Core.FSharpRef`1<'0>"
(* macro *)
external op_UnaryPlus : 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_UnaryPlus|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_UnaryPlus|'0"
(* macro *)
external op_UnaryNegation : 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_UnaryNegation|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_UnaryNegation|'0"
(* macro *)
external op_LogicalNot : 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_LogicalNot|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_LogicalNot|'0"
(* macro *)
external abs : 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Abs|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Abs|'0"
(* macro *)
external acos : 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Acos|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Acos|'0"
(* macro *)
external asin : 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Asin|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Asin|'0"
(* macro *)
external atan : 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Atan|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Atan|'0"
(* inline *)
external box : 'a -> Js.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Box|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Box|'0"
(* macro *)
external ceiling : 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Ceiling|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Ceiling|'0"
(* macro *)
external toChar : 'a -> char = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToChar|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToChar|'0"
(* macro *)
external toByte : 'a -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToByte|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToByte|'0"
(* macro *)
external toSByte : 'a -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToSByte|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToSByte|'0"
(* macro *)
external cos : 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Cos|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Cos|'0"
(* macro *)
external cosh : 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Cosh|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Cosh|'0"
(* inline *)
external decrement : (int) FSharpRef.t -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Decrement|Microsoft.FSharp.Core.FSharpRef`1<System.Int32>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Decrement|Microsoft.FSharp.Core.FSharpRef`1<System.Int32>"
(* inline *)
external enum : 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Enum|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Enum|'0"
(* macro *)
external toDecimal : 'a -> Js.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToDecimal|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToDecimal|'0"
(* macro *)
external toDouble : 'a -> float = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToDouble|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToDouble|'0"
(* macro *)
external exp : 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Exp|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Exp|'0"
(* macro *)
external toFloat : 'a -> float = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToFloat|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToFloat|'0"
(* macro *)
external floor : 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Floor|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Floor|'0"
(* inline *)
external fst : 'a * 'b -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Fst|('0,'1)" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Fst|('0,'1)"
(* inline *)
external identity : 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Identity|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Identity|'0"
(* inline *)
external ignore : 'a -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Ignore|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Ignore|'0"
(* inline *)
external increment : (int) FSharpRef.t -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Increment|Microsoft.FSharp.Core.FSharpRef`1<System.Int32>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Increment|Microsoft.FSharp.Core.FSharpRef`1<System.Int32>"
(* macro *)
external toInt : 'a -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToInt|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToInt|'0"
(* macro *)
external toInt16 : 'a -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToInt16|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToInt16|'0"
(* macro *)
external toSingle : 'a -> float = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToSingle|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToSingle|'0"
(* macro *)
external toInt32 : 'a -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToInt32|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToInt32|'0"
(* inline *)
external toEnum : int -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToEnum|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToEnum|System.Int32"
(* macro *)
external toInt64 : 'a -> int64 = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToInt64|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToInt64|'0"
(* macro *)
external toUInt16 : 'a -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToUInt16|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToUInt16|'0"
(* macro *)
external toUInt32 : 'a -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToUInt32|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToUInt32|'0"
(* macro *)
external toUInt64 : 'a -> int64 = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToUInt64|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToUInt64|'0"
(* inline *)
external log : 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Log|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Log|'0"
(* inline *)
external log10 : 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Log10|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Log10|'0"
(* inline *)
external not : bool -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Not|System.Boolean" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Not|System.Boolean"
(* inline *)
external raise : Object.t -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Raise|System.Exception" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Raise|System.Exception"
(* inline *)
external ref : 'a -> ('a) FSharpRef.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Ref|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Ref|'0"
(* inline *)
external round : 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Round|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Round|'0"
(* inline *)
external createSequence : ('a) IEnumerable2.t -> ('a) IEnumerable2.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#CreateSequence|System.Collections.Generic.IEnumerable`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#CreateSequence|System.Collections.Generic.IEnumerable`1<'0>"
(* macro *)
external sin : 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Sin|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Sin|'0"
(* macro *)
external sinh : 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Sinh|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Sinh|'0"
(* inline *)
external snd : 'a * 'b -> 'b = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Snd|('0,'1)" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Snd|('0,'1)"
(* inline *)
external sqrt : 'a -> 'b = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Sqrt|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Sqrt|'0"
(* macro *)
external toString : 'a -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToString|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#ToString|'0"
(* macro *)
external tan : 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Tan|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Tan|'0"
(* macro *)
external tanh : 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Tanh|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Tanh|'0"
(* inline *)
external unbox : Js.t -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Unbox|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Unbox|System.Object"
(* inline *)
external isNull : 'a -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#IsNull|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#IsNull|'0"
(* inline *)
external hash : 'a -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Hash|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Hash|'0"
(* inline *)
external truncate : 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Truncate|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Truncate|'0"
(* func *)
external bigIntAbs : int64 -> int64 = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#BigIntAbs|System.Int64" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#BigIntAbs|System.Int64"
(* func *)
external bigIntSign : int64 -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#BigIntSign|System.Int64" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#BigIntSign|System.Int64"
(* func *)
external keyValuePattern : ('a, 'b) KeyValuePair.t -> 'a * 'b = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#KeyValuePattern|System.Collections.Generic.KeyValuePair`2<'0,'1>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#KeyValuePattern|System.Collections.Generic.KeyValuePair`2<'0,'1>"
(* macro *)
external sign : 'a -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Sign|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Sign|'0"
(* func *)
external toInt_2 : float -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#toInt|System.Double" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#toInt|System.Double"
(* func *)
external toUInt : float -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#toUInt|System.Double" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#toUInt|System.Double"
(* func *)
external invalidOp : string -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#InvalidOp|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#InvalidOp|System.String"
(* func *)
external failWith : string -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#FailWith|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#FailWith|System.String"
(* macro *)
external op_Modulus : 'a -> 'b -> 'c = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_Modulus|'0|'1" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_Modulus|'0|'1"
(* macro *)
external op_BitwiseAnd : 'a -> 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_BitwiseAnd|'0|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_BitwiseAnd|'0|'0"
(* macro *)
external op_Multiply : 'a -> 'b -> 'c = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_Multiply|'0|'1" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_Multiply|'0|'1"
(* macro *)
external op_Exponentiation : 'a -> 'b -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_Exponentiation|'0|'1" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_Exponentiation|'0|'1"
(* inline *)
external powInteger : 'a -> int -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#PowInteger|'0|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#PowInteger|'0|System.Int32"
(* macro *)
external op_Addition : 'a -> 'b -> 'c = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_Addition|'0|'1" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_Addition|'0|'1"
(* macro *)
external op_Subtraction : 'a -> 'b -> 'c = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_Subtraction|'0|'1" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_Subtraction|'0|'1"
(* macro *)
external op_Division : 'a -> 'b -> 'c = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_Division|'0|'1" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_Division|'0|'1"
(* inline *)
external op_ColonEquals : ('a) FSharpRef.t -> 'a -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_ColonEquals|Microsoft.FSharp.Core.FSharpRef`1<'0>|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_ColonEquals|Microsoft.FSharp.Core.FSharpRef`1<'0>|'0"
(* macro *)
external op_LeftShift : 'a -> int -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_LeftShift|'0|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_LeftShift|'0|System.Int32"
(* macro *)
external op_Equality : 'a -> 'a -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_Equality|'0|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_Equality|'0|'0"
(* macro *)
external op_Inequality : 'a -> 'a -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_Inequality|'0|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_Inequality|'0|'0"
(* macro *)
external op_LessThan : 'a -> 'a -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_LessThan|'0|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_LessThan|'0|'0"
(* macro *)
external op_GreaterThan : 'a -> 'a -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_GreaterThan|'0|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_GreaterThan|'0|'0"
(* macro *)
external op_LessThanOrEqual : 'a -> 'a -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_LessThanOrEqual|'0|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_LessThanOrEqual|'0|'0"
(* macro *)
external op_GreaterThanOrEqual : 'a -> 'a -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_GreaterThanOrEqual|'0|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_GreaterThanOrEqual|'0|'0"
(* macro *)
external op_RightShift : 'a -> int -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_RightShift|'0|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_RightShift|'0|System.Int32"
(* inline *)
external op_Concatenate : string -> string -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_Concatenate|System.String|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_Concatenate|System.String|System.String"
(* macro *)
external op_ExclusiveOr : 'a -> 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_ExclusiveOr|'0|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_ExclusiveOr|'0|'0"
(* macro *)
external op_BitwiseOr : 'a -> 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_BitwiseOr|'0|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_BitwiseOr|'0|'0"
(* macro *)
external atan2 : 'a -> 'a -> 'b = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Atan2|'0|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Atan2|'0|'0"
(* inline *)
external op_PipeRight : 'a -> ('a -> 'b) -> 'b = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_PipeRight|'0|fn" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_PipeRight|'0|fn"
(* inline *)
external compare : 'a -> 'a -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Compare|'0|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Compare|'0|'0"
(* inline *)
external op_ComposeRight : ('a -> 'b) -> ('b -> 'c) -> ('a -> 'c) = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_ComposeRight|fn|fn" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_ComposeRight|fn|fn"
(* inline *)
external defaultArg : ('a) FSharpOption.t -> 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#DefaultArg|Microsoft.FSharp.Core.FSharpOption`1<'0>|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#DefaultArg|Microsoft.FSharp.Core.FSharpOption`1<'0>|'0"
(* inline *)
external min : 'a -> 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Min|'0|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Min|'0|'0"
(* inline *)
external max : 'a -> 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Max|'0|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Max|'0|'0"
(* inline *)
external op_ComposeLeft : ('a -> 'b) -> ('c -> 'a) -> ('c -> 'b) = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_ComposeLeft|fn|fn" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_ComposeLeft|fn|fn"
(* inline *)
external op_PipeLeft : ('a -> 'b) -> 'a -> 'b = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_PipeLeft|fn|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_PipeLeft|fn|'0"
(* inline *)
external op_Append : ('a) FSharpList.t -> ('a) FSharpList.t -> ('a) FSharpList.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_Append|Microsoft.FSharp.Collections.FSharpList`1<'0>|Microsoft.FSharp.Collections.FSharpList`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_Append|Microsoft.FSharp.Collections.FSharpList`1<'0>|Microsoft.FSharp.Collections.FSharpList`1<'0>"
(* inline *)
external defaultValueArg : ('a) FSharpValueOption.t -> 'a -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#DefaultValueArg|Microsoft.FSharp.Core.FSharpValueOption`1<'0>|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#DefaultValueArg|Microsoft.FSharp.Core.FSharpValueOption`1<'0>|'0"
(* inline *)
external lock : 'a -> (unit -> 'b) -> 'b = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Lock|'0|fn" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Lock|'0|fn"
(* inline *)
external using : 'a -> ('a -> 'b) -> 'b = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Using|'0|fn" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#Using|'0|fn"
(* macro *)
external op_Range : 'a -> 'a -> ('a) IEnumerable2.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_Range|'0|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_Range|'0|'0"
(* func *)
external invalidArg : string -> string -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#InvalidArg|System.String|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#InvalidArg|System.String|System.String"
(* inline *)
external op_PipeLeft2 : ('a -> ('b -> 'c)) -> 'a -> 'b -> 'c = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_PipeLeft2|fn|'0|'1" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_PipeLeft2|fn|'0|'1"
(* inline *)
external op_PipeRight2 : 'a -> 'b -> ('a -> ('b -> 'c)) -> 'c = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_PipeRight2|'0|'1|fn" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_PipeRight2|'0|'1|fn"
(* macro *)
external op_RangeStep : 'a -> 'b -> 'a -> ('a) IEnumerable2.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_RangeStep|'0|'1|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_RangeStep|'0|'1|'0"
(* inline *)
external op_PipeLeft3 : ('a -> ('b -> ('c -> 'd))) -> 'a -> 'b -> 'c -> 'd = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_PipeLeft3|fn|'0|'1|'2" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_PipeLeft3|fn|'0|'1|'2"
(* inline *)
external op_PipeRight3 : 'a -> 'b -> 'c -> ('a -> ('b -> ('c -> 'd))) -> 'd = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_PipeRight3|'0|'1|'2|fn" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Core.Operators::#op_PipeRight3|'0|'1|'2|fn"
