(* Generated by binding-adaptor. Do not edit. *)
type t = Object.t
(* inline *)
external cancellationToken : t -> CancellationToken.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.OperationCanceledException::default#get_CancellationToken|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.OperationCanceledException::default#get_CancellationToken|"
(* instance *)
external get_ct : t -> CancellationToken.t = "wsget:WebSharper.StdLib!WebSharper.StdLib/System.OperationCanceledException::default#ct" "wsget:WebSharper.StdLib!WebSharper.StdLib/System.OperationCanceledException::default#ct"
(* inline *)
external create : unit -> t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.OperationCanceledException::default" "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.OperationCanceledException::default"
(* inline *)
external create_2 : string -> t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.OperationCanceledException::default" "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.OperationCanceledException::default"
(* inline *)
external create_3 : string -> CancellationToken.t -> t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.OperationCanceledException::default" "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.OperationCanceledException::default"
(* inline *)
external create_4 : string -> Object.t -> t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.OperationCanceledException::default" "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.OperationCanceledException::default"
(* new *)
external create_5 : CancellationToken.t -> t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.OperationCanceledException::default" "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.OperationCanceledException::default"
(* new *)
external create_6 : string -> Object.t -> CancellationToken.t -> t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.OperationCanceledException::default" "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.OperationCanceledException::default"
