(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external empty : unit -> ('a) FSharpSet.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Empty|" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Empty|"
(* inline *)
external empty_2 : unit -> ('a) FSharpSet.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#get_Empty|" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#get_Empty|"
(* inline *)
external toTree : ('a) FSharpSet.t -> ('a) Tree.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#ToTree|Microsoft.FSharp.Collections.FSharpSet`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#ToTree|Microsoft.FSharp.Collections.FSharpSet`1<'0>"
(* inline *)
external ofTree : ('a) Tree.t -> ('a) FSharpSet.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#OfTree|WebSharper.Collections.BalancedTree+Tree`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#OfTree|WebSharper.Collections.BalancedTree+Tree`1<'0>"
(* inline *)
external count : ('a) FSharpSet.t -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Count|Microsoft.FSharp.Collections.FSharpSet`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Count|Microsoft.FSharp.Collections.FSharpSet`1<'0>"
(* inline *)
external intersectMany : (('a) FSharpSet.t) list -> ('a) FSharpSet.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#IntersectMany|System.Collections.Generic.IEnumerable`1<Microsoft.FSharp.Collections.FSharpSet`1<'0>>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#IntersectMany|System.Collections.Generic.IEnumerable`1<Microsoft.FSharp.Collections.FSharpSet`1<'0>>"
(* inline *)
external isEmpty : ('a) FSharpSet.t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#IsEmpty|Microsoft.FSharp.Collections.FSharpSet`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#IsEmpty|Microsoft.FSharp.Collections.FSharpSet`1<'0>"
(* inline *)
external ofSeq : ('a) list -> ('a) FSharpSet.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#OfSeq|System.Collections.Generic.IEnumerable`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#OfSeq|System.Collections.Generic.IEnumerable`1<'0>"
(* inline *)
external maxElement : ('a) FSharpSet.t -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#MaxElement|Microsoft.FSharp.Collections.FSharpSet`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#MaxElement|Microsoft.FSharp.Collections.FSharpSet`1<'0>"
(* inline *)
external minElement : ('a) FSharpSet.t -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#MinElement|Microsoft.FSharp.Collections.FSharpSet`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#MinElement|Microsoft.FSharp.Collections.FSharpSet`1<'0>"
(* inline *)
external ofList : ('a) FSharpList.t -> ('a) FSharpSet.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#OfList|Microsoft.FSharp.Collections.FSharpList`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#OfList|Microsoft.FSharp.Collections.FSharpList`1<'0>"
(* inline *)
external singleton : 'a -> ('a) FSharpSet.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Singleton|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Singleton|'0"
(* inline *)
external toArray : ('a) FSharpSet.t -> ('a) array = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#ToArray|Microsoft.FSharp.Collections.FSharpSet`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#ToArray|Microsoft.FSharp.Collections.FSharpSet`1<'0>"
(* inline *)
external toList : ('a) FSharpSet.t -> ('a) FSharpList.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#ToList|Microsoft.FSharp.Collections.FSharpSet`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#ToList|Microsoft.FSharp.Collections.FSharpSet`1<'0>"
(* inline *)
external toSeq : ('a) FSharpSet.t -> ('a) IEnumerable2.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#ToSeq|Microsoft.FSharp.Collections.FSharpSet`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#ToSeq|Microsoft.FSharp.Collections.FSharpSet`1<'0>"
(* inline *)
external unionMany : (('a) FSharpSet.t) list -> ('a) FSharpSet.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#UnionMany|System.Collections.Generic.IEnumerable`1<Microsoft.FSharp.Collections.FSharpSet`1<'0>>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#UnionMany|System.Collections.Generic.IEnumerable`1<Microsoft.FSharp.Collections.FSharpSet`1<'0>>"
(* inline *)
external add : 'a -> ('a) FSharpSet.t -> ('a) FSharpSet.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Add|'0|Microsoft.FSharp.Collections.FSharpSet`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Add|'0|Microsoft.FSharp.Collections.FSharpSet`1<'0>"
(* inline *)
external contains : 'a -> ('a) FSharpSet.t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Contains|'0|Microsoft.FSharp.Collections.FSharpSet`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Contains|'0|Microsoft.FSharp.Collections.FSharpSet`1<'0>"
(* inline *)
external difference : ('a) FSharpSet.t -> ('a) FSharpSet.t -> ('a) FSharpSet.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Difference|Microsoft.FSharp.Collections.FSharpSet`1<'0>|Microsoft.FSharp.Collections.FSharpSet`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Difference|Microsoft.FSharp.Collections.FSharpSet`1<'0>|Microsoft.FSharp.Collections.FSharpSet`1<'0>"
(* inline *)
external exists : ('a -> bool) -> ('a) FSharpSet.t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Exists|fn|Microsoft.FSharp.Collections.FSharpSet`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Exists|fn|Microsoft.FSharp.Collections.FSharpSet`1<'0>"
(* inline *)
external forAll : ('a -> bool) -> ('a) FSharpSet.t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#ForAll|fn|Microsoft.FSharp.Collections.FSharpSet`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#ForAll|fn|Microsoft.FSharp.Collections.FSharpSet`1<'0>"
(* inline *)
external intersect : ('a) FSharpSet.t -> ('a) FSharpSet.t -> ('a) FSharpSet.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Intersect|Microsoft.FSharp.Collections.FSharpSet`1<'0>|Microsoft.FSharp.Collections.FSharpSet`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Intersect|Microsoft.FSharp.Collections.FSharpSet`1<'0>|Microsoft.FSharp.Collections.FSharpSet`1<'0>"
(* inline *)
external isProperSubset : ('a) FSharpSet.t -> ('a) FSharpSet.t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#IsProperSubset|Microsoft.FSharp.Collections.FSharpSet`1<'0>|Microsoft.FSharp.Collections.FSharpSet`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#IsProperSubset|Microsoft.FSharp.Collections.FSharpSet`1<'0>|Microsoft.FSharp.Collections.FSharpSet`1<'0>"
(* inline *)
external isProperSuperset : ('a) FSharpSet.t -> ('a) FSharpSet.t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#IsProperSuperset|Microsoft.FSharp.Collections.FSharpSet`1<'0>|Microsoft.FSharp.Collections.FSharpSet`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#IsProperSuperset|Microsoft.FSharp.Collections.FSharpSet`1<'0>|Microsoft.FSharp.Collections.FSharpSet`1<'0>"
(* inline *)
external isSubset : ('a) FSharpSet.t -> ('a) FSharpSet.t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#IsSubset|Microsoft.FSharp.Collections.FSharpSet`1<'0>|Microsoft.FSharp.Collections.FSharpSet`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#IsSubset|Microsoft.FSharp.Collections.FSharpSet`1<'0>|Microsoft.FSharp.Collections.FSharpSet`1<'0>"
(* inline *)
external isSuperset : ('a) FSharpSet.t -> ('a) FSharpSet.t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#IsSuperset|Microsoft.FSharp.Collections.FSharpSet`1<'0>|Microsoft.FSharp.Collections.FSharpSet`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#IsSuperset|Microsoft.FSharp.Collections.FSharpSet`1<'0>|Microsoft.FSharp.Collections.FSharpSet`1<'0>"
(* inline *)
external iterate : ('a -> unit) -> ('a) FSharpSet.t -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Iterate|fn|Microsoft.FSharp.Collections.FSharpSet`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Iterate|fn|Microsoft.FSharp.Collections.FSharpSet`1<'0>"
(* inline *)
external map : ('a -> 'b) -> ('a) FSharpSet.t -> ('b) FSharpSet.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Map|fn|Microsoft.FSharp.Collections.FSharpSet`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Map|fn|Microsoft.FSharp.Collections.FSharpSet`1<'0>"
(* inline *)
external remove : 'a -> ('a) FSharpSet.t -> ('a) FSharpSet.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Remove|'0|Microsoft.FSharp.Collections.FSharpSet`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Remove|'0|Microsoft.FSharp.Collections.FSharpSet`1<'0>"
(* inline *)
external union : ('a) FSharpSet.t -> ('a) FSharpSet.t -> ('a) FSharpSet.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Union|Microsoft.FSharp.Collections.FSharpSet`1<'0>|Microsoft.FSharp.Collections.FSharpSet`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Union|Microsoft.FSharp.Collections.FSharpSet`1<'0>|Microsoft.FSharp.Collections.FSharpSet`1<'0>"
(* func *)
external partition : ('a -> bool) -> ('a) FSharpSet.t -> ('a) FSharpSet.t * ('a) FSharpSet.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Partition|fn|Microsoft.FSharp.Collections.FSharpSet`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Partition|fn|Microsoft.FSharp.Collections.FSharpSet`1<'0>"
(* func *)
external filter : ('a -> bool) -> ('a) FSharpSet.t -> ('a) FSharpSet.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Filter|fn|Microsoft.FSharp.Collections.FSharpSet`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Filter|fn|Microsoft.FSharp.Collections.FSharpSet`1<'0>"
(* inline *)
external fold : ('b -> ('a -> 'b)) -> 'b -> ('a) FSharpSet.t -> 'b = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Fold|fn|'1|Microsoft.FSharp.Collections.FSharpSet`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#Fold|fn|'1|Microsoft.FSharp.Collections.FSharpSet`1<'0>"
(* func *)
external foldBack : ('a -> ('b -> 'b)) -> ('a) FSharpSet.t -> 'b -> 'b = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#FoldBack|fn|Microsoft.FSharp.Collections.FSharpSet`1<'0>|'1" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#FoldBack|fn|Microsoft.FSharp.Collections.FSharpSet`1<'0>|'1"
(* inline *)
external ofArray : ('a) array -> ('a) FSharpSet.t = "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#OfArray|'0[]" "ws:WebSharper.StdLib!WebSharper.StdLib/Microsoft.FSharp.Collections.SetModule::#OfArray|'0[]"
