(* Generated by binding-adaptor. Do not edit. *)
type t = Object.t
(* inline *)
external append : t -> int -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Append|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Append|System.Int32"
(* inline *)
external append_2 : t -> int64 -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Append|System.Int64" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Append|System.Int64"
(* inline *)
external append_3 : t -> int -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Append|System.Int16" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Append|System.Int16"
(* inline *)
external append_4 : t -> int -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Append|System.SByte" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Append|System.SByte"
(* inline *)
external append_5 : t -> int -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Append|System.UInt32" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Append|System.UInt32"
(* inline *)
external append_6 : t -> int64 -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Append|System.UInt64" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Append|System.UInt64"
(* inline *)
external append_7 : t -> int -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Append|System.UInt16" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Append|System.UInt16"
(* inline *)
external append_8 : t -> int -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Append|System.Byte" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Append|System.Byte"
(* inline *)
external append_9 : t -> float -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Append|System.Single" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Append|System.Single"
(* inline *)
external append_10 : t -> float -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Append|System.Double" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Append|System.Double"
(* inline *)
external append_11 : t -> Js.t -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Append|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Append|System.Object"
(* inline *)
external append_12 : t -> bool -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Append|System.Boolean" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Append|System.Boolean"
(* inline *)
external append_13 : t -> char -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Append|System.Char" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Append|System.Char"
(* inline *)
external insert : t -> int -> int -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Insert|System.Int32|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Insert|System.Int32|System.Int32"
(* inline *)
external insert_2 : t -> int -> int64 -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Insert|System.Int32|System.Int64" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Insert|System.Int32|System.Int64"
(* inline *)
external insert_3 : t -> int -> int -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Insert|System.Int32|System.Int16" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Insert|System.Int32|System.Int16"
(* inline *)
external insert_4 : t -> int -> int -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Insert|System.Int32|System.SByte" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Insert|System.Int32|System.SByte"
(* inline *)
external insert_5 : t -> int -> int -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Insert|System.Int32|System.UInt32" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Insert|System.Int32|System.UInt32"
(* inline *)
external insert_6 : t -> int -> int64 -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Insert|System.Int32|System.UInt64" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Insert|System.Int32|System.UInt64"
(* inline *)
external insert_7 : t -> int -> int -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Insert|System.Int32|System.UInt16" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Insert|System.Int32|System.UInt16"
(* inline *)
external insert_8 : t -> int -> int -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Insert|System.Int32|System.Byte" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Insert|System.Int32|System.Byte"
(* inline *)
external insert_9 : t -> int -> float -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Insert|System.Int32|System.Single" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Insert|System.Int32|System.Single"
(* inline *)
external insert_10 : t -> int -> float -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Insert|System.Int32|System.Double" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Insert|System.Int32|System.Double"
(* inline *)
external insert_11 : t -> int -> Js.t -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Insert|System.Int32|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Insert|System.Int32|System.Object"
(* inline *)
external insert_12 : t -> int -> bool -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Insert|System.Int32|System.Boolean" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Insert|System.Int32|System.Boolean"
(* inline *)
external insert_13 : t -> int -> char -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Insert|System.Int32|System.Char" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Insert|System.Int32|System.Char"
(* inline *)
external replace : t -> char -> char -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Replace|System.Char|System.Char" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Replace|System.Char|System.Char"
(* inline *)
external replace_2 : t -> char -> char -> int -> int -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Replace|System.Char|System.Char|System.Int32|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Replace|System.Char|System.Char|System.Int32|System.Int32"
(* instance *)
external toString : t -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#ToString|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#ToString|"
(* instance *)
external get_Length : t -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#get_Length|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#get_Length|"
(* instance *)
external replace_3 : t -> string -> string -> int -> int -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Replace|System.String|System.String|System.Int32|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Replace|System.String|System.String|System.Int32|System.Int32"
(* instance *)
external replace_4 : t -> string -> string -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Replace|System.String|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Replace|System.String|System.String"
(* instance *)
external remove : t -> int -> int -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Remove|System.Int32|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Remove|System.Int32|System.Int32"
(* instance *)
external insert_14 : t -> int -> string -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Insert|System.Int32|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Insert|System.Int32|System.String"
(* instance *)
external clear : t -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Clear|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Clear|"
(* instance *)
external set_Chars : t -> int -> char -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#set_Chars|System.Int32|System.Char" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#set_Chars|System.Int32|System.Char"
(* instance *)
external get_Chars : t -> int -> char = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#get_Chars|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#get_Chars|System.Int32"
(* instance *)
external appendLine : t -> string -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#AppendLine|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#AppendLine|System.String"
(* instance *)
external append_14 : t -> string -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Append|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#Append|System.String"
(* instance *)
external get_strings : t -> (string) array = "wsget:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#strings" "wsget:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#strings"
(* instance *)
external set_strings : t -> (string) array -> unit = "wsset:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#strings" "wsset:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#strings"
(* instance *)
external get_init11 : t -> int = "wsget:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#init@11" "wsget:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#init@11"
(* instance *)
external set_init11 : t -> int -> unit = "wsset:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#init@11" "wsset:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default#init@11"
(* new *)
external create : string -> t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default" "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default"
(* new *)
external create_2 : unit -> t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default" "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.Text.StringBuilder::default"
