(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external clone : t -> Js.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Clone|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Clone|"
(* inline *)
external copy : t -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Copy|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Copy|"
(* inline *)
external empty : unit -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#get_Empty|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#get_Empty|"
(* inline *)
external length : t -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#get_Length|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#get_Length|"
(* inline *)
external toString : t -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#ToString|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#ToString|"
(* inline *)
external toLower : t -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#ToLower|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#ToLower|"
(* inline *)
external toUpper : t -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#ToUpper|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#ToUpper|"
(* inline *)
external getHashCode : t -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#GetHashCode|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#GetHashCode|"
(* inline *)
external getEnumerator : t -> Js.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#GetEnumerator|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#GetEnumerator|"
(* inline *)
external toCharArray : t -> (char) array = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#ToCharArray|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#ToCharArray|"
(* inline *)
external trim : t -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Trim|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Trim|"
(* inline *)
external trimStart : t -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#TrimStart|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#TrimStart|"
(* inline *)
external trimEnd : t -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#TrimEnd|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#TrimEnd|"
(* inline *)
external chars : t -> int -> char = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#get_Chars|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#get_Chars|System.Int32"
(* inline *)
external concat : Js.t -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Concat|System.ReadOnlySpan`1<System.String>" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Concat|System.ReadOnlySpan`1<System.String>"
(* inline *)
external contains : t -> string -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Contains|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Contains|System.String"
(* inline *)
external equals : t -> string -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Equals|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Equals|System.String"
(* inline *)
external equals_2 : t -> Js.t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Equals|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Equals|System.Object"
(* inline *)
external indexOf : t -> string -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#IndexOf|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#IndexOf|System.String"
(* inline *)
external indexOf_2 : t -> char -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#IndexOf|System.Char" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#IndexOf|System.Char"
(* inline *)
external item : t -> int -> char = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#get_Item|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#get_Item|System.Int32"
(* inline *)
external lastIndexOf : t -> string -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#LastIndexOf|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#LastIndexOf|System.String"
(* inline *)
external lastIndexOf_2 : t -> char -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#LastIndexOf|System.Char" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#LastIndexOf|System.Char"
(* inline *)
external remove : t -> int -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Remove|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Remove|System.Int32"
(* inline *)
external substring : t -> int -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Substring|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Substring|System.Int32"
(* inline *)
external compareTo : t -> string -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#CompareTo|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#CompareTo|System.String"
(* inline *)
external compareTo_2 : t -> Js.t -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#CompareTo|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#CompareTo|System.Object"
(* inline *)
external concat_2 : (string) list -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Concat|System.Collections.Generic.IEnumerable`1<System.String>" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Concat|System.Collections.Generic.IEnumerable`1<System.String>"
(* inline *)
external concat_3 : ('a) list -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Concat|System.Collections.Generic.IEnumerable`1<'0>" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Concat|System.Collections.Generic.IEnumerable`1<'0>"
(* inline *)
external concat_4 : Js.t -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Concat|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Concat|System.Object"
(* inline *)
external concat_5 : Js.t -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Concat|System.ReadOnlySpan`1<System.Object>" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Concat|System.ReadOnlySpan`1<System.Object>"
(* inline *)
external endsWith : t -> string -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#EndsWith|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#EndsWith|System.String"
(* inline *)
external isNullOrEmpty : string -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#IsNullOrEmpty|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#IsNullOrEmpty|System.String"
(* inline *)
external isNullOrWhiteSpace : string -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#IsNullOrWhiteSpace|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#IsNullOrWhiteSpace|System.String"
(* inline *)
external padLeft : t -> int -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#PadLeft|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#PadLeft|System.Int32"
(* inline *)
external padRight : t -> int -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#PadRight|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#PadRight|System.Int32"
(* inline *)
external startsWith : t -> string -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#StartsWith|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#StartsWith|System.String"
(* inline *)
external trim_2 : t -> char -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Trim|System.Char" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Trim|System.Char"
(* inline *)
external trimStart_2 : t -> char -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#TrimStart|System.Char" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#TrimStart|System.Char"
(* inline *)
external trimEnd_2 : t -> char -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#TrimEnd|System.Char" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#TrimEnd|System.Char"
(* inline *)
external equals_3 : string -> string -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Equals|System.String|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Equals|System.String|System.String"
(* inline *)
external indexOf_3 : t -> string -> int -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#IndexOf|System.String|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#IndexOf|System.String|System.Int32"
(* inline *)
external lastIndexOf_3 : t -> string -> int -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#LastIndexOf|System.String|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#LastIndexOf|System.String|System.Int32"
(* inline *)
external op_Addition : string -> string -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#op_Addition|System.String|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#op_Addition|System.String|System.String"
(* inline *)
external op_Equality : string -> string -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#op_Equality|System.String|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#op_Equality|System.String|System.String"
(* inline *)
external op_Inequality : string -> string -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#op_Inequality|System.String|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#op_Inequality|System.String|System.String"
(* macro *)
external format : string -> Js.t -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Format|System.String|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Format|System.String|System.Object"
(* inline *)
external compare : string -> string -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Compare|System.String|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Compare|System.String|System.String"
(* inline *)
external concat_6 : string -> string -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Concat|System.String|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Concat|System.String|System.String"
(* inline *)
external concat_7 : Js.t -> Js.t -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Concat|System.Object|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Concat|System.Object|System.Object"
(* inline *)
external indexOf_4 : t -> char -> int -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#IndexOf|System.Char|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#IndexOf|System.Char|System.Int32"
(* inline *)
external join : string -> (string) list -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Join|System.String|System.Collections.Generic.IEnumerable`1<System.String>" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Join|System.String|System.Collections.Generic.IEnumerable`1<System.String>"
(* inline *)
external lastIndexOf_4 : t -> char -> int -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#LastIndexOf|System.Char|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#LastIndexOf|System.Char|System.Int32"
(* inline *)
external padLeft_2 : t -> int -> char -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#PadLeft|System.Int32|System.Char" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#PadLeft|System.Int32|System.Char"
(* inline *)
external padRight_2 : t -> int -> char -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#PadRight|System.Int32|System.Char" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#PadRight|System.Int32|System.Char"
(* inline *)
external remove_2 : t -> int -> int -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Remove|System.Int32|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Remove|System.Int32|System.Int32"
(* inline *)
external replace : t -> string -> string -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Replace|System.String|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Replace|System.String|System.String"
(* inline *)
external replace_2 : t -> char -> char -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Replace|System.Char|System.Char" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Replace|System.Char|System.Char"
(* inline *)
external split : t -> char -> Js.t -> (string) array = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Split|System.Char|System.StringSplitOptions" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Split|System.Char|System.StringSplitOptions"
(* inline *)
external substring_2 : t -> int -> int -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Substring|System.Int32|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Substring|System.Int32|System.Int32"
(* inline *)
external toCharArray_2 : t -> int -> int -> (char) array = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#ToCharArray|System.Int32|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#ToCharArray|System.Int32|System.Int32"
(* inline *)
external op_Addition_2 : Js.t -> string -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#op_Addition|System.Object|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#op_Addition|System.Object|System.String"
(* inline *)
external op_Addition_3 : string -> Js.t -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#op_Addition|System.String|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#op_Addition|System.String|System.Object"
(* macro *)
external format_2 : string -> Js.t -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Format|System.String|System.ReadOnlySpan`1<System.Object>" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Format|System.String|System.ReadOnlySpan`1<System.Object>"
(* macro *)
external format_3 : string -> Js.t -> Js.t -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Format|System.String|System.Object|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Format|System.String|System.Object|System.Object"
(* inline *)
external compare_2 : string -> string -> bool -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Compare|System.String|System.String|System.Boolean" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Compare|System.String|System.String|System.Boolean"
(* inline *)
external concat_8 : string -> string -> string -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Concat|System.String|System.String|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Concat|System.String|System.String|System.String"
(* inline *)
external concat_9 : Js.t -> Js.t -> Js.t -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Concat|System.Object|System.Object|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Concat|System.Object|System.Object|System.Object"
(* macro *)
external format_4 : string -> Js.t -> Js.t -> Js.t -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Format|System.String|System.Object|System.Object|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Format|System.String|System.Object|System.Object|System.Object"
(* inline *)
external concat_10 : string -> string -> string -> string -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Concat|System.String|System.String|System.String|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Concat|System.String|System.String|System.String|System.String"
(* inline *)
external concat_11 : (string) array -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Concat|System.String[]" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Concat|System.String[]"
(* inline *)
external concat_12 : (Js.t) array -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Concat|System.Object[]" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Concat|System.Object[]"
(* inline *)
external split_2 : t -> (char) array -> (string) array = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Split|System.Char[]" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Split|System.Char[]"
(* inline *)
external trim_3 : t -> (char) array -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Trim|System.Char[]" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Trim|System.Char[]"
(* inline *)
external trimStart_3 : t -> (char) array -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#TrimStart|System.Char[]" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#TrimStart|System.Char[]"
(* inline *)
external trimEnd_3 : t -> (char) array -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#TrimEnd|System.Char[]" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#TrimEnd|System.Char[]"
(* macro *)
external format_5 : string -> (Js.t) array -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Format|System.String|System.Object[]" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Format|System.String|System.Object[]"
(* inline *)
external join_2 : string -> (string) array -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Join|System.String|System.String[]" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Join|System.String|System.String[]"
(* inline *)
external split_3 : t -> (char) array -> Js.t -> (string) array = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Split|System.Char[]|System.StringSplitOptions" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Split|System.Char[]|System.StringSplitOptions"
(* inline *)
external split_4 : t -> (string) array -> Js.t -> (string) array = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Split|System.String[]|System.StringSplitOptions" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#Split|System.String[]|System.StringSplitOptions"
(* inline *)
external copyTo : t -> int -> (char) array -> int -> int -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#CopyTo|System.Int32|System.Char[]|System.Int32|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/System.String::#CopyTo|System.Int32|System.Char[]|System.Int32|System.Int32"
(* inline *)
external create : unit -> t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.String::" "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.String::"
(* inline *)
external create_2 : (char) array -> t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.String::" "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.String::"
(* inline *)
external create_3 : (char) array -> int -> int -> t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.String::" "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.String::"
(* inline *)
external create_4 : char -> int -> t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.String::" "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.String::"
