(* Generated by binding-adaptor. Do not edit. *)
type ('a) t = Object.t
(* inline *)
external continueWith : ('a) t -> Js.t -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default#ContinueWith|System.Action`1<System.Threading.Tasks.Task`1<'0>>" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default#ContinueWith|System.Action`1<System.Threading.Tasks.Task`1<'0>>"
(* inline *)
external continueWith_2 : ('a) t -> Js.t -> Js.t -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default#ContinueWith|System.Action`1<System.Threading.Tasks.Task`1<'0>>|System.Threading.CancellationToken" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default#ContinueWith|System.Action`1<System.Threading.Tasks.Task`1<'0>>|System.Threading.CancellationToken"
(* inline *)
external continueWith_3 : ('a) t -> Js.t -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default#ContinueWith|System.Func`2<System.Threading.Tasks.Task`1<'0>,'1>" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default#ContinueWith|System.Func`2<System.Threading.Tasks.Task`1<'0>,'1>"
(* inline *)
external continueWith_4 : ('a) t -> Js.t -> Js.t -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default#ContinueWith|System.Func`2<System.Threading.Tasks.Task`1<'0>,'1>|System.Threading.CancellationToken" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default#ContinueWith|System.Func`2<System.Threading.Tasks.Task`1<'0>,'1>|System.Threading.CancellationToken"
(* inline *)
external continueWith_5 : ('a) t -> Js.t -> Js.t -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default#ContinueWith|System.Action`2<System.Threading.Tasks.Task`1<'0>,System.Object>|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default#ContinueWith|System.Action`2<System.Threading.Tasks.Task`1<'0>,System.Object>|System.Object"
(* inline *)
external continueWith_6 : ('a) t -> Js.t -> Js.t -> Js.t -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default#ContinueWith|System.Action`2<System.Threading.Tasks.Task`1<'0>,System.Object>|System.Object|System.Threading.CancellationToken" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default#ContinueWith|System.Action`2<System.Threading.Tasks.Task`1<'0>,System.Object>|System.Object|System.Threading.CancellationToken"
(* inline *)
external continueWith_7 : ('a) t -> Js.t -> Js.t -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default#ContinueWith|System.Func`3<System.Threading.Tasks.Task`1<'0>,System.Object,'1>|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default#ContinueWith|System.Func`3<System.Threading.Tasks.Task`1<'0>,System.Object,'1>|System.Object"
(* inline *)
external continueWith_8 : ('a) t -> Js.t -> Js.t -> Js.t -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default#ContinueWith|System.Func`3<System.Threading.Tasks.Task`1<'0>,System.Object,'1>|System.Object|System.Threading.CancellationToken" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default#ContinueWith|System.Func`3<System.Threading.Tasks.Task`1<'0>,System.Object,'1>|System.Object|System.Threading.CancellationToken"
(* instance *)
external get_Result : ('a) t -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default#get_Result|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default#get_Result|"
(* instance *)
external execute : ('a) t -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default#Execute|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default#Execute|"
(* instance *)
external get_result284 : ('a) t -> 'a = "wsget:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default#result@284" "wsget:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default#result@284"
(* instance *)
external get_func : ('a) t -> Js.t = "wsget:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default#func" "wsget:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default#func"
(* new *)
external create : Js.t -> Js.t -> Js.t -> ('a) t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default" "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default"
(* new *)
external create_2 : Js.t -> Js.t -> ('a) t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default" "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default"
(* new *)
external create_3 : Js.t -> Js.t -> ('a) t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default" "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default"
(* new *)
external create_4 : Js.t -> ('a) t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default" "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default"
(* new *)
external create_5 : Js.t -> Js.t -> Js.t -> Object.t -> 'a -> ('a) t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default" "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.Task`1::default"
