(* Generated by binding-adaptor. Do not edit. *)
type t
(* new *)
external create : unit -> t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.TaskCanceledException::default" "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.TaskCanceledException::default"
(* new *)
external create_2 : string -> t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.TaskCanceledException::default" "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.TaskCanceledException::default"
