(* Generated by binding-adaptor. Do not edit. *)
type t
(* instance *)
external get_Encoding : t -> Js.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#get_Encoding|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#get_Encoding|"
(* instance *)
external writeLine : t -> (char) array -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.Char[]" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.Char[]"
(* instance *)
external writeLine_2 : t -> int -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.Int32"
(* instance *)
external writeLine_3 : t -> int64 -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.Int64" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.Int64"
(* instance *)
external writeLine_4 : t -> Js.t -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.Object"
(* instance *)
external writeLine_5 : t -> string -> Js.t -> Js.t -> Js.t -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.String|System.Object|System.Object|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.String|System.Object|System.Object|System.Object"
(* instance *)
external writeLine_6 : t -> string -> Js.t -> Js.t -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.String|System.Object|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.String|System.Object|System.Object"
(* instance *)
external writeLine_7 : t -> float -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.Single" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.Single"
(* instance *)
external writeLine_8 : t -> float -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.Double" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.Double"
(* instance *)
external writeLine_9 : t -> string -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.String"
(* instance *)
external writeLine_10 : t -> int -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.UInt32" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.UInt32"
(* instance *)
external writeLine_11 : t -> int64 -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.UInt64" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.UInt64"
(* instance *)
external writeLine_12 : t -> string -> Js.t -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.String|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.String|System.Object"
(* instance *)
external writeLine_13 : t -> string -> (Js.t) array -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.String|System.Object[]" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.String|System.Object[]"
(* instance *)
external writeLine_14 : t -> (char) array -> int -> int -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.Char[]|System.Int32|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.Char[]|System.Int32|System.Int32"
(* instance *)
external writeLine_15 : t -> char -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.Char" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.Char"
(* instance *)
external writeLine_16 : t -> bool -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.Boolean" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|System.Boolean"
(* instance *)
external writeLine_17 : t -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#WriteLine|"
(* instance *)
external write : t -> (char) array -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.Char[]" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.Char[]"
(* instance *)
external write_2 : t -> int -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.Int32"
(* instance *)
external write_3 : t -> int64 -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.Int64" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.Int64"
(* instance *)
external write_4 : t -> Js.t -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.Object"
(* instance *)
external write_5 : t -> string -> Js.t -> Js.t -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.String|System.Object|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.String|System.Object|System.Object"
(* instance *)
external write_6 : t -> float -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.Single" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.Single"
(* instance *)
external write_7 : t -> float -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.Double" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.Double"
(* instance *)
external write_8 : t -> string -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.String"
(* instance *)
external write_9 : t -> int -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.UInt32" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.UInt32"
(* instance *)
external write_10 : t -> int64 -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.UInt64" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.UInt64"
(* instance *)
external write_11 : t -> string -> Js.t -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.String|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.String|System.Object"
(* instance *)
external write_12 : t -> string -> (Js.t) array -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.String|System.Object[]" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.String|System.Object[]"
(* instance *)
external write_13 : t -> (char) array -> int -> int -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.Char[]|System.Int32|System.Int32" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.Char[]|System.Int32|System.Int32"
(* instance *)
external write_14 : t -> char -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.Char" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.Char"
(* instance *)
external write_15 : t -> bool -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.Boolean" "ws:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default#Write|System.Boolean"
(* new *)
external create : unit -> t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default" "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.IO.TextWriter::default"
