(* Generated by binding-adaptor. Do not edit. *)
type ('a, 'b, 'c, 'd, 'e, 'f) t
(* inline *)
external bind : ('a, 'b, 'c, 'd, 'e, 'f) t -> 'a -> Js.t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.ThisFunc`6::#Bind|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.ThisFunc`6::#Bind|'0"
(* macro *)
external call : 'a -> 'b -> 'c -> 'd -> 'e -> 'f = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.ThisFunc`6::#Call|'0|'1|'2|'3|'4" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.ThisFunc`6::#Call|'0|'1|'2|'3|'4"
(* inline *)
external create : Js.t -> ('a, 'b, 'c, 'd, 'e, 'f) t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.ThisFunc`6::" "wsnew:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.ThisFunc`6::"
