(* Generated by binding-adaptor. Do not edit. *)
type ('a, 'b, 'c, 'd, 'e) t
(* inline *)
external bind : ('a, 'b, 'c, 'd, 'e) t -> 'a -> Js.t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.ThisAction`5::#Bind|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.ThisAction`5::#Bind|'0"
(* macro *)
external call : 'a -> 'b -> 'c -> 'd -> 'e -> unit = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.ThisAction`5::#Call|'0|'1|'2|'3|'4" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.ThisAction`5::#Call|'0|'1|'2|'3|'4"
(* inline *)
external create : Js.t -> ('a, 'b, 'c, 'd, 'e) t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.ThisAction`5::" "wsnew:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.ThisAction`5::"
