(* Generated by binding-adaptor. Do not edit. *)
type ('a, 'b, 'c, 'd, 'e, 'f) t
(* inline *)
external item1 : ('a, 'b, 'c, 'd, 'e, 'f) t -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Tuple`6::#get_Item1|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Tuple`6::#get_Item1|"
(* inline *)
external item2 : ('a, 'b, 'c, 'd, 'e, 'f) t -> 'b = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Tuple`6::#get_Item2|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Tuple`6::#get_Item2|"
(* inline *)
external item3 : ('a, 'b, 'c, 'd, 'e, 'f) t -> 'c = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Tuple`6::#get_Item3|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Tuple`6::#get_Item3|"
(* inline *)
external item4 : ('a, 'b, 'c, 'd, 'e, 'f) t -> 'd = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Tuple`6::#get_Item4|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Tuple`6::#get_Item4|"
(* inline *)
external item5 : ('a, 'b, 'c, 'd, 'e, 'f) t -> 'e = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Tuple`6::#get_Item5|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Tuple`6::#get_Item5|"
(* inline *)
external item6 : ('a, 'b, 'c, 'd, 'e, 'f) t -> 'f = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Tuple`6::#get_Item6|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Tuple`6::#get_Item6|"
(* inline *)
external create : 'a -> 'b -> 'c -> 'd -> 'e -> 'f -> ('a, 'b, 'c, 'd, 'e, 'f) t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.Tuple`6::" "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.Tuple`6::"
