(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external zero : unit -> int64 = "ws:WebSharper.StdLib!WebSharper.StdLib/System.UInt64::#get_Zero|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.UInt64::#get_Zero|"
(* inline *)
external one : unit -> int64 = "ws:WebSharper.StdLib!WebSharper.StdLib/System.UInt64::#get_One|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.UInt64::#get_One|"
(* func *)
external parse : string -> int64 = "ws:WebSharper.StdLib!WebSharper.StdLib/System.UInt64::#Parse|System.String" "ws:WebSharper.StdLib!WebSharper.StdLib/System.UInt64::#Parse|System.String"
(* func *)
external tryParse : string -> int64 -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/System.UInt64::#TryParse|System.String|System.UInt64" "ws:WebSharper.StdLib!WebSharper.StdLib/System.UInt64::#TryParse|System.String|System.UInt64"
