(* Generated by binding-adaptor. Do not edit. *)
type ('a, 'b, 'c, 'd) t
(* inline *)
external value1 : ('a, 'b, 'c, 'd) t -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#get_Value1|" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#get_Value1|"
(* inline *)
external value2 : ('a, 'b, 'c, 'd) t -> 'b = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#get_Value2|" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#get_Value2|"
(* inline *)
external value3 : ('a, 'b, 'c, 'd) t -> 'c = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#get_Value3|" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#get_Value3|"
(* inline *)
external value4 : ('a, 'b, 'c, 'd) t -> 'd = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#get_Value4|" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#get_Value4|"
(* inline *)
external op_Implicit : 'a -> ('a, 'b, 'c, 'd) t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#op_Implicit|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#op_Implicit|'0"
(* inline *)
external op_Implicit_2 : ('a, 'b, 'c, 'd) t -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#op_Implicit|WebSharper.JavaScript.Union`4<'0,'1,'2,'3>" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#op_Implicit|WebSharper.JavaScript.Union`4<'0,'1,'2,'3>"
(* inline *)
external op_Implicit_3 : 'b -> ('a, 'b, 'c, 'd) t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#op_Implicit|'1" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#op_Implicit|'1"
(* inline *)
external op_Implicit_4 : ('a, 'b, 'c, 'd) t -> 'b = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#op_Implicit|WebSharper.JavaScript.Union`4<'0,'1,'2,'3>" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#op_Implicit|WebSharper.JavaScript.Union`4<'0,'1,'2,'3>"
(* inline *)
external op_Implicit_5 : 'c -> ('a, 'b, 'c, 'd) t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#op_Implicit|'2" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#op_Implicit|'2"
(* inline *)
external op_Implicit_6 : ('a, 'b, 'c, 'd) t -> 'c = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#op_Implicit|WebSharper.JavaScript.Union`4<'0,'1,'2,'3>" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#op_Implicit|WebSharper.JavaScript.Union`4<'0,'1,'2,'3>"
(* inline *)
external op_Implicit_7 : 'd -> ('a, 'b, 'c, 'd) t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#op_Implicit|'3" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#op_Implicit|'3"
(* inline *)
external op_Implicit_8 : ('a, 'b, 'c, 'd) t -> 'd = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#op_Implicit|WebSharper.JavaScript.Union`4<'0,'1,'2,'3>" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#op_Implicit|WebSharper.JavaScript.Union`4<'0,'1,'2,'3>"
(* func *)
external newUnion4Of4 : 'd -> ('a, 'b, 'c, 'd) t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#NewUnion4Of4|'3" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#NewUnion4Of4|'3"
(* func *)
external newUnion3Of4 : 'c -> ('a, 'b, 'c, 'd) t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#NewUnion3Of4|'2" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#NewUnion3Of4|'2"
(* func *)
external newUnion2Of4 : 'b -> ('a, 'b, 'c, 'd) t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#NewUnion2Of4|'1" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#NewUnion2Of4|'1"
(* func *)
external newUnion1Of4 : 'a -> ('a, 'b, 'c, 'd) t = "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#NewUnion1Of4|'0" "ws:WebSharper.StdLib!WebSharper.StdLib/WebSharper.JavaScript.Union`4::#NewUnion1Of4|'0"
