(* Generated by binding-adaptor. Do not edit. *)
type ('a, 'b, 'c, 'd) t
(* inline *)
external item1 : ('a, 'b, 'c, 'd) t -> 'a = "ws:WebSharper.StdLib!WebSharper.StdLib/System.ValueTuple`4::#get_Item1|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.ValueTuple`4::#get_Item1|"
(* inline *)
external item2 : ('a, 'b, 'c, 'd) t -> 'b = "ws:WebSharper.StdLib!WebSharper.StdLib/System.ValueTuple`4::#get_Item2|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.ValueTuple`4::#get_Item2|"
(* inline *)
external item3 : ('a, 'b, 'c, 'd) t -> 'c = "ws:WebSharper.StdLib!WebSharper.StdLib/System.ValueTuple`4::#get_Item3|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.ValueTuple`4::#get_Item3|"
(* inline *)
external item4 : ('a, 'b, 'c, 'd) t -> 'd = "ws:WebSharper.StdLib!WebSharper.StdLib/System.ValueTuple`4::#get_Item4|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.ValueTuple`4::#get_Item4|"
(* inline *)
external create : 'a -> 'b -> 'c -> 'd -> ('a, 'b, 'c, 'd) t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.ValueTuple`4::" "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.ValueTuple`4::"
