(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external completedTask : unit -> t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.ValueTask::#get_CompletedTask|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.ValueTask::#get_CompletedTask|"
(* inline *)
external asTask : t -> Object.t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.ValueTask::#AsTask|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.ValueTask::#AsTask|"
(* inline *)
external preserve : t -> t = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.ValueTask::#Preserve|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.ValueTask::#Preserve|"
(* inline *)
external isCompletedSuccessfully : t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.ValueTask::#get_IsCompletedSuccessfully|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.ValueTask::#get_IsCompletedSuccessfully|"
(* inline *)
external isCompleted : t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.ValueTask::#get_IsCompleted|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.ValueTask::#get_IsCompleted|"
(* inline *)
external isFaulted : t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.ValueTask::#get_IsFaulted|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.ValueTask::#get_IsFaulted|"
(* inline *)
external isCanceled : t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.ValueTask::#get_IsCanceled|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.ValueTask::#get_IsCanceled|"
(* inline *)
external create : Object.t -> t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.ValueTask::" "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.ValueTask::"
(* inline *)
external create_2 : unit -> t = "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.ValueTask::" "wsnew:WebSharper.StdLib!WebSharper.StdLib/System.Threading.Tasks.ValueTask::"
