(* Generated by binding-adaptor. Do not edit. *)
type t
(* inline *)
external getHashCode : t -> int = "ws:WebSharper.StdLib!WebSharper.StdLib/System.ValueType::#GetHashCode|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.ValueType::#GetHashCode|"
(* inline *)
external toString : t -> string = "ws:WebSharper.StdLib!WebSharper.StdLib/System.ValueType::#ToString|" "ws:WebSharper.StdLib!WebSharper.StdLib/System.ValueType::#ToString|"
(* inline *)
external equals : t -> Js.t -> bool = "ws:WebSharper.StdLib!WebSharper.StdLib/System.ValueType::#Equals|System.Object" "ws:WebSharper.StdLib!WebSharper.StdLib/System.ValueType::#Equals|System.Object"
