#!/usr/bin/env bash
# Build a wsocaml app against the raw-FFI test fixture in bindings-legacy/.
# The fixture exercises the backend's `js:`/`jsm:`/`jse:`/`ccall` lowering; it is
# generated by scripts/gen-bindings.py. The full browser surface lives in the
# generated `websharper-javascript` package (see build-ws-app.sh).
#   build-js-app.sh <entry.ml> [out-dir]
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
fe="$root/frontend/_build/default/bin/main.exe"
be="$root/backend/bin/Debug/net10.0/WebSharper.OCaml.dll"
s="$(ocamlc -where)"
bdir="$root/bindings-legacy"
entry="$1"
out="${2:-$root/out}"
mkdir -p "$out"

# dependency order (module names, capitalized)
order="Js Event UiEvent MouseEvent KeyboardEvent Node Element HtmlElement
HtmlInputElement HtmlOptionElement Document Window Storage Url TextEncoder
Json JsDate JsArray Console Math"
base_of() { echo "$(echo "${1:0:1}" | tr 'A-Z' 'a-z')${1:1}"; }

# 1) type-check bindings -> .cmi
for m in $order; do
  f="$bdir/$(base_of "$m").ml"
  [ -f "$f" ] || continue
  (cd "$bdir" && ocamlc -c -I "$s" "$(basename "$f")")
done

# 2) compile bindings -> .js
for m in $order; do
  f="$bdir/$(base_of "$m").ml"
  [ -f "$f" ] || continue
  "$fe" --input "$f" --output "$out/$(base_of "$m").wsir.json" --unit "$m" -I "$bdir" -I "$s"
  dotnet "$be" --ir "$out/$(base_of "$m").wsir.json" --output "$out" --compact
done

# 3) compile entry -> .js
"$fe" --input "$entry" --output "$out/main.wsir.json" --unit Main -I "$bdir" -I "$s"
dotnet "$be" --ir "$out/main.wsir.json" --output "$out" --compact

# 4) link stdlib shims + package.json
cp "$root/backend/tests/Stdlib"*.js "$out/"
printf '{ "type": "module" }\n' > "$out/package.json"
echo "built $out/Main.js"
