#!/usr/bin/env python3
"""Generate OCaml binding modules for browser/JS globals from a compact spec.

Each module is a set of `external`s over `Js.t` (opaque JS handle). FFI schemes:
  js:<path>        global call        (path dotted, e.g. Math.max)
  jsnew:<path>     global new
  jsget:<path>     global property get
  jsset:<path>     global property set
  jsm:<name>       receiver method call     (receiver = first arg)
  jsgp:<name>      receiver property get
  jssp:<name>      receiver property set
Usage: gen-bindings.py [bindings-dir]
"""
import os
import sys

DIR = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), "..", "bindings")


def M(name, members, typename="t", prelude=""):
    return (name, typename, members, prelude)


SPEC = [
    M("Node", [
        ("node_type", "t -> int", "jsgp:nodeType"),
        ("node_name", "t -> string", "jsgp:nodeName"),
        ("node_value", "t -> string", "jsgp:nodeValue"),
        ("set_node_value", "t -> string -> unit", "jssp:nodeValue"),
        ("parent_node", "t -> t", "jsgp:parentNode"),
        ("parent_element", "t -> t", "jsgp:parentElement"),
        ("child_nodes", "t -> t", "jsgp:childNodes"),
        ("first_child", "t -> t", "jsgp:firstChild"),
        ("last_child", "t -> t", "jsgp:lastChild"),
        ("next_sibling", "t -> t", "jsgp:nextSibling"),
        ("previous_sibling", "t -> t", "jsgp:previousSibling"),
        ("text_content", "t -> string", "jsgp:textContent"),
        ("set_text_content", "t -> string -> unit", "jssp:textContent"),
        ("is_connected", "t -> bool", "jsgp:isConnected"),
        ("append_child", "t -> t -> t", "jsm:appendChild"),
        ("remove_child", "t -> t -> t", "jsm:removeChild"),
        ("replace_child", "t -> t -> t -> t", "jsm:replaceChild"),
        ("insert_before", "t -> t -> t -> t", "jsm:insertBefore"),
        ("clone_node", "t -> bool -> t", "jsm:cloneNode"),
        ("contains", "t -> t -> bool", "jsm:contains"),
        ("normalize", "t -> unit", "jsm:normalize"),
    ]),
    M("Element", [
        ("tag_name", "t -> string", "jsgp:tagName"),
        ("id", "t -> string", "jsgp:id"),
        ("set_id", "t -> string -> unit", "jssp:id"),
        ("class_name", "t -> string", "jsgp:className"),
        ("set_class_name", "t -> string -> unit", "jssp:className"),
        ("inner_html", "t -> string", "jsgp:innerHTML"),
        ("set_inner_html", "t -> string -> unit", "jssp:innerHTML"),
        ("outer_html", "t -> string", "jsgp:outerHTML"),
        ("set_outer_html", "t -> string -> unit", "jssp:outerHTML"),
        ("class_list", "t -> t", "jsgp:classList"),
        ("children", "t -> t", "jsgp:children"),
        ("first_element_child", "t -> t", "jsgp:firstElementChild"),
        ("last_element_child", "t -> t", "jsgp:lastElementChild"),
        ("next_element_sibling", "t -> t", "jsgp:nextElementSibling"),
        ("previous_element_sibling", "t -> t", "jsgp:previousElementSibling"),
        ("child_element_count", "t -> int", "jsgp:childElementCount"),
        ("get_attribute", "t -> string -> string", "jsm:getAttribute"),
        ("set_attribute", "t -> string -> string -> unit", "jsm:setAttribute"),
        ("remove_attribute", "t -> string -> unit", "jsm:removeAttribute"),
        ("has_attribute", "t -> string -> bool", "jsm:hasAttribute"),
        ("query_selector", "t -> string -> t", "jsm:querySelector"),
        ("query_selector_all", "t -> string -> t", "jsm:querySelectorAll"),
        ("get_elements_by_tag_name", "t -> string -> t", "jsm:getElementsByTagName"),
        ("get_elements_by_class_name", "t -> string -> t", "jsm:getElementsByClassName"),
        ("closest", "t -> string -> t", "jsm:closest"),
        ("matches", "t -> string -> bool", "jsm:matches"),
        ("get_bounding_client_rect", "t -> DomRectReadOnly.t", "jsm:getBoundingClientRect"),
        ("attach_shadow", "t -> t -> t", "jsm:attachShadow"),
        ("shadow_root", "t -> t", "jsgp:shadowRoot"),
        ("remove", "t -> unit", "jsm:remove"),
        ("append", "t -> t -> unit", "jsm:append"),
        ("prepend", "t -> t -> unit", "jsm:prepend"),
        ("insert_adjacent_html", "t -> string -> string -> unit", "jsm:insertAdjacentHTML"),
        ("scroll_into_view", "t -> unit", "jsm:scrollIntoView"),
        ("scroll_top", "t -> float", "jsgp:scrollTop"),
        ("set_scroll_top", "t -> float -> unit", "jssp:scrollTop"),
        ("client_width", "t -> int", "jsgp:clientWidth"),
        ("client_height", "t -> int", "jsgp:clientHeight"),
        ("add_event_listener", "t -> string -> (Event.t -> unit) -> unit", "jsm:addEventListener"),
        ("remove_event_listener", "t -> string -> (Event.t -> unit) -> unit", "jsm:removeEventListener"),
        ("dispatch_event", "t -> Event.t -> bool", "jsm:dispatchEvent"),
    ]),
    M("HtmlElement", [
        ("style", "t -> t", "jsgp:style"),
        ("dataset", "t -> t", "jsgp:dataset"),
        ("inner_text", "t -> string", "jsgp:innerText"),
        ("set_inner_text", "t -> string -> unit", "jssp:innerText"),
        ("title", "t -> string", "jsgp:title"),
        ("set_title", "t -> string -> unit", "jssp:title"),
        ("lang", "t -> string", "jsgp:lang"),
        ("hidden", "t -> bool", "jsgp:hidden"),
        ("set_hidden", "t -> bool -> unit", "jssp:hidden"),
        ("click", "t -> unit", "jsm:click"),
        ("focus", "t -> unit", "jsm:focus"),
        ("blur", "t -> unit", "jsm:blur"),
        ("offset_width", "t -> int", "jsgp:offsetWidth"),
        ("offset_height", "t -> int", "jsgp:offsetHeight"),
        ("tab_index", "t -> int", "jsgp:tabIndex"),
        ("set_tab_index", "t -> int -> unit", "jssp:tabIndex"),
        ("content_editable", "t -> string", "jsgp:contentEditable"),
        ("set_content_editable", "t -> string -> unit", "jssp:contentEditable"),
    ]),
    M("HtmlDivElement", [
        ("align", "t -> string", "jsgp:align"),
        ("set_align", "t -> string -> unit", "jssp:align"),
    ], "t = HtmlElement.t"),
    M("HtmlInputElement", [
        ("value", "t -> string", "jsgp:value"),
        ("set_value", "t -> string -> unit", "jssp:value"),
        ("checked", "t -> bool", "jsgp:checked"),
        ("set_checked", "t -> bool -> unit", "jssp:checked"),
        ("input_type", "t -> string", "jsgp:type"),
        ("set_input_type", "t -> string -> unit", "jssp:type"),
        ("placeholder", "t -> string", "jsgp:placeholder"),
        ("set_placeholder", "t -> string -> unit", "jssp:placeholder"),
        ("disabled", "t -> bool", "jsgp:disabled"),
        ("set_disabled", "t -> bool -> unit", "jssp:disabled"),
        ("read_only", "t -> bool", "jsgp:readOnly"),
        ("name", "t -> string", "jsgp:name"),
        ("accept", "t -> string", "jsgp:accept"),
        ("files", "t -> t", "jsgp:files"),
        ("select", "t -> unit", "jsm:select"),
        ("check_validity", "t -> bool", "jsm:checkValidity"),
        ("report_validity", "t -> bool", "jsm:reportValidity"),
    ], "t = HtmlElement.t"),
    M("HtmlCanvasElement", [
        ("width", "t -> int", "jsgp:width"),
        ("set_width", "t -> int -> unit", "jssp:width"),
        ("height", "t -> int", "jsgp:height"),
        ("set_height", "t -> int -> unit", "jssp:height"),
        ("get_context", "t -> string -> CanvasRenderingContext2D.t", "jsm:getContext"),
        ("to_data_url", "t -> string -> string", "jsm:toDataURL"),
    ], "t = HtmlElement.t"),
    M("HtmlImageElement", [
        ("src", "t -> string", "jsgp:src"),
        ("set_src", "t -> string -> unit", "jssp:src"),
        ("alt", "t -> string", "jsgp:alt"),
        ("set_alt", "t -> string -> unit", "jssp:alt"),
        ("width", "t -> int", "jsgp:width"),
        ("height", "t -> int", "jsgp:height"),
        ("complete", "t -> bool", "jsgp:complete"),
        ("natural_width", "t -> int", "jsgp:naturalWidth"),
        ("natural_height", "t -> int", "jsgp:naturalHeight"),
        ("cross_origin", "t -> string", "jsgp:crossOrigin"),
    ], "t = HtmlElement.t"),
    M("Text", [
        ("data", "t -> string", "jsgp:data"),
        ("set_data", "t -> string -> unit", "jssp:data"),
        ("split_text", "t -> int -> t", "jsm:splitText"),
        ("whole_text", "t -> string", "jsgp:wholeText"),
    ]),
    M("Comment", [
        ("data", "t -> string", "jsgp:data"),
        ("set_data", "t -> string -> unit", "jssp:data"),
    ]),
    M("Attr", [
        ("name", "t -> string", "jsgp:name"),
        ("value", "t -> string", "jsgp:value"),
        ("set_value", "t -> string -> unit", "jssp:value"),
        ("owner_element", "t -> t", "jsgp:ownerElement"),
    ]),
    M("NodeList", [
        ("length", "t -> int", "jsgp:length"),
        ("item", "t -> int -> t", "jsm:item"),
        ("for_each", "t -> (t -> unit) -> unit", "jsm:forEach"),
    ]),
    M("HtmlCollection", [
        ("length", "t -> int", "jsgp:length"),
        ("item", "t -> int -> t", "jsm:item"),
        ("named_item", "t -> string -> t", "jsm:namedItem"),
    ]),
    M("DomTokenList", [
        ("length", "t -> int", "jsgp:length"),
        ("value", "t -> string", "jsgp:value"),
        ("contains", "t -> string -> bool", "jsm:contains"),
        ("add", "t -> string -> unit", "jsm:add"),
        ("remove", "t -> string -> unit", "jsm:remove"),
        ("toggle", "t -> string -> bool", "jsm:toggle"),
        ("replace", "t -> string -> string -> bool", "jsm:replace"),
        ("item", "t -> int -> string", "jsm:item"),
    ]),
    M("CssStyle", [
        ("get_property_value", "t -> string -> string", "jsm:getPropertyValue"),
        ("set_property", "t -> string -> string -> unit", "jsm:setProperty"),
        ("remove_property", "t -> string -> unit", "jsm:removeProperty"),
        ("css_text", "t -> string", "jsgp:cssText"),
        ("set_css_text", "t -> string -> unit", "jssp:cssText"),
    ]),
    M("DocumentFragment", [
        ("query_selector", "t -> string -> t", "jsm:querySelector"),
        ("get_element_by_id", "t -> string -> t", "jsm:getElementById"),
        ("children", "t -> t", "jsgp:children"),
    ]),
    M("Document", [
        ("get_element_by_id", "t -> string -> t", "jsm:getElementById"),
        ("get_elements_by_tag_name", "t -> string -> t", "jsm:getElementsByTagName"),
        ("get_elements_by_class_name", "t -> string -> t", "jsm:getElementsByClassName"),
        ("query_selector", "t -> string -> t", "jsm:querySelector"),
        ("query_selector_all", "t -> string -> t", "jsm:querySelectorAll"),
        ("create_element", "t -> string -> t", "jsm:createElement"),
        ("create_element_ns", "t -> string -> string -> t", "jsm:createElementNS"),
        ("create_text_node", "t -> string -> t", "jsm:createTextNode"),
        ("create_comment", "t -> string -> t", "jsm:createComment"),
        ("create_document_fragment", "t -> t", "jsm:createDocumentFragment"),
        ("create_attribute", "t -> string -> t", "jsm:createAttribute"),
        ("import_node", "t -> t -> bool -> t", "jsm:importNode"),
        ("adopt_node", "t -> t -> t", "jsm:adoptNode"),
        ("has_focus", "t -> bool", "jsm:hasFocus"),
        ("body", "t -> t", "jsgp:body"),
        ("head", "t -> t", "jsgp:head"),
        ("document_element", "t -> t", "jsgp:documentElement"),
        ("active_element", "t -> t", "jsgp:activeElement"),
        ("title", "t -> string", "jsgp:title"),
        ("set_title", "t -> string -> unit", "jssp:title"),
        ("cookie", "t -> string", "jsgp:cookie"),
        ("set_cookie", "t -> string -> unit", "jssp:cookie"),
        ("location", "t -> Location.t", "jsgp:location"),
        ("ready_state", "t -> string", "jsgp:readyState"),
        ("url", "t -> string", "jsgp:URL"),
    ]),
    M("Location", [
        ("href", "t -> string", "jsgp:href"),
        ("set_href", "t -> string -> unit", "jssp:href"),
        ("protocol", "t -> string", "jsgp:protocol"),
        ("host", "t -> string", "jsgp:host"),
        ("hostname", "t -> string", "jsgp:hostname"),
        ("port", "t -> string", "jsgp:port"),
        ("pathname", "t -> string", "jsgp:pathname"),
        ("set_pathname", "t -> string -> unit", "jssp:pathname"),
        ("search", "t -> string", "jsgp:search"),
        ("set_search", "t -> string -> unit", "jssp:search"),
        ("hash", "t -> string", "jsgp:hash"),
        ("set_hash", "t -> string -> unit", "jssp:hash"),
        ("origin", "t -> string", "jsgp:origin"),
        ("assign", "t -> string -> unit", "jsm:assign"),
        ("replace", "t -> string -> unit", "jsm:replace"),
        ("reload", "t -> unit", "jsm:reload"),
        ("to_string", "t -> string", "jsm:toString"),
    ]),
    M("Navigator", [
        ("user_agent", "t -> string", "jsgp:userAgent"),
        ("language", "t -> string", "jsgp:language"),
        ("languages", "t -> t", "jsgp:languages"),
        ("platform", "t -> string", "jsgp:platform"),
        ("on_line", "t -> bool", "jsgp:onLine"),
        ("hardware_concurrency", "t -> int", "jsgp:hardwareConcurrency"),
        ("max_touch_points", "t -> int", "jsgp:maxTouchPoints"),
        ("cookie_enabled", "t -> bool", "jsgp:cookieEnabled"),
        ("clipboard", "t -> t", "jsgp:clipboard"),
        ("geolocation", "t -> t", "jsgp:geolocation"),
        ("media_devices", "t -> MediaDevices.t", "jsgp:mediaDevices"),
        ("permissions", "t -> Permissions.t", "jsgp:permissions"),
        ("storage", "t -> StorageManager.t", "jsgp:storage"),
        ("service_worker", "t -> t", "jsgp:serviceWorker"),
    ]),
    M("History", [
        ("length", "t -> int", "jsgp:length"),
        ("state", "t -> t", "jsgp:state"),
        ("scroll_restoration", "t -> string", "jsgp:scrollRestoration"),
        ("back", "t -> unit", "jsm:back"),
        ("forward", "t -> unit", "jsm:forward"),
        ("go", "t -> int -> unit", "jsm:go"),
        ("push_state", "t -> t -> string -> string -> unit", "jsm:pushState"),
        ("replace_state", "t -> t -> string -> string -> unit", "jsm:replaceState"),
    ]),
    M("Screen", [
        ("width", "t -> int", "jsgp:width"),
        ("height", "t -> int", "jsgp:height"),
        ("avail_width", "t -> int", "jsgp:availWidth"),
        ("avail_height", "t -> int", "jsgp:availHeight"),
        ("color_depth", "t -> int", "jsgp:colorDepth"),
        ("pixel_depth", "t -> int", "jsgp:pixelDepth"),
        ("orientation", "t -> t", "jsgp:orientation"),
    ]),
    M("Performance", [
        ("now", "unit -> float", "js0:performance.now"),
        ("time_origin", "t -> float", "jsgp:timeOrigin"),
        ("mark", "t -> string -> unit", "jsm:mark"),
        ("measure", "t -> string -> unit", "jsm:measure"),
        ("clear_marks", "t -> string -> unit", "jsm:clearMarks"),
        ("clear_measures", "t -> string -> unit", "jsm:clearMeasures"),
        ("get_entries", "t -> t", "jsm:getEntries"),
        ("get_entries_by_type", "t -> string -> t", "jsm:getEntriesByType"),
        ("get_entries_by_name", "t -> string -> t", "jsm:getEntriesByName"),
        ("memory", "t -> t", "jsgp:memory"),
    ]),
    M("Event", [
        ("event_type", "t -> string", "jsgp:type"),
        ("target", "t -> t", "jsgp:target"),
        ("current_target", "t -> t", "jsgp:currentTarget"),
        ("event_phase", "t -> int", "jsgp:eventPhase"),
        ("bubbles", "t -> bool", "jsgp:bubbles"),
        ("cancelable", "t -> bool", "jsgp:cancelable"),
        ("default_prevented", "t -> bool", "jsgp:defaultPrevented"),
        ("time_stamp", "t -> float", "jsgp:timeStamp"),
        ("is_trusted", "t -> bool", "jsgp:isTrusted"),
        ("prevent_default", "t -> unit", "jsm:preventDefault"),
        ("stop_propagation", "t -> unit", "jsm:stopPropagation"),
        ("stop_immediate_propagation", "t -> unit", "jsm:stopImmediatePropagation"),
        ("composed_path", "t -> t", "jsm:composedPath"),
    ]),
    M("UiEvent", [
        ("detail", "t -> int", "jsgp:detail"),
        ("view", "t -> t", "jsgp:view"),
        ("which", "t -> int", "jsgp:which"),
    ], "t = Event.t"),
    M("MouseEvent", [
        ("client_x", "t -> float", "jsgp:clientX"),
        ("client_y", "t -> float", "jsgp:clientY"),
        ("page_x", "t -> float", "jsgp:pageX"),
        ("page_y", "t -> float", "jsgp:pageY"),
        ("screen_x", "t -> float", "jsgp:screenX"),
        ("screen_y", "t -> float", "jsgp:screenY"),
        ("offset_x", "t -> float", "jsgp:offsetX"),
        ("offset_y", "t -> float", "jsgp:offsetY"),
        ("button", "t -> int", "jsgp:button"),
        ("buttons", "t -> int", "jsgp:buttons"),
        ("ctrl_key", "t -> bool", "jsgp:ctrlKey"),
        ("shift_key", "t -> bool", "jsgp:shiftKey"),
        ("alt_key", "t -> bool", "jsgp:altKey"),
        ("meta_key", "t -> bool", "jsgp:metaKey"),
        ("related_target", "t -> t", "jsgp:relatedTarget"),
        ("which", "t -> int", "jsgp:which"),
    ], "t = Event.t"),
    M("KeyboardEvent", [
        ("key", "t -> string", "jsgp:key"),
        ("code", "t -> string", "jsgp:code"),
        ("key_code", "t -> int", "jsgp:keyCode"),
        ("which", "t -> int", "jsgp:which"),
        ("location", "t -> int", "jsgp:location"),
        ("ctrl_key", "t -> bool", "jsgp:ctrlKey"),
        ("shift_key", "t -> bool", "jsgp:shiftKey"),
        ("alt_key", "t -> bool", "jsgp:altKey"),
        ("meta_key", "t -> bool", "jsgp:metaKey"),
        ("repeat", "t -> bool", "jsgp:repeat"),
        ("is_composing", "t -> bool", "jsgp:isComposing"),
        ("get_modifier_state", "t -> string -> bool", "jsm:getModifierState"),
    ], "t = Event.t"),
    M("FocusEvent", [
        ("related_target", "t -> t", "jsgp:relatedTarget"),
    ], "t = Event.t"),
    M("WheelEvent", [
        ("delta_x", "t -> float", "jsgp:deltaX"),
        ("delta_y", "t -> float", "jsgp:deltaY"),
        ("delta_z", "t -> float", "jsgp:deltaZ"),
        ("delta_mode", "t -> int", "jsgp:deltaMode"),
    ], "t = Event.t"),
    M("TouchEvent", [
        ("touches", "t -> t", "jsgp:touches"),
        ("target_touches", "t -> t", "jsgp:targetTouches"),
        ("changed_touches", "t -> t", "jsgp:changedTouches"),
        ("alt_key", "t -> bool", "jsgp:altKey"),
        ("ctrl_key", "t -> bool", "jsgp:ctrlKey"),
        ("shift_key", "t -> bool", "jsgp:shiftKey"),
        ("meta_key", "t -> bool", "jsgp:metaKey"),
    ], "t = Event.t"),
    M("MessageEvent", [
        ("data", "t -> t", "jsgp:data"),
        ("origin", "t -> string", "jsgp:origin"),
        ("last_event_id", "t -> string", "jsgp:lastEventId"),
        ("source", "t -> t", "jsgp:source"),
        ("ports", "t -> t", "jsgp:ports"),
    ], "t = Event.t"),
    M("ProgressEvent", [
        ("length_computable", "t -> bool", "jsgp:lengthComputable"),
        ("loaded", "t -> float", "jsgp:loaded"),
        ("total", "t -> float", "jsgp:total"),
    ]),
    M("PointerEvent", [
        ("pointer_id", "t -> int", "jsgp:pointerId"),
        ("pointer_type", "t -> string", "jsgp:pointerType"),
        ("width", "t -> float", "jsgp:width"),
        ("height", "t -> float", "jsgp:height"),
        ("pressure", "t -> float", "jsgp:pressure"),
        ("is_primary", "t -> bool", "jsgp:isPrimary"),
    ]),
    M("DragEvent", [
        ("data_transfer", "t -> t", "jsgp:dataTransfer"),
    ]),
    M("InputEvent", [
        ("data", "t -> string", "jsgp:data"),
        ("input_type", "t -> string", "jsgp:inputType"),
        ("is_composing", "t -> bool", "jsgp:isComposing"),
    ]),
    M("CompositionEvent", [
        ("data", "t -> string", "jsgp:data"),
    ]),
    M("SubmitEvent", [
        ("submitter", "t -> t", "jsgp:submitter"),
    ]),
    M("Json", [
        ("parse", "string -> value", "js:JSON.parse"),
        ("stringify", "value -> string", "js:JSON.stringify"),
    ], "value = Js.t"),
    M("JsDate", [
        ("now", "unit -> float", "js0:Date.now"),
        ("create", "unit -> t", "jsnew0:Date"),
        ("get_time", "t -> float", "jsm:getTime"),
        ("value_of", "t -> float", "jsm:valueOf"),
        ("get_full_year", "t -> int", "jsm:getFullYear"),
        ("get_month", "t -> int", "jsm:getMonth"),
        ("get_date", "t -> int", "jsm:getDate"),
        ("get_day", "t -> int", "jsm:getDay"),
        ("get_hours", "t -> int", "jsm:getHours"),
        ("get_minutes", "t -> int", "jsm:getMinutes"),
        ("get_seconds", "t -> int", "jsm:getSeconds"),
        ("get_milliseconds", "t -> int", "jsm:getMilliseconds"),
        ("get_timezone_offset", "t -> int", "jsm:getTimezoneOffset"),
        ("set_time", "t -> float -> float", "jsm:setTime"),
        ("to_iso_string", "t -> string", "jsm:toISOString"),
        ("to_json", "t -> string", "jsm:toJSON"),
        ("to_string", "t -> string", "jsm:toString"),
    ]),
    M("RegExp", [
        ("create", "string -> t", "jsnew:RegExp"),
        ("test", "t -> string -> bool", "jsm:test"),
        ("exec", "t -> string -> t", "jsm:exec"),
        ("source", "t -> string", "jsgp:source"),
        ("flags", "t -> string", "jsgp:flags"),
        ("global", "t -> bool", "jsgp:global"),
        ("last_index", "t -> int", "jsgp:lastIndex"),
    ]),
    M("JsError", [
        ("create", "string -> t", "jsnew:Error"),
        ("message", "t -> string", "jsgp:message"),
        ("name", "t -> string", "jsgp:name"),
        ("stack", "t -> string", "jsgp:stack"),
    ]),
    M("Promise", [
        ("create", "((Js.t -> unit) -> (Js.t -> unit) -> unit) -> t", "jsnew:Promise"),
        ("then", "t -> (Js.t -> Js.t) -> t", "jsm:then"),
        ("catch_", "t -> (Js.t -> Js.t) -> t", "jsm:catch"),
        ("resolve", "Js.t -> t", "js:Promise.resolve"),
        ("reject", "Js.t -> t", "js:Promise.reject"),
        ("all", "Js.t -> t", "js:Promise.all"),
    ]),
    M("JsObject", [
        ("create", "unit -> t", "jsnew0:Object"),
        ("keys", "t -> Js.t", "js:Object.keys"),
        ("values", "t -> Js.t", "js:Object.values"),
        ("entries", "t -> Js.t", "js:Object.entries"),
        ("assign", "t -> t -> t", "js:Object.assign"),
        ("freeze", "t -> t", "js:Object.freeze"),
    ]),
    M("JsArray", [
        ("create", "unit -> t", "jsnew0:Array"),
        ("length", "t -> int", "jsgp:length"),
        ("get", "t -> int -> Js.t", "jsdget"),
        ("set", "t -> int -> Js.t -> unit", "jsdset"),
        ("push", "t -> Js.t -> int", "jsm:push"),
        ("pop", "t -> Js.t", "jsm:pop"),
        ("shift", "t -> Js.t", "jsm:shift"),
        ("unshift", "t -> Js.t -> int", "jsm:unshift"),
        ("join", "t -> string -> string", "jsm:join"),
        ("slice", "t -> int -> int -> t", "jsm:slice"),
        ("splice", "t -> int -> int -> t", "jsm:splice"),
        ("concat", "t -> t -> t", "jsm:concat"),
        ("index_of", "t -> Js.t -> int", "jsm:indexOf"),
        ("reverse", "t -> t", "jsm:reverse"),
        ("sort", "t -> t", "jsm:sort"),
        ("for_each", "t -> (Js.t -> unit) -> unit", "jsm:forEach"),
        ("map", "t -> (Js.t -> Js.t) -> t", "jsm:map"),
        ("filter", "t -> (Js.t -> bool) -> t", "jsm:filter"),
    ]),
    M("JsMap", [
        ("create", "unit -> t", "jsnew0:Map"),
        ("size", "t -> int", "jsgp:size"),
        ("set", "t -> Js.t -> Js.t -> t", "jsm:set"),
        ("get", "t -> Js.t -> Js.t", "jsm:get"),
        ("has", "t -> Js.t -> bool", "jsm:has"),
        ("delete", "t -> Js.t -> bool", "jsm:delete"),
        ("clear", "t -> unit", "jsm:clear"),
        ("for_each", "t -> (Js.t -> Js.t -> unit) -> unit", "jsm:forEach"),
        ("keys", "t -> Js.t", "jsm:keys"),
        ("values", "t -> Js.t", "jsm:values"),
        ("entries", "t -> Js.t", "jsm:entries"),
    ]),
    M("JsSet", [
        ("create", "unit -> t", "jsnew0:Set"),
        ("size", "t -> int", "jsgp:size"),
        ("add", "t -> Js.t -> t", "jsm:add"),
        ("has", "t -> Js.t -> bool", "jsm:has"),
        ("delete", "t -> Js.t -> bool", "jsm:delete"),
        ("clear", "t -> unit", "jsm:clear"),
        ("for_each", "t -> (Js.t -> unit) -> unit", "jsm:forEach"),
        ("values", "t -> Js.t", "jsm:values"),
    ]),
    M("WeakMap", [
        ("create", "unit -> t", "jsnew0:WeakMap"),
        ("set", "t -> Js.t -> Js.t -> t", "jsm:set"),
        ("get", "t -> Js.t -> Js.t", "jsm:get"),
        ("has", "t -> Js.t -> bool", "jsm:has"),
        ("delete", "t -> Js.t -> bool", "jsm:delete"),
    ]),
    M("WeakSet", [
        ("create", "unit -> t", "jsnew0:WeakSet"),
        ("add", "t -> Js.t -> t", "jsm:add"),
        ("has", "t -> Js.t -> bool", "jsm:has"),
        ("delete", "t -> Js.t -> bool", "jsm:delete"),
    ]),
    M("JsSymbol", [
        ("create", "string -> t", "js:Symbol"),
        ("for_", "string -> t", "js:Symbol.for"),
        ("key_for", "t -> string", "js:Symbol.keyFor"),
    ]),
    M("Window", [
        ("get", "unit -> t", "jsget:window"),
        ("alert", "t -> string -> unit", "jsm:alert"),
        ("confirm", "t -> string -> bool", "jsm:confirm"),
        ("prompt", "t -> string -> string", "jsm:prompt"),
        ("console", "t -> Console.t", "jsgp:console"),
        ("document", "t -> Document.t", "jsgp:document"),
        ("location", "t -> Location.t", "jsgp:location"),
        ("history", "t -> History.t", "jsgp:history"),
        ("navigator", "t -> Navigator.t", "jsgp:navigator"),
        ("screen", "t -> Screen.t", "jsgp:screen"),
        ("performance", "t -> Performance.t", "jsgp:performance"),
        ("inner_width", "t -> int", "jsgp:innerWidth"),
        ("inner_height", "t -> int", "jsgp:innerHeight"),
        ("outer_width", "t -> int", "jsgp:outerWidth"),
        ("outer_height", "t -> int", "jsgp:outerHeight"),
        ("scroll_x", "t -> float", "jsgp:scrollX"),
        ("scroll_y", "t -> float", "jsgp:scrollY"),
        ("device_pixel_ratio", "t -> float", "jsgp:devicePixelRatio"),
        ("get_computed_style", "t -> t -> CssStyle.t", "jsm:getComputedStyle"),
        ("match_media", "t -> string -> t", "jsm:matchMedia"),
        ("add_event_listener", "t -> string -> (Event.t -> unit) -> unit", "jsm:addEventListener"),
        ("remove_event_listener", "t -> string -> (Event.t -> unit) -> unit", "jsm:removeEventListener"),
        ("set_timeout", "t -> (unit -> unit) -> int -> int", "jsm:setTimeout"),
        ("clear_timeout", "t -> int -> unit", "jsm:clearTimeout"),
        ("set_interval", "t -> (unit -> unit) -> int -> int", "jsm:setInterval"),
        ("clear_interval", "t -> int -> unit", "jsm:clearInterval"),
        ("request_animation_frame", "t -> (float -> unit) -> int", "jsm:requestAnimationFrame"),
        ("cancel_animation_frame", "t -> int -> unit", "jsm:cancelAnimationFrame"),
        ("atob", "t -> string -> string", "jsm:atob"),
        ("btoa", "t -> string -> string", "jsm:btoa"),
        ("focus", "t -> unit", "jsm:focus"),
        ("blur", "t -> unit", "jsm:blur"),
        ("print", "t -> unit", "jsm:print"),
        ("close", "t -> unit", "jsm:close"),
        ("on_click", "t -> (MouseEvent.t -> unit) -> unit", "jse:click"),
        ("on_dblclick", "t -> (MouseEvent.t -> unit) -> unit", "jse:dblclick"),
        ("on_mousedown", "t -> (MouseEvent.t -> unit) -> unit", "jse:mousedown"),
        ("on_mouseup", "t -> (MouseEvent.t -> unit) -> unit", "jse:mouseup"),
        ("on_mousemove", "t -> (MouseEvent.t -> unit) -> unit", "jse:mousemove"),
        ("on_mouseover", "t -> (MouseEvent.t -> unit) -> unit", "jse:mouseover"),
        ("on_mouseout", "t -> (MouseEvent.t -> unit) -> unit", "jse:mouseout"),
        ("on_keydown", "t -> (KeyboardEvent.t -> unit) -> unit", "jse:keydown"),
        ("on_keyup", "t -> (KeyboardEvent.t -> unit) -> unit", "jse:keyup"),
        ("on_keypress", "t -> (KeyboardEvent.t -> unit) -> unit", "jse:keypress"),
        ("on_input", "t -> (InputEvent.t -> unit) -> unit", "jse:input"),
        ("on_change", "t -> (Event.t -> unit) -> unit", "jse:change"),
        ("on_focus", "t -> (FocusEvent.t -> unit) -> unit", "jse:focus"),
        ("on_blur", "t -> (FocusEvent.t -> unit) -> unit", "jse:blur"),
        ("on_wheel", "t -> (WheelEvent.t -> unit) -> unit", "jse:wheel"),
        ("on_scroll", "t -> (Event.t -> unit) -> unit", "jse:scroll"),
        ("on_resize", "t -> (UiEvent.t -> unit) -> unit", "jse:resize"),
        ("on_load", "t -> (Event.t -> unit) -> unit", "jse:load"),
        ("on_unload", "t -> (Event.t -> unit) -> unit", "jse:unload"),
        ("on_error", "t -> (Event.t -> unit) -> unit", "jse:error"),
        ("on_message", "t -> (MessageEvent.t -> unit) -> unit", "jse:message"),
        ("on_pointerdown", "t -> (PointerEvent.t -> unit) -> unit", "jse:pointerdown"),
        ("on_pointerup", "t -> (PointerEvent.t -> unit) -> unit", "jse:pointerup"),
        ("on_pointermove", "t -> (PointerEvent.t -> unit) -> unit", "jse:pointermove"),
        ("on_touchstart", "t -> (TouchEvent.t -> unit) -> unit", "jse:touchstart"),
        ("on_touchend", "t -> (TouchEvent.t -> unit) -> unit", "jse:touchend"),
        ("on_touchmove", "t -> (TouchEvent.t -> unit) -> unit", "jse:touchmove"),
        ("on_submit", "t -> (SubmitEvent.t -> unit) -> unit", "jse:submit"),
        ("local_storage", "t -> Storage.t", "jsgp:localStorage"),
        ("session_storage", "t -> Storage.t", "jsgp:sessionStorage"),
        ("crypto", "t -> Crypto.t", "jsgp:crypto"),
        ("request_idle_callback", "t -> (Js.t -> unit) -> int", "jsm:requestIdleCallback"),
        ("cancel_idle_callback", "t -> int -> unit", "jsm:cancelIdleCallback"),
        ("get_selection", "t -> Selection.t", "jsm:getSelection"),
        ("scroll_to", "t -> float -> float -> unit", "jsm:scrollTo"),
        ("scroll_by", "t -> float -> float -> unit", "jsm:scrollBy"),
        ("post_message", "t -> Js.t -> string -> unit", "jsm:postMessage"),
        ("open_", "t -> string -> string -> string -> t", "jsm:open"),
        ("audio_context", "t -> AudioContext.t", "jsnew0:AudioContext"),
        ("dispatch_event", "t -> Event.t -> bool", "jsm:dispatchEvent"),
    ]),
    M("Console", [
        ("log", "string -> unit", "js:console.log"),
        ("error", "string -> unit", "js:console.error"),
        ("warn", "string -> unit", "js:console.warn"),
        ("info", "string -> unit", "js:console.info"),
        ("debug", "string -> unit", "js:console.debug"),
        ("assert_", "bool -> string -> unit", "js:console.assert"),
    ], "t = Js.t"),
    M("Math", [
        ("max", "float -> float -> float", "js:Math.max"),
        ("min", "float -> float -> float", "js:Math.min"),
        ("abs", "float -> float", "js:Math.abs"),
        ("sqrt", "float -> float", "js:Math.sqrt"),
        ("cbrt", "float -> float", "js:Math.cbrt"),
        ("pow", "float -> float -> float", "js:Math.pow"),
        ("floor", "float -> float", "js:Math.floor"),
        ("ceil", "float -> float", "js:Math.ceil"),
        ("round", "float -> float", "js:Math.round"),
        ("trunc", "float -> float", "js:Math.trunc"),
        ("log", "float -> float", "js:Math.log"),
        ("log2", "float -> float", "js:Math.log2"),
        ("log10", "float -> float", "js:Math.log10"),
        ("exp", "float -> float", "js:Math.exp"),
        ("sin", "float -> float", "js:Math.sin"),
        ("cos", "float -> float", "js:Math.cos"),
        ("tan", "float -> float", "js:Math.tan"),
        ("atan2", "float -> float -> float", "js:Math.atan2"),
        ("hypot", "float -> float -> float", "js:Math.hypot"),
        ("sign", "float -> float", "js:Math.sign"),
        ("random", "unit -> float", "js0:Math.random"),
        ("pi", "unit -> float", "jsget:Math.PI"),
        ("e", "unit -> float", "jsget:Math.E"),
        ("ln2", "unit -> float", "jsget:Math.LN2"),
        ("ln10", "unit -> float", "jsget:Math.LN10"),
        ("sqrt2", "unit -> float", "jsget:Math.SQRT2"),
    ], "", ""),
    M("JsGlobal", [
        ("parse_int", "string -> int", "js:parseInt"),
        ("parse_float", "string -> float", "js:parseFloat"),
        ("is_nan", "float -> bool", "js:isNaN"),
        ("is_finite", "float -> bool", "js:isFinite"),
        ("encode_uri", "string -> string", "js:encodeURI"),
        ("decode_uri", "string -> string", "js:decodeURI"),
        ("encode_uri_component", "string -> string", "js:encodeURIComponent"),
        ("decode_uri_component", "string -> string", "js:decodeURIComponent"),
        ("fetch", "string -> Promise.t", "js:fetch"),
        ("queue_microtask", "(unit -> unit) -> unit", "js:queueMicrotask"),
        ("structured_clone", "Js.t -> Js.t", "js:structuredClone"),
    ], "", ""),
    M("Timers", [
        ("set_timeout", "(unit -> unit) -> int -> int", "js:setTimeout"),
        ("clear_timeout", "int -> unit", "js:clearTimeout"),
        ("set_interval", "(unit -> unit) -> int -> int", "js:setInterval"),
        ("clear_interval", "int -> unit", "js:clearInterval"),
        ("request_animation_frame", "(float -> unit) -> int", "js:requestAnimationFrame"),
        ("cancel_animation_frame", "int -> unit", "js:cancelAnimationFrame"),
    ], "", ""),
    M("HtmlAnchorElement", [
        ("href", "t -> string", "jsgp:href"),
        ("set_href", "t -> string -> unit", "jssp:href"),
        ("target", "t -> string", "jsgp:target"),
        ("set_target", "t -> string -> unit", "jssp:target"),
        ("rel", "t -> string", "jsgp:rel"),
        ("set_rel", "t -> string -> unit", "jssp:rel"),
        ("download", "t -> string", "jsgp:download"),
        ("set_download", "t -> string -> unit", "jssp:download"),
        ("host", "t -> string", "jsgp:host"),
        ("hostname", "t -> string", "jsgp:hostname"),
        ("pathname", "t -> string", "jsgp:pathname"),
        ("search", "t -> string", "jsgp:search"),
        ("hash", "t -> string", "jsgp:hash"),
        ("protocol", "t -> string", "jsgp:protocol"),
        ("origin", "t -> string", "jsgp:origin"),
        ("text", "t -> string", "jsgp:text"),
        ("set_text", "t -> string -> unit", "jssp:text"),
    ], "t = Node.t"),
    M("HtmlButtonElement", [
        ("disabled", "t -> bool", "jsgp:disabled"),
        ("set_disabled", "t -> bool -> unit", "jssp:disabled"),
        ("button_type", "t -> string", "jsgp:type"),
        ("set_button_type", "t -> string -> unit", "jssp:type"),
        ("value", "t -> string", "jsgp:value"),
        ("set_value", "t -> string -> unit", "jssp:value"),
        ("name", "t -> string", "jsgp:name"),
        ("form", "t -> t", "jsgp:form"),
        ("click", "t -> unit", "jsm:click"),
        ("check_validity", "t -> bool", "jsm:checkValidity"),
        ("report_validity", "t -> bool", "jsm:reportValidity"),
    ], "t = Node.t"),
    M("HtmlTextAreaElement", [
        ("value", "t -> string", "jsgp:value"),
        ("set_value", "t -> string -> unit", "jssp:value"),
        ("placeholder", "t -> string", "jsgp:placeholder"),
        ("set_placeholder", "t -> string -> unit", "jssp:placeholder"),
        ("rows", "t -> int", "jsgp:rows"),
        ("set_rows", "t -> int -> unit", "jssp:rows"),
        ("cols", "t -> int", "jsgp:cols"),
        ("set_cols", "t -> int -> unit", "jssp:cols"),
        ("disabled", "t -> bool", "jsgp:disabled"),
        ("read_only", "t -> bool", "jsgp:readOnly"),
        ("select", "t -> unit", "jsm:select"),
        ("set_selection_range", "t -> int -> int -> unit", "jsm:setSelectionRange"),
    ], "t = Node.t"),
    M("HtmlFormElement", [
        ("action", "t -> string", "jsgp:action"),
        ("set_action", "t -> string -> unit", "jssp:action"),
        ("method", "t -> string", "jsgp:method"),
        ("set_method", "t -> string -> unit", "jssp:method"),
        ("name", "t -> string", "jsgp:name"),
        ("elements", "t -> t", "jsgp:elements"),
        ("length", "t -> int", "jsgp:length"),
        ("no_validate", "t -> bool", "jsgp:noValidate"),
        ("set_no_validate", "t -> bool -> unit", "jssp:noValidate"),
        ("submit", "t -> unit", "jsm:submit"),
        ("reset", "t -> unit", "jsm:reset"),
        ("check_validity", "t -> bool", "jsm:checkValidity"),
        ("report_validity", "t -> bool", "jsm:reportValidity"),
    ], "t = Node.t"),
    M("HtmlSelectElement", [
        ("value", "t -> string", "jsgp:value"),
        ("set_value", "t -> string -> unit", "jssp:value"),
        ("selected_index", "t -> int", "jsgp:selectedIndex"),
        ("set_selected_index", "t -> int -> unit", "jssp:selectedIndex"),
        ("options", "t -> t", "jsgp:options"),
        ("length", "t -> int", "jsgp:length"),
        ("multiple", "t -> bool", "jsgp:multiple"),
        ("set_multiple", "t -> bool -> unit", "jssp:multiple"),
        ("disabled", "t -> bool", "jsgp:disabled"),
        ("name", "t -> string", "jsgp:name"),
        ("item", "t -> int -> t", "jsm:item"),
        ("add", "t -> t -> unit", "jsm:add"),
        ("remove_", "t -> int -> unit", "jsm:remove"),
    ], "t = Node.t"),
    M("HtmlOptionElement", [
        ("value", "t -> string", "jsgp:value"),
        ("set_value", "t -> string -> unit", "jssp:value"),
        ("text", "t -> string", "jsgp:text"),
        ("set_text", "t -> string -> unit", "jssp:text"),
        ("selected", "t -> bool", "jsgp:selected"),
        ("set_selected", "t -> bool -> unit", "jssp:selected"),
        ("disabled", "t -> bool", "jsgp:disabled"),
        ("label", "t -> string", "jsgp:label"),
    ], "t = Node.t"),
    M("HtmlOptGroupElement", [
        ("label", "t -> string", "jsgp:label"),
        ("set_label", "t -> string -> unit", "jssp:label"),
        ("disabled", "t -> bool", "jsgp:disabled"),
    ], "t = Node.t"),
    M("HtmlLabelElement", [
        ("html_for", "t -> string", "jsgp:htmlFor"),
        ("set_html_for", "t -> string -> unit", "jssp:htmlFor"),
        ("control", "t -> t", "jsgp:control"),
    ], "t = Node.t"),
    M("HtmlMediaElement", [
        ("src", "t -> string", "jsgp:src"),
        ("set_src", "t -> string -> unit", "jssp:src"),
        ("current_time", "t -> float", "jsgp:currentTime"),
        ("set_current_time", "t -> float -> unit", "jssp:currentTime"),
        ("duration", "t -> float", "jsgp:duration"),
        ("paused", "t -> bool", "jsgp:paused"),
        ("ended", "t -> bool", "jsgp:ended"),
        ("volume", "t -> float", "jsgp:volume"),
        ("set_volume", "t -> float -> unit", "jssp:volume"),
        ("muted", "t -> bool", "jsgp:muted"),
        ("set_muted", "t -> bool -> unit", "jssp:muted"),
        ("loop", "t -> bool", "jsgp:loop"),
        ("set_loop", "t -> bool -> unit", "jssp:loop"),
        ("autoplay", "t -> bool", "jsgp:autoplay"),
        ("set_autoplay", "t -> bool -> unit", "jssp:autoplay"),
        ("controls", "t -> bool", "jsgp:controls"),
        ("set_controls", "t -> bool -> unit", "jssp:controls"),
        ("play", "t -> t", "jsm:play"),
        ("pause", "t -> unit", "jsm:pause"),
        ("load", "t -> unit", "jsm:load"),
        ("can_play_type", "t -> string -> string", "jsm:canPlayType"),
    ], "t = Node.t"),
    M("HtmlVideoElement", [
        ("width", "t -> int", "jsgp:width"),
        ("set_width", "t -> int -> unit", "jssp:width"),
        ("height", "t -> int", "jsgp:height"),
        ("set_height", "t -> int -> unit", "jssp:height"),
        ("video_width", "t -> int", "jsgp:videoWidth"),
        ("video_height", "t -> int", "jsgp:videoHeight"),
        ("poster", "t -> string", "jsgp:poster"),
        ("set_poster", "t -> string -> unit", "jssp:poster"),
    ], "t = Node.t"),
    M("HtmlAudioElement", [
        ("audio", "unit -> t", "jsnew0:Audio"),
    ], "t = Node.t"),
    M("HtmlSourceElement", [
        ("src", "t -> string", "jsgp:src"),
        ("set_src", "t -> string -> unit", "jssp:src"),
        ("source_type", "t -> string", "jsgp:type"),
        ("set_source_type", "t -> string -> unit", "jssp:type"),
    ], "t = Node.t"),
    M("HtmlTableElement", [
        ("caption", "t -> t", "jsgp:caption"),
        ("t_head", "t -> t", "jsgp:tHead"),
        ("t_body", "t -> t", "jsgp:tBodies"),
        ("t_foot", "t -> t", "jsgp:tFoot"),
        ("rows", "t -> t", "jsgp:rows"),
        ("insert_row", "t -> int -> t", "jsm:insertRow"),
        ("delete_row", "t -> int -> unit", "jsm:deleteRow"),
        ("create_t_head", "t -> t", "jsm:createTHead"),
        ("create_t_body", "t -> t", "jsm:createTBody"),
        ("create_t_foot", "t -> t", "jsm:createTFoot"),
    ], "t = Node.t"),
    M("HtmlTableRowElement", [
        ("row_index", "t -> int", "jsgp:rowIndex"),
        ("section_row_index", "t -> int", "jsgp:sectionRowIndex"),
        ("cells", "t -> t", "jsgp:cells"),
        ("insert_cell", "t -> int -> t", "jsm:insertCell"),
        ("delete_cell", "t -> int -> unit", "jsm:deleteCell"),
    ], "t = Node.t"),
    M("HtmlTableCellElement", [
        ("cell_index", "t -> int", "jsgp:cellIndex"),
        ("col_span", "t -> int", "jsgp:colSpan"),
        ("set_col_span", "t -> int -> unit", "jssp:colSpan"),
        ("row_span", "t -> int", "jsgp:rowSpan"),
        ("set_row_span", "t -> int -> unit", "jssp:rowSpan"),
        ("abbr", "t -> string", "jsgp:abbr"),
    ], "t = Node.t"),
    M("HtmlIFrameElement", [
        ("src", "t -> string", "jsgp:src"),
        ("set_src", "t -> string -> unit", "jssp:src"),
        ("width", "t -> string", "jsgp:width"),
        ("height", "t -> string", "jsgp:height"),
        ("name", "t -> string", "jsgp:name"),
        ("content_window", "t -> t", "jsgp:contentWindow"),
        ("content_document", "t -> t", "jsgp:contentDocument"),
        ("allow", "t -> string", "jsgp:allow"),
        ("srcdoc", "t -> string", "jsgp:srcdoc"),
    ], "t = Node.t"),
    M("HtmlScriptElement", [
        ("src", "t -> string", "jsgp:src"),
        ("set_src", "t -> string -> unit", "jssp:src"),
        ("script_type", "t -> string", "jsgp:type"),
        ("set_script_type", "t -> string -> unit", "jssp:type"),
        ("async", "t -> bool", "jsgp:async"),
        ("set_async", "t -> bool -> unit", "jssp:async"),
        ("defer", "t -> bool", "jsgp:defer"),
        ("set_defer", "t -> bool -> unit", "jssp:defer"),
        ("text", "t -> string", "jsgp:text"),
        ("set_text", "t -> string -> unit", "jssp:text"),
        ("cross_origin", "t -> string", "jsgp:crossOrigin"),
        ("integrity", "t -> string", "jsgp:integrity"),
    ], "t = Node.t"),
    M("HtmlStyleElement", [
        ("media", "t -> string", "jsgp:media"),
        ("set_media", "t -> string -> unit", "jssp:media"),
        ("disabled", "t -> bool", "jsgp:disabled"),
        ("set_disabled", "t -> bool -> unit", "jssp:disabled"),
        ("sheet", "t -> t", "jsgp:sheet"),
    ], "t = Node.t"),
    M("HtmlLinkElement", [
        ("href", "t -> string", "jsgp:href"),
        ("set_href", "t -> string -> unit", "jssp:href"),
        ("rel", "t -> string", "jsgp:rel"),
        ("set_rel", "t -> string -> unit", "jssp:rel"),
        ("link_type", "t -> string", "jsgp:type"),
        ("media", "t -> string", "jsgp:media"),
        ("set_media", "t -> string -> unit", "jssp:media"),
        ("disabled", "t -> bool", "jsgp:disabled"),
        ("sheet", "t -> t", "jsgp:sheet"),
    ], "t = Node.t"),
    M("HtmlMetaElement", [
        ("name", "t -> string", "jsgp:name"),
        ("set_name", "t -> string -> unit", "jssp:name"),
        ("content", "t -> string", "jsgp:content"),
        ("set_content", "t -> string -> unit", "jssp:content"),
        ("http_equiv", "t -> string", "jsgp:httpEquiv"),
        ("charset", "t -> string", "jsgp:charset"),
    ], "t = Node.t"),
    M("HtmlTitleElement", [
        ("text", "t -> string", "jsgp:text"),
        ("set_text", "t -> string -> unit", "jssp:text"),
    ], "t = Node.t"),
    M("HtmlTemplateElement", [
        ("content", "t -> t", "jsgp:content"),
    ], "t = Node.t"),
    M("HtmlDialogElement", [
        ("open", "t -> bool", "jsgp:open"),
        ("set_open", "t -> bool -> unit", "jssp:open"),
        ("return_value", "t -> string", "jsgp:returnValue"),
        ("show", "t -> unit", "jsm:show"),
        ("show_modal", "t -> unit", "jsm:showModal"),
        ("close", "t -> string -> unit", "jsm:close"),
    ], "t = Node.t"),
    M("HtmlDetailsElement", [
        ("open", "t -> bool", "jsgp:open"),
        ("set_open", "t -> bool -> unit", "jssp:open"),
    ], "t = Node.t"),
    M("HtmlProgressElement", [
        ("value", "t -> float", "jsgp:value"),
        ("set_value", "t -> float -> unit", "jssp:value"),
        ("max", "t -> float", "jsgp:max"),
        ("set_max", "t -> float -> unit", "jssp:max"),
        ("position", "t -> float", "jsgp:position"),
    ], "t = Node.t"),
    M("Storage", [
        ("length", "t -> int", "jsgp:length"),
        ("get_item", "t -> string -> Js.t", "jsm:getItem"),
        ("set_item", "t -> string -> string -> unit", "jsm:setItem"),
        ("remove_item", "t -> string -> unit", "jsm:removeItem"),
        ("clear", "t -> unit", "jsm:clear"),
        ("key", "t -> int -> Js.t", "jsm:key"),
    ]),
    M("CanvasRenderingContext2D", [
        ("canvas", "t -> t", "jsgp:canvas"),
        ("fill_style", "t -> string", "jsgp:fillStyle"),
        ("set_fill_style", "t -> string -> unit", "jssp:fillStyle"),
        ("stroke_style", "t -> string", "jsgp:strokeStyle"),
        ("set_stroke_style", "t -> string -> unit", "jssp:strokeStyle"),
        ("line_width", "t -> float", "jsgp:lineWidth"),
        ("set_line_width", "t -> float -> unit", "jssp:lineWidth"),
        ("global_alpha", "t -> float", "jsgp:globalAlpha"),
        ("set_global_alpha", "t -> float -> unit", "jssp:globalAlpha"),
        ("font", "t -> string", "jsgp:font"),
        ("set_font", "t -> string -> unit", "jssp:font"),
        ("text_align", "t -> string", "jsgp:textAlign"),
        ("set_text_align", "t -> string -> unit", "jssp:textAlign"),
        ("fill_rect", "t -> float -> float -> float -> float -> unit", "jsm:fillRect"),
        ("stroke_rect", "t -> float -> float -> float -> float -> unit", "jsm:strokeRect"),
        ("clear_rect", "t -> float -> float -> float -> float -> unit", "jsm:clearRect"),
        ("begin_path", "t -> unit", "jsm:beginPath"),
        ("close_path", "t -> unit", "jsm:closePath"),
        ("move_to", "t -> float -> float -> unit", "jsm:moveTo"),
        ("line_to", "t -> float -> float -> unit", "jsm:lineTo"),
        ("arc", "t -> float -> float -> float -> float -> float -> bool -> unit", "jsm:arc"),
        ("rect", "t -> float -> float -> float -> float -> unit", "jsm:rect"),
        ("fill", "t -> unit", "jsm:fill"),
        ("stroke", "t -> unit", "jsm:stroke"),
        ("clip", "t -> unit", "jsm:clip"),
        ("fill_text", "t -> string -> float -> float -> unit", "jsm:fillText"),
        ("stroke_text", "t -> string -> float -> float -> unit", "jsm:strokeText"),
        ("draw_image", "t -> t -> float -> float -> unit", "jsm:drawImage"),
        ("save", "t -> unit", "jsm:save"),
        ("restore", "t -> unit", "jsm:restore"),
        ("translate", "t -> float -> float -> unit", "jsm:translate"),
        ("rotate", "t -> float -> unit", "jsm:rotate"),
        ("scale", "t -> float -> float -> unit", "jsm:scale"),
        ("create_linear_gradient", "t -> float -> float -> float -> float -> t", "jsm:createLinearGradient"),
        ("get_image_data", "t -> int -> int -> int -> int -> t", "jsm:getImageData"),
        ("measure_text", "t -> string -> t", "jsm:measureText"),
    ]),
    M("Headers", [
        ("create", "unit -> t", "jsnew0:Headers"),
        ("append", "t -> string -> string -> unit", "jsm:append"),
        ("delete", "t -> string -> unit", "jsm:delete"),
        ("get", "t -> string -> Js.t", "jsm:get"),
        ("has", "t -> string -> bool", "jsm:has"),
        ("set", "t -> string -> string -> unit", "jsm:set"),
        ("for_each", "t -> (string -> string -> unit) -> unit", "jsm:forEach"),
    ]),
    M("Request", [
        ("create", "string -> t", "jsnew:Request"),
        ("url", "t -> string", "jsgp:url"),
        ("method", "t -> string", "jsgp:method"),
        ("headers", "t -> Headers.t", "jsgp:headers"),
        ("body_used", "t -> bool", "jsgp:bodyUsed"),
        ("mode", "t -> string", "jsgp:mode"),
        ("credentials", "t -> string", "jsgp:credentials"),
        ("text", "t -> Promise.t", "jsm:text"),
        ("json", "t -> Promise.t", "jsm:json"),
    ]),
    M("Response", [
        ("create", "unit -> t", "jsnew0:Response"),
        ("ok", "t -> bool", "jsgp:ok"),
        ("status", "t -> int", "jsgp:status"),
        ("status_text", "t -> string", "jsgp:statusText"),
        ("headers", "t -> Headers.t", "jsgp:headers"),
        ("url", "t -> string", "jsgp:url"),
        ("redirected", "t -> bool", "jsgp:redirected"),
        ("response_type", "t -> string", "jsgp:type"),
        ("body_used", "t -> bool", "jsgp:bodyUsed"),
        ("text", "t -> Promise.t", "jsm:text"),
        ("json", "t -> Promise.t", "jsm:json"),
        ("clone", "t -> t", "jsm:clone"),
    ]),
    M("XmlHttpRequest", [
        ("create", "unit -> t", "jsnew0:XMLHttpRequest"),
        ("open", "t -> string -> string -> unit", "jsm:open"),
        ("send", "t -> unit", "jsm:send"),
        ("abort", "t -> unit", "jsm:abort"),
        ("set_request_header", "t -> string -> string -> unit", "jsm:setRequestHeader"),
        ("get_response_header", "t -> string -> Js.t", "jsm:getResponseHeader"),
        ("get_all_response_headers", "t -> string", "jsm:getAllResponseHeaders"),
        ("ready_state", "t -> int", "jsgp:readyState"),
        ("status", "t -> int", "jsgp:status"),
        ("status_text", "t -> string", "jsgp:statusText"),
        ("response", "t -> Js.t", "jsgp:response"),
        ("response_text", "t -> string", "jsgp:responseText"),
        ("response_type", "t -> string", "jsgp:responseType"),
        ("set_response_type", "t -> string -> unit", "jssp:responseType"),
        ("with_credentials", "t -> bool", "jsgp:withCredentials"),
        ("set_with_credentials", "t -> bool -> unit", "jssp:withCredentials"),
        ("on_load", "t -> (Event.t -> unit) -> unit", "jse:load"),
        ("on_error", "t -> (Event.t -> unit) -> unit", "jse:error"),
        ("on_progress", "t -> (ProgressEvent.t -> unit) -> unit", "jse:progress"),
        ("on_ready_state_change", "t -> (Event.t -> unit) -> unit", "jse:readystatechange"),
    ]),
    M("WebSocket", [
        ("create", "string -> t", "jsnew:WebSocket"),
        ("send", "t -> string -> unit", "jsm:send"),
        ("close", "t -> unit", "jsm:close"),
        ("ready_state", "t -> int", "jsgp:readyState"),
        ("url", "t -> string", "jsgp:url"),
        ("protocol", "t -> string", "jsgp:protocol"),
        ("buffered_amount", "t -> int", "jsgp:bufferedAmount"),
        ("on_open", "t -> (Event.t -> unit) -> unit", "jse:open"),
        ("on_message", "t -> (MessageEvent.t -> unit) -> unit", "jse:message"),
        ("on_error", "t -> (Event.t -> unit) -> unit", "jse:error"),
        ("on_close", "t -> (Event.t -> unit) -> unit", "jse:close"),
    ]),
    M("EventSource", [
        ("create", "string -> t", "jsnew:EventSource"),
        ("close", "t -> unit", "jsm:close"),
        ("ready_state", "t -> int", "jsgp:readyState"),
        ("url", "t -> string", "jsgp:url"),
        ("with_credentials", "t -> bool", "jsgp:withCredentials"),
        ("on_open", "t -> (Event.t -> unit) -> unit", "jse:open"),
        ("on_message", "t -> (MessageEvent.t -> unit) -> unit", "jse:message"),
        ("on_error", "t -> (Event.t -> unit) -> unit", "jse:error"),
    ]),
    M("UrlSearchParams", [
        ("create", "unit -> t", "jsnew0:URLSearchParams"),
        ("append", "t -> string -> string -> unit", "jsm:append"),
        ("delete", "t -> string -> unit", "jsm:delete"),
        ("get", "t -> string -> Js.t", "jsm:get"),
        ("get_all", "t -> string -> Js.t", "jsm:getAll"),
        ("has", "t -> string -> bool", "jsm:has"),
        ("set", "t -> string -> string -> unit", "jsm:set"),
        ("sort", "t -> unit", "jsm:sort"),
        ("to_string", "t -> string", "jsm:toString"),
    ]),
    M("Url", [
        ("create", "string -> t", "jsnew:URL"),
        ("href", "t -> string", "jsgp:href"),
        ("protocol", "t -> string", "jsgp:protocol"),
        ("host", "t -> string", "jsgp:host"),
        ("hostname", "t -> string", "jsgp:hostname"),
        ("port", "t -> string", "jsgp:port"),
        ("pathname", "t -> string", "jsgp:pathname"),
        ("search", "t -> string", "jsgp:search"),
        ("hash", "t -> string", "jsgp:hash"),
        ("origin", "t -> string", "jsgp:origin"),
        ("search_params", "t -> UrlSearchParams.t", "jsgp:searchParams"),
        ("to_string", "t -> string", "jsm:toString"),
    ]),
    M("MutationObserver", [
        ("create", "(Js.t -> unit) -> t", "jsnew:MutationObserver"),
        ("observe", "t -> t -> t -> unit", "jsm:observe"),
        ("disconnect", "t -> unit", "jsm:disconnect"),
        ("take_records", "t -> Js.t", "jsm:takeRecords"),
    ]),
    M("IntersectionObserver", [
        ("create", "(Js.t -> unit) -> t", "jsnew:IntersectionObserver"),
        ("observe", "t -> t -> unit", "jsm:observe"),
        ("unobserve", "t -> t -> unit", "jsm:unobserve"),
        ("disconnect", "t -> unit", "jsm:disconnect"),
        ("take_records", "t -> Js.t", "jsm:takeRecords"),
        ("root", "t -> t", "jsgp:root"),
        ("root_margin", "t -> string", "jsgp:rootMargin"),
    ]),
    M("ResizeObserver", [
        ("create", "(Js.t -> unit) -> t", "jsnew:ResizeObserver"),
        ("observe", "t -> t -> unit", "jsm:observe"),
        ("unobserve", "t -> t -> unit", "jsm:unobserve"),
        ("disconnect", "t -> unit", "jsm:disconnect"),
    ]),
    M("Crypto", [
        ("get_random_values", "t -> t -> t", "jsm:getRandomValues"),
        ("random_uuid", "t -> string", "jsm:randomUUID"),
        ("subtle", "t -> t", "jsgp:subtle"),
    ]),
    M("DomRectReadOnly", [
        ("x", "t -> float", "jsgp:x"),
        ("y", "t -> float", "jsgp:y"),
        ("width", "t -> float", "jsgp:width"),
        ("height", "t -> float", "jsgp:height"),
        ("top", "t -> float", "jsgp:top"),
        ("right", "t -> float", "jsgp:right"),
        ("bottom", "t -> float", "jsgp:bottom"),
        ("left", "t -> float", "jsgp:left"),
        ("to_json", "t -> Js.t", "jsm:toJSON"),
    ]),
    M("DomRect", [
        ("create", "float -> float -> float -> float -> t", "jsnew:DOMRect"),
        ("x", "t -> float", "jsgp:x"),
        ("set_x", "t -> float -> unit", "jssp:x"),
        ("y", "t -> float", "jsgp:y"),
        ("set_y", "t -> float -> unit", "jssp:y"),
        ("width", "t -> float", "jsgp:width"),
        ("set_width", "t -> float -> unit", "jssp:width"),
        ("height", "t -> float", "jsgp:height"),
        ("set_height", "t -> float -> unit", "jssp:height"),
        ("top", "t -> float", "jsgp:top"),
        ("right", "t -> float", "jsgp:right"),
        ("bottom", "t -> float", "jsgp:bottom"),
        ("left", "t -> float", "jsgp:left"),
    ]),
    M("DomPoint", [
        ("create", "float -> float -> float -> float -> t", "jsnew:DOMPoint"),
        ("x", "t -> float", "jsgp:x"),
        ("set_x", "t -> float -> unit", "jssp:x"),
        ("y", "t -> float", "jsgp:y"),
        ("set_y", "t -> float -> unit", "jssp:y"),
        ("z", "t -> float", "jsgp:z"),
        ("w", "t -> float", "jsgp:w"),
        ("to_json", "t -> Js.t", "jsm:toJSON"),
    ]),
    M("DomMatrix", [
        ("create", "unit -> t", "jsnew0:DOMMatrix"),
        ("a", "t -> float", "jsgp:a"),
        ("b", "t -> float", "jsgp:b"),
        ("c", "t -> float", "jsgp:c"),
        ("d", "t -> float", "jsgp:d"),
        ("e", "t -> float", "jsgp:e"),
        ("f", "t -> float", "jsgp:f"),
        ("translate", "t -> float -> float -> t", "jsm:translate"),
        ("scale", "t -> float -> t", "jsm:scale"),
        ("rotate", "t -> float -> t", "jsm:rotate"),
        ("multiply", "t -> t -> t", "jsm:multiply"),
        ("inverse", "t -> t", "jsm:inverse"),
        ("to_string", "t -> string", "jsm:toString"),
    ]),
    M("CanvasGradient", [
        ("add_color_stop", "t -> float -> string -> unit", "jsm:addColorStop"),
    ]),
    M("CanvasPattern", []),
    M("ImageData", [
        ("create", "int -> int -> t", "jsnew:ImageData"),
        ("width", "t -> int", "jsgp:width"),
        ("height", "t -> int", "jsgp:height"),
        ("data", "t -> t", "jsgp:data"),
    ]),
    M("TextMetrics", [
        ("width", "t -> float", "jsgp:width"),
        ("actual_bounding_box_left", "t -> float", "jsgp:actualBoundingBoxLeft"),
        ("actual_bounding_box_right", "t -> float", "jsgp:actualBoundingBoxRight"),
        ("font_bounding_box_ascent", "t -> float", "jsgp:fontBoundingBoxAscent"),
        ("font_bounding_box_descent", "t -> float", "jsgp:fontBoundingBoxDescent"),
    ]),
    M("Path2D", [
        ("create", "unit -> t", "jsnew0:Path2D"),
        ("move_to", "t -> float -> float -> unit", "jsm:moveTo"),
        ("line_to", "t -> float -> float -> unit", "jsm:lineTo"),
        ("arc", "t -> float -> float -> float -> float -> float -> bool -> unit", "jsm:arc"),
        ("rect", "t -> float -> float -> float -> float -> unit", "jsm:rect"),
        ("close_path", "t -> unit", "jsm:closePath"),
        ("add_path", "t -> t -> unit", "jsm:addPath"),
    ]),
    M("OffscreenCanvas", [
        ("create", "int -> int -> t", "jsnew:OffscreenCanvas"),
        ("width", "t -> int", "jsgp:width"),
        ("set_width", "t -> int -> unit", "jssp:width"),
        ("height", "t -> int", "jsgp:height"),
        ("set_height", "t -> int -> unit", "jssp:height"),
        ("get_context", "t -> string -> CanvasRenderingContext2D.t", "jsm:getContext"),
        ("transfer_to_image_bitmap", "t -> Js.t", "jsm:transferToImageBitmap"),
    ]),
    M("Blob", [
        ("create", "Js.t -> Js.t -> t", "jsnew:Blob"),
        ("size", "t -> float", "jsgp:size"),
        ("blob_type", "t -> string", "jsgp:type"),
        ("slice", "t -> int -> int -> string -> t", "jsm:slice"),
        ("text", "t -> Promise.t", "jsm:text"),
        ("array_buffer", "t -> Promise.t", "jsm:arrayBuffer"),
    ]),
    M("File", [
        ("create", "Js.t -> string -> Js.t -> t", "jsnew:File"),
        ("name", "t -> string", "jsgp:name"),
        ("last_modified", "t -> float", "jsgp:lastModified"),
        ("size", "t -> float", "jsgp:size"),
        ("file_type", "t -> string", "jsgp:type"),
        ("slice", "t -> int -> int -> string -> t", "jsm:slice"),
        ("text", "t -> Promise.t", "jsm:text"),
    ]),
    M("FileList", [
        ("length", "t -> int", "jsgp:length"),
        ("item", "t -> int -> File.t", "jsm:item"),
    ]),
    M("FileReader", [
        ("create", "unit -> t", "jsnew0:FileReader"),
        ("read_as_text", "t -> Blob.t -> unit", "jsm:readAsText"),
        ("read_as_data_url", "t -> Blob.t -> unit", "jsm:readAsDataURL"),
        ("read_as_array_buffer", "t -> Blob.t -> unit", "jsm:readAsArrayBuffer"),
        ("abort", "t -> unit", "jsm:abort"),
        ("result", "t -> Js.t", "jsgp:result"),
        ("error", "t -> Js.t", "jsgp:error"),
        ("ready_state", "t -> int", "jsgp:readyState"),
        ("on_load", "t -> (Event.t -> unit) -> unit", "jse:load"),
        ("on_error", "t -> (Event.t -> unit) -> unit", "jse:error"),
        ("on_progress", "t -> (ProgressEvent.t -> unit) -> unit", "jse:progress"),
    ]),
    M("FormData", [
        ("create", "unit -> t", "jsnew0:FormData"),
        ("append", "t -> string -> Js.t -> unit", "jsm:append"),
        ("delete", "t -> string -> unit", "jsm:delete"),
        ("get", "t -> string -> Js.t", "jsm:get"),
        ("get_all", "t -> string -> Js.t", "jsm:getAll"),
        ("has", "t -> string -> bool", "jsm:has"),
        ("set", "t -> string -> Js.t -> unit", "jsm:set"),
    ]),
    M("Worker", [
        ("create", "string -> t", "jsnew:Worker"),
        ("post_message", "t -> Js.t -> unit", "jsm:postMessage"),
        ("terminate", "t -> unit", "jsm:terminate"),
        ("on_message", "t -> (MessageEvent.t -> unit) -> unit", "jse:message"),
        ("on_error", "t -> (Event.t -> unit) -> unit", "jse:error"),
        ("on_messageerror", "t -> (Event.t -> unit) -> unit", "jse:messageerror"),
    ]),
    M("MessagePort", [
        ("post_message", "t -> Js.t -> unit", "jsm:postMessage"),
        ("start", "t -> unit", "jsm:start"),
        ("close", "t -> unit", "jsm:close"),
        ("on_message", "t -> (MessageEvent.t -> unit) -> unit", "jse:message"),
    ]),
    M("MessageChannel", [
        ("create", "unit -> t", "jsnew0:MessageChannel"),
        ("port1", "t -> MessagePort.t", "jsgp:port1"),
        ("port2", "t -> MessagePort.t", "jsgp:port2"),
    ]),
    M("BroadcastChannel", [
        ("create", "string -> t", "jsnew:BroadcastChannel"),
        ("name", "t -> string", "jsgp:name"),
        ("post_message", "t -> Js.t -> unit", "jsm:postMessage"),
        ("close", "t -> unit", "jsm:close"),
        ("on_message", "t -> (MessageEvent.t -> unit) -> unit", "jse:message"),
    ]),
    M("CustomEvent", [
        ("create", "string -> t", "jsnew:CustomEvent"),
        ("detail", "t -> Js.t", "jsgp:detail"),
    ]),
    M("ErrorEvent", [
        ("message", "t -> string", "jsgp:message"),
        ("filename", "t -> string", "jsgp:filename"),
        ("lineno", "t -> int", "jsgp:lineno"),
        ("colno", "t -> int", "jsgp:colno"),
        ("error", "t -> Js.t", "jsgp:error"),
    ]),
    M("PopStateEvent", [
        ("state", "t -> Js.t", "jsgp:state"),
    ]),
    M("HashChangeEvent", [
        ("old_url", "t -> string", "jsgp:oldURL"),
        ("new_url", "t -> string", "jsgp:newURL"),
    ]),
    M("StorageEvent", [
        ("key", "t -> Js.t", "jsgp:key"),
        ("old_value", "t -> Js.t", "jsgp:oldValue"),
        ("new_value", "t -> Js.t", "jsgp:newValue"),
        ("url", "t -> string", "jsgp:url"),
    ]),
    M("BeforeUnloadEvent", [
        ("return_value", "t -> string", "jsgp:returnValue"),
        ("set_return_value", "t -> string -> unit", "jssp:returnValue"),
    ]),
    M("AbortSignal", [
        ("aborted", "t -> bool", "jsgp:aborted"),
        ("reason", "t -> Js.t", "jsgp:reason"),
        ("throw_if_aborted", "t -> unit", "jsm:throwIfAborted"),
        ("on_abort", "t -> (Event.t -> unit) -> unit", "jse:abort"),
    ]),
    M("AbortController", [
        ("create", "unit -> t", "jsnew0:AbortController"),
        ("signal", "t -> AbortSignal.t", "jsgp:signal"),
        ("abort", "t -> Js.t -> unit", "jsm:abort"),
    ]),
    M("TextEncoder", [
        ("create", "unit -> t", "jsnew0:TextEncoder"),
        ("encoding", "t -> string", "jsgp:encoding"),
        ("encode", "t -> string -> t", "jsm:encode"),
    ]),
    M("TextDecoder", [
        ("create", "unit -> t", "jsnew0:TextDecoder"),
        ("encoding", "t -> string", "jsgp:encoding"),
        ("decode", "t -> t -> string", "jsm:decode"),
    ]),
    M("MediaDevices", [
        ("get_user_media", "t -> Js.t -> Promise.t", "jsm:getUserMedia"),
        ("get_display_media", "t -> Js.t -> Promise.t", "jsm:getDisplayMedia"),
        ("enumerate_devices", "t -> Promise.t", "jsm:enumerateDevices"),
    ]),
    M("MediaStreamTrack", [
        ("kind", "t -> string", "jsgp:kind"),
        ("id", "t -> string", "jsgp:id"),
        ("label", "t -> string", "jsgp:label"),
        ("enabled", "t -> bool", "jsgp:enabled"),
        ("set_enabled", "t -> bool -> unit", "jssp:enabled"),
        ("muted", "t -> bool", "jsgp:muted"),
        ("ready_state", "t -> string", "jsgp:readyState"),
        ("stop", "t -> unit", "jsm:stop"),
    ]),
    M("MediaStream", [
        ("create", "unit -> t", "jsnew0:MediaStream"),
        ("id", "t -> string", "jsgp:id"),
        ("active", "t -> bool", "jsgp:active"),
        ("get_tracks", "t -> Js.t", "jsm:getTracks"),
        ("get_audio_tracks", "t -> Js.t", "jsm:getAudioTracks"),
        ("get_video_tracks", "t -> Js.t", "jsm:getVideoTracks"),
        ("add_track", "t -> MediaStreamTrack.t -> unit", "jsm:addTrack"),
        ("remove_track", "t -> MediaStreamTrack.t -> unit", "jsm:removeTrack"),
    ]),
    M("AudioParam", [
        ("value", "t -> float", "jsgp:value"),
        ("set_value", "t -> float -> unit", "jssp:value"),
        ("set_value_at_time", "t -> float -> float -> t", "jsm:setValueAtTime"),
        ("linear_ramp_to_value_at_time", "t -> float -> float -> t", "jsm:linearRampToValueAtTime"),
    ]),
    M("AudioNode", [
        ("connect", "t -> t -> t", "jsm:connect"),
        ("disconnect", "t -> unit", "jsm:disconnect"),
        ("context", "t -> Js.t", "jsgp:context"),
        ("number_of_inputs", "t -> int", "jsgp:numberOfInputs"),
        ("number_of_outputs", "t -> int", "jsgp:numberOfOutputs"),
    ]),
    M("GainNode", [
        ("gain", "t -> AudioParam.t", "jsgp:gain"),
    ]),
    M("OscillatorNode", [
        ("frequency", "t -> AudioParam.t", "jsgp:frequency"),
        ("detune", "t -> AudioParam.t", "jsgp:detune"),
        ("oscillator_type", "t -> string", "jsgp:type"),
        ("set_oscillator_type", "t -> string -> unit", "jssp:type"),
        ("start", "t -> unit", "jsm:start"),
        ("stop", "t -> unit", "jsm:stop"),
    ]),
    M("AudioBuffer", [
        ("duration", "t -> float", "jsgp:duration"),
        ("length", "t -> int", "jsgp:length"),
        ("sample_rate", "t -> float", "jsgp:sampleRate"),
        ("number_of_channels", "t -> int", "jsgp:numberOfChannels"),
        ("get_channel_data", "t -> int -> t", "jsm:getChannelData"),
    ]),
    M("AudioBufferSourceNode", [
        ("buffer", "t -> AudioBuffer.t", "jsgp:buffer"),
        ("set_buffer", "t -> AudioBuffer.t -> unit", "jssp:buffer"),
        ("start", "t -> unit", "jsm:start"),
        ("stop", "t -> unit", "jsm:stop"),
    ]),
    M("AudioContext", [
        ("create", "unit -> t", "jsnew0:AudioContext"),
        ("current_time", "t -> float", "jsgp:currentTime"),
        ("sample_rate", "t -> float", "jsgp:sampleRate"),
        ("state", "t -> string", "jsgp:state"),
        ("destination", "t -> AudioNode.t", "jsgp:destination"),
        ("create_gain", "t -> GainNode.t", "jsm:createGain"),
        ("create_oscillator", "t -> OscillatorNode.t", "jsm:createOscillator"),
        ("create_buffer_source", "t -> AudioBufferSourceNode.t", "jsm:createBufferSource"),
        ("decode_audio_data", "t -> t -> Promise.t", "jsm:decodeAudioData"),
        ("resume", "t -> Promise.t", "jsm:resume"),
        ("suspend", "t -> Promise.t", "jsm:suspend"),
        ("close", "t -> Promise.t", "jsm:close"),
    ]),
    M("IntlDateTimeFormat", [
        ("create", "unit -> t", "jsnew0:Intl.DateTimeFormat"),
        ("format", "t -> Js.t -> string", "jsm:format"),
        ("resolved_options", "t -> Js.t", "jsgp:resolvedOptions"),
    ]),
    M("IntlNumberFormat", [
        ("create", "unit -> t", "jsnew0:Intl.NumberFormat"),
        ("format", "t -> float -> string", "jsm:format"),
        ("resolved_options", "t -> Js.t", "jsgp:resolvedOptions"),
    ]),
    M("IntlCollator", [
        ("create", "unit -> t", "jsnew0:Intl.Collator"),
        ("compare", "t -> string -> string -> int", "jsm:compare"),
        ("resolved_options", "t -> Js.t", "jsgp:resolvedOptions"),
    ]),
    M("Notification", [
        ("create", "string -> t", "jsnew:Notification"),
        ("request_permission", "unit -> Promise.t", "js0:Notification.requestPermission"),
        ("permission", "unit -> string", "js0:Notification.permission"),
        ("close", "t -> unit", "jsm:close"),
        ("title", "t -> string", "jsgp:title"),
        ("body", "t -> string", "jsgp:body"),
        ("on_click", "t -> (Event.t -> unit) -> unit", "jse:click"),
        ("on_close", "t -> (Event.t -> unit) -> unit", "jse:close"),
        ("on_error", "t -> (Event.t -> unit) -> unit", "jse:error"),
        ("on_show", "t -> (Event.t -> unit) -> unit", "jse:show"),
    ]),
    M("PerformanceObserver", [
        ("create", "(Js.t -> unit) -> t", "jsnew:PerformanceObserver"),
        ("observe", "t -> t -> unit", "jsm:observe"),
        ("disconnect", "t -> unit", "jsm:disconnect"),
        ("take_records", "t -> Js.t", "jsm:takeRecords"),
    ]),
    M("Permissions", [
        ("query", "t -> Js.t -> Promise.t", "jsm:query"),
    ]),
    M("StorageManager", [
        ("estimate", "t -> Promise.t", "jsm:estimate"),
        ("persisted", "t -> Promise.t", "jsm:persisted"),
        ("persist", "t -> Promise.t", "jsm:persist"),
    ]),
    M("Selection", [
        ("anchor_node", "t -> t", "jsgp:anchorNode"),
        ("focus_node", "t -> t", "jsgp:focusNode"),
        ("anchor_offset", "t -> int", "jsgp:anchorOffset"),
        ("focus_offset", "t -> int", "jsgp:focusOffset"),
        ("range_count", "t -> int", "jsgp:rangeCount"),
        ("is_collapsed", "t -> bool", "jsgp:isCollapsed"),
        ("remove_all_ranges", "t -> unit", "jsm:removeAllRanges"),
        ("collapse", "t -> t -> int -> unit", "jsm:collapse"),
        ("to_string", "t -> string", "jsm:toString"),
    ]),
]


RESERVED = {
    "and", "as", "assert", "begin", "class", "constraint", "do", "done",
    "downto", "else", "end", "exception", "external", "false", "for", "fun",
    "function", "functor", "if", "in", "include", "inherit", "initializer",
    "lazy", "let", "match", "method", "module", "mutable", "new", "object",
    "of", "open", "or", "private", "rec", "sig", "struct", "then", "to",
    "true", "try", "type", "val", "virtual", "when", "while", "with",
    "land", "lor", "lxor", "lsl", "lsr", "asr", "mod",
}


def emit(name, typename, members, prelude):
    lines = ["(* Generated by scripts/gen-bindings.py. Do not edit. *)"]
    if prelude:
        lines.append(prelude)
    if typename == "t":
        lines.append("type t")
        lines.append('external as_js : t -> Js.t = "%identity"')
        lines.append('external of_js : Js.t -> t = "%identity"')
    elif typename:
        lines.append("type %s" % typename)
    for fname, fsig in COERCIONS.get(name, []):
        lines.append('external %s : %s = "%%identity"' % (fname, fsig))
    wide = max((len(m[0]) for m in members), default=0)
    for mname, mtype, scheme in members:
        if mname in RESERVED:
            mname = mname + "_"
        lines.append('external %s : %s = "%s"' % (mname.ljust(wide), mtype, scheme))
    path = os.path.join(DIR, name[0].lower() + name[1:] + ".ml")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


NODE_ALIASES = {
    "Element", "HtmlElement", "HtmlDivElement", "HtmlInputElement",
    "HtmlCanvasElement", "HtmlImageElement", "Text", "Comment", "Attr",
    "NodeList", "HtmlCollection", "DomTokenList", "CssStyle", "Document",
    "DocumentFragment",
}

COERCIONS = {
    "UiEvent": [("as_event", "t -> Event.t"), ("of_event", "Event.t -> t")],
    "MouseEvent": [("as_ui_event", "t -> UiEvent.t"), ("of_ui_event", "UiEvent.t -> t"),
                   ("as_event", "t -> Event.t"), ("of_event", "Event.t -> t")],
    "WheelEvent": [("as_mouse_event", "t -> MouseEvent.t"), ("of_mouse_event", "MouseEvent.t -> t"),
                   ("as_event", "t -> Event.t"), ("of_event", "Event.t -> t")],
    "PointerEvent": [("as_mouse_event", "t -> MouseEvent.t"), ("of_mouse_event", "MouseEvent.t -> t"),
                     ("as_event", "t -> Event.t"), ("of_event", "Event.t -> t")],
    "DragEvent": [("as_mouse_event", "t -> MouseEvent.t"), ("of_mouse_event", "MouseEvent.t -> t"),
                  ("as_event", "t -> Event.t"), ("of_event", "Event.t -> t")],
    "TouchEvent": [("as_ui_event", "t -> UiEvent.t"), ("of_ui_event", "UiEvent.t -> t"),
                   ("as_event", "t -> Event.t"), ("of_event", "Event.t -> t")],
    "InputEvent": [("as_ui_event", "t -> UiEvent.t"), ("of_ui_event", "UiEvent.t -> t"),
                   ("as_event", "t -> Event.t"), ("of_event", "Event.t -> t")],
    "CompositionEvent": [("as_ui_event", "t -> UiEvent.t"), ("of_ui_event", "UiEvent.t -> t"),
                         ("as_event", "t -> Event.t"), ("of_event", "Event.t -> t")],
    "KeyboardEvent": [("as_event", "t -> Event.t"), ("of_event", "Event.t -> t")],
    "FocusEvent": [("as_event", "t -> Event.t"), ("of_event", "Event.t -> t")],
    "MessageEvent": [("as_event", "t -> Event.t"), ("of_event", "Event.t -> t")],
    "ProgressEvent": [("as_event", "t -> Event.t"), ("of_event", "Event.t -> t")],
    "SubmitEvent": [("as_event", "t -> Event.t"), ("of_event", "Event.t -> t")],
}


def main():
    os.makedirs(DIR, exist_ok=True)
    for name, typename, members, prelude in SPEC:
        if name in COERCIONS:
            typename = "t"
        elif name in NODE_ALIASES:
            typename = "t = Node.t"
        elif name == "Json":
            typename = "value"
        emit(name, typename, members, prelude)
    print("wrote %d binding modules to %s" % (len(SPEC), DIR))


if __name__ == "__main__":
    main()
