(* Generated by scripts/gen-bindings.py. Do not edit. *)
type t
external as_js : t -> Js.t = "%identity"
external of_js : Js.t -> t = "%identity"
external buffer     : t -> AudioBuffer.t = "jsgp:buffer"
external set_buffer : t -> AudioBuffer.t -> unit = "jssp:buffer"
external start      : t -> unit = "jsm:start"
external stop       : t -> unit = "jsm:stop"
