(* Generated by scripts/gen-bindings.py. Do not edit. *)
type t = Node.t
external html_for     : t -> string = "jsgp:htmlFor"
external set_html_for : t -> string -> unit = "jssp:htmlFor"
external control      : t -> t = "jsgp:control"
