(* Generated by scripts/gen-bindings.py. Do not edit. *)
type t = Node.t
external name        : t -> string = "jsgp:name"
external set_name    : t -> string -> unit = "jssp:name"
external content     : t -> string = "jsgp:content"
external set_content : t -> string -> unit = "jssp:content"
external http_equiv  : t -> string = "jsgp:httpEquiv"
external charset     : t -> string = "jsgp:charset"
