(* Generated by scripts/gen-bindings.py. Do not edit. *)
type t
external as_js : t -> Js.t = "%identity"
external of_js : Js.t -> t = "%identity"
external create    : unit -> t = "jsnew0:URLSearchParams"
external append    : t -> string -> string -> unit = "jsm:append"
external delete    : t -> string -> unit = "jsm:delete"
external get       : t -> string -> Js.t = "jsm:get"
external get_all   : t -> string -> Js.t = "jsm:getAll"
external has       : t -> string -> bool = "jsm:has"
external set       : t -> string -> string -> unit = "jsm:set"
external sort      : t -> unit = "jsm:sort"
external to_string : t -> string = "jsm:toString"
